Repository serverless/serverless, pull requests merged in 2019-02, with the labels that each got.

#5775 Preserve whitespaces in single-quote literal fallback
  lib/classes/Variables.js
  lib/classes/Variables.test.js
Labels: pr/in-review

#5785 Fixes for AWS cors config issues
  lib/plugins/aws/package/compile/events/apiGateway/lib/cors.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/cors.test.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/validate.test.js
Labels: bug/confirmed, pr/accepted

#5793 Fix race condition when loading config file
  lib/Serverless.js
  lib/classes/PluginManager.js
Labels: pr/in-review

#5794 fixed cli tests when running in debug mode
  lib/classes/CLI.test.js
Labels: pr/in-review

#5796 Set timout & others on context in python invoke local
  lib/plugins/aws/invokeLocal/index.js
Labels: pr/in-review

#5799 Append in Custom Syntax
  lib/classes/Variables.js
  lib/classes/Variables.test.js
Labels: pr/in-review

#5798 Don't load config for `config`
  lib/plugins/config/config.js
Labels: pr/in-review

#5791 Replace blocking fs.readFileSync with non blocking fs.readFile in checkForChanges.js
  lib/plugins/aws/deploy/lib/checkForChanges.js
  lib/plugins/aws/deploy/lib/checkForChanges.test.js
Labels: pr/in-review

#5787 Added layer option for deploy function update-config
  lib/plugins/aws/deployFunction/index.js
  lib/plugins/aws/deployFunction/index.test.js
Labels: pr/in-review

#5718 Make local ruby pry work
  lib/plugins/aws/invokeLocal/invoke.rb
Labels: pr/in-review

#5808 Replace \ with / in paths on windows before passing to nanomatch
  lib/plugins/package/lib/packageService.js
Labels: pr/in-review

#5816 Fix windows go rework
  lib/plugins/package/lib/packageService.js
  lib/plugins/package/lib/packageService.test.js
Labels: pr/in-review

#5826 Make use of join operator first argument in sns docs
  docs/providers/aws/events/sns.md
Labels: docs

#5821 add support for command type='container'
  lib/classes/CLI.js
  lib/classes/CLI.test.js
  lib/classes/PluginManager.js
  lib/classes/PluginManager.test.js
Labels: pr/in-review

#5819 Add Google Python function template
  docs/providers/google/cli-reference/create.md
  docs/providers/google/examples/README.md
  docs/providers/google/examples/hello-world/README.md
  docs/providers/google/examples/hello-world/python/README.md
  docs/providers/google/examples/hello-world/python/main.py
  docs/providers/google/examples/hello-world/python/package.json
  docs/providers/google/examples/hello-world/python/serverless.yml
  docs/providers/google/guide/services.md
  lib/plugins/create/create.js
  lib/plugins/create/create.test.js
  lib/plugins/create/templates/google-python/gitignore
  lib/plugins/create/templates/google-python/main.py
  lib/plugins/create/templates/google-python/package.json
  lib/plugins/create/templates/google-python/serverless.yml
  tests/templates/test_all_templates
Labels: pr/in-review

#5800 Update bucket conf to default AES256 encryption.
  docs/providers/aws/guide/deploying.md
  lib/plugins/aws/package/lib/core-cloudformation-template.json
  lib/plugins/aws/package/lib/generateCoreTemplate.js
  lib/plugins/aws/package/lib/generateCoreTemplate.test.js
  lib/plugins/aws/package/lib/mergeCustomProviderResources.test.js
Labels: pr/in-review

#5825 Fix: override wildcard glob pattern (**) in resolveFilePathsFromPatterns
  lib/plugins/package/lib/packageService.js
Labels: pr/in-review

#5832 Indicate unused context in aws-nodejs-typescipt
  lib/plugins/create/templates/aws-nodejs-typescript/handler.ts
Labels: pr/in-review

#5835 Add stack trace to aws/invokeLocal errors
  lib/plugins/aws/invokeLocal/index.js
  lib/plugins/aws/invokeLocal/index.test.js
Labels: pr/in-review

#5836 Missing underscore
  docs/providers/openwhisk/events/messagehub.md
Labels: docs, pr/in-review

#5690 Updating cloudformation resource reference url
  docs/providers/aws/events/s3.md
Labels: pr/in-progress, pr/in-review

#5843 [Docs] Replacing "runtimes" with "templates"
  docs/providers/aws/guide/services.md
Labels: pr/in-review

#5824 Add support for websockets event
  docs/providers/aws/README.md
  docs/providers/aws/events/alexa-skill.md
  docs/providers/aws/events/alexa-smart-home.md
  docs/providers/aws/events/cloudwatch-event.md
  docs/providers/aws/events/cloudwatch-log.md
  docs/providers/aws/events/cognito-user-pool.md
  docs/providers/aws/events/iot.md
  docs/providers/aws/events/s3.md
  docs/providers/aws/events/schedule.md
  docs/providers/aws/events/sns.md
  docs/providers/aws/events/sqs.md
  docs/providers/aws/events/streams.md
  docs/providers/aws/events/websocket.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/Plugins.json
  lib/plugins/aws/info/display.js
  lib/plugins/aws/info/display.test.js
  lib/plugins/aws/info/getResourceCount.test.js
  lib/plugins/aws/info/getStackInfo.js
  lib/plugins/aws/info/getStackInfo.test.js
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/lib/naming.test.js
  lib/plugins/aws/package/compile/events/websockets/index.js
  lib/plugins/aws/package/compile/events/websockets/index.test.js
  lib/plugins/aws/package/compile/events/websockets/lib/api.js
  lib/plugins/aws/package/compile/events/websockets/lib/api.test.js
  lib/plugins/aws/package/compile/events/websockets/lib/deployment.js
  lib/plugins/aws/package/compile/events/websockets/lib/deployment.test.js
  lib/plugins/aws/package/compile/events/websockets/lib/integrations.js
  lib/plugins/aws/package/compile/events/websockets/lib/integrations.test.js
  lib/plugins/aws/package/compile/events/websockets/lib/permissions.js
  lib/plugins/aws/package/compile/events/websockets/lib/permissions.test.js
  lib/plugins/aws/package/compile/events/websockets/lib/routes.js
  lib/plugins/aws/package/compile/events/websockets/lib/routes.test.js
  lib/plugins/aws/package/compile/events/websockets/lib/stage.js
  lib/plugins/aws/package/compile/events/websockets/lib/stage.test.js
  lib/plugins/aws/package/compile/events/websockets/lib/validate.js
  lib/plugins/aws/package/compile/events/websockets/lib/validate.test.js
  lib/plugins/create/templates/aws-clojure-gradle/serverless.yml
  lib/plugins/create/templates/aws-clojurescript-gradle/serverless.yml
  lib/plugins/create/templates/aws-csharp/serverless.yml
  lib/plugins/create/templates/aws-fsharp/serverless.yml
  lib/plugins/create/templates/aws-go-dep/serverless.yml
  lib/plugins/create/templates/aws-go-mod/serverless.yml
  lib/plugins/create/templates/aws-go/serverless.yml
  lib/plugins/create/templates/aws-groovy-gradle/serverless.yml
  lib/plugins/create/templates/aws-java-gradle/serverless.yml
  lib/plugins/create/templates/aws-java-maven/serverless.yml
  lib/plugins/create/templates/aws-kotlin-jvm-gradle/serverless.yml
  lib/plugins/create/templates/aws-kotlin-jvm-maven/serverless.yml
  lib/plugins/create/templates/aws-kotlin-nodejs-gradle/serverless.yml
  lib/plugins/create/templates/aws-nodejs/serverless.yml
  lib/plugins/create/templates/aws-provided/serverless.yml
  lib/plugins/create/templates/aws-python/serverless.yml
  lib/plugins/create/templates/aws-python3/serverless.yml
  lib/plugins/create/templates/aws-ruby/serverless.yml
  lib/plugins/create/templates/aws-scala-sbt/serverless.yml
Labels: pr/in-review

#5842 AWS: ${ssm} resolve vairbale as JSON if it is stored as JSON in Secrets Manager
  docs/providers/aws/guide/variables.md
  lib/classes/Variables.js
  lib/classes/Variables.test.js
Labels: pr/in-review

#5839 Fix service name in template install message
  lib/plugins/create/create.js
  lib/plugins/create/create.test.js
  lib/plugins/install/install.js
  lib/plugins/install/install.test.js
  lib/utils/downloadTemplateFromRepo.js
  lib/utils/downloadTemplateFromRepo.test.js
Labels: pr/in-review

#5852 Releasing v1.38.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: pr/in-review

#5849 Update README.md
  README.md
Labels: pr/in-review

#5850 Update shared API instructions
  docs/providers/aws/events/apigateway.md
Labels: pr/in-review

#5859 Add details to websocket documentation
  docs/providers/aws/events/websocket.md
Labels: pr/in-review

#5840 Packaging exclude only config file being used
  docs/providers/aws/guide/packaging.md
  lib/classes/PluginManager.js
  lib/plugins/package/lib/packageService.js
  lib/plugins/package/lib/packageService.test.js
  lib/utils/getServerlessConfigFile.js
  lib/utils/getServerlessConfigFile.test.js
Labels: pr/in-review

#5854 Removing the context parameter from aws-nodejs template
  lib/plugins/create/templates/aws-nodejs/handler.js
Labels: pr/in-review

#5443 Improves usage and documentation of SNS event sources.
  docs/providers/aws/events/sns.md
  lib/plugins/aws/package/compile/events/sns/index.js
  lib/plugins/aws/package/compile/events/sns/index.test.js
  tests/integration/aws/sns/existing-topic/service/serverless.yml
  tests/integration/aws/sns/existing-topic/tests.js
Labels: pr/in-review

#5274 Added ability to add S3 deployment resource tags
  docs/providers/aws/guide/serverless.yml.md
  docs/providers/aws/guide/services.md
  lib/plugins/aws/package/lib/generateCoreTemplate.js
  lib/plugins/aws/package/lib/generateCoreTemplate.test.js
Labels: pr/in-review

#5862 Put `Custom Response Headers` into `[Responses]`
  docs/providers/aws/events/apigateway.md
Labels: pr/in-review

#5872 Enchancement/kotlin jvm maven updates
  lib/plugins/create/templates/aws-kotlin-jvm-maven/pom.xml
  lib/plugins/create/templates/aws-kotlin-jvm-maven/src/main/kotlin/com/serverless/ApiGatewayResponse.kt
  lib/plugins/create/templates/aws-kotlin-jvm-maven/src/main/kotlin/com/serverless/Handler.kt
  lib/plugins/create/templates/aws-kotlin-jvm-maven/src/main/resources/log4j2.xml
Labels: pr/in-review

#5865 Websockets: Support more route characters
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/lib/naming.test.js
Labels: cat/event-src, enhancement, pr/in-review

#5867 Added websockets authorizer support
  docs/providers/aws/events/websocket.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/lib/naming.test.js
  lib/plugins/aws/package/compile/events/websockets/index.js
  lib/plugins/aws/package/compile/events/websockets/index.test.js
  lib/plugins/aws/package/compile/events/websockets/lib/authorizers.js
  lib/plugins/aws/package/compile/events/websockets/lib/authorizers.test.js
  lib/plugins/aws/package/compile/events/websockets/lib/permissions.js
  lib/plugins/aws/package/compile/events/websockets/lib/permissions.test.js
  lib/plugins/aws/package/compile/events/websockets/lib/routes.js
  lib/plugins/aws/package/compile/events/websockets/lib/routes.test.js
  lib/plugins/aws/package/compile/events/websockets/lib/validate.js
  lib/plugins/aws/package/compile/events/websockets/lib/validate.test.js
Labels: pr/in-progress
