Repository serverless/serverless, pull requests merged in 2019-01, with the labels that each got.

#5638 Add warning for multiple functions having same handler
  lib/classes/Service.js
  lib/classes/Service.test.js
Labels: stage/in-review

#5639 Add stage name validation to AWS provider.
  lib/plugins/aws/provider/awsProvider.js
  lib/plugins/aws/provider/awsProvider.test.js
Labels: stage/in-review

#5312 Handle scoped npm packages in ${file()} variables
  docs/providers/aws/guide/variables.md
  lib/classes/Service.js
  lib/classes/Service.test.js
  lib/classes/Utils.js
  lib/classes/Variables.js
  lib/classes/Variables.test.js
  lib/plugins/print/print.js
  lib/plugins/print/print.test.js
Labels: stage/in-review

#5694 AWS: Request cache should add region as key to prevent cross-region cache collision
  lib/plugins/aws/provider/awsProvider.js
  lib/plugins/aws/provider/awsProvider.test.js
Labels: pr/in-review

#5707 Fixed a link
  docs/providers/aws/cli-reference/slstats.md
Labels: pr/in-review

#5695 Increase @types/aws-lambda version in aws-nodejs-typescript template
  lib/plugins/create/templates/aws-nodejs-typescript/package.json
Labels: pr/in-review

#5680 Clarify docs for the http key for GCF
  docs/providers/google/events/http.md
Labels: pr/in-progress

#5130 docs: Kubeless secrets
  docs/providers/kubeless/guide/functions.md
Labels: pr/in-review

#5688 Fix awsProvider.js : "Cannot use 'in' operator to search for '0'
  lib/classes/Service.js
  lib/classes/Service.test.js
  lib/classes/Variables.js
  lib/classes/Variables.test.js
Labels: pr/in-review

#5702 Fix array notation in stream ARN
  docs/providers/aws/events/streams.md
Labels: pr/in-progress

#5687 Remove platform code
  bin/serverless
  docs/README.md
  docs/platform/README.md
  docs/platform/commands/README.md
  docs/platform/commands/login.md
  docs/platform/commands/logout.md
  lib/Serverless.js
  lib/classes/CLI.js
  lib/plugins/Plugins.json
  lib/plugins/aws/deploy/index.js
  lib/plugins/aws/deploy/lib/createDeployment.js
  lib/plugins/aws/deploy/lib/createStack.js
  lib/plugins/aws/deploy/lib/createStack.test.js
  lib/plugins/aws/deploy/lib/validateTemplate.js
  lib/plugins/aws/deploy/lib/validateTemplate.test.js
  lib/plugins/aws/invokeLocal/index.js
  lib/plugins/aws/logs/index.js
  lib/plugins/login/login.js
  lib/plugins/login/login.test.js
  lib/plugins/logout/logout.js
  lib/plugins/logout/logout.test.js
  lib/plugins/package/lib/packageService.js
  lib/plugins/platform/platform.js
  lib/utils/getAccessKey.js
  lib/utils/getUser.js
  lib/utils/isLoggedIn.js
  package-lock.json
Labels: pr/in-progress

#5725 Update aws-scala-sbt template
  lib/plugins/create/templates/aws-scala-sbt/build.sbt
  lib/plugins/create/templates/aws-scala-sbt/project/assembly.sbt
  lib/plugins/create/templates/aws-scala-sbt/project/build.properties
  lib/plugins/create/templates/aws-scala-sbt/project/plugins.sbt
Labels: pr/in-review

#5531 AWS: Consolidates Lambda::Permission objects for cloudwatchLog events
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/lib/naming.test.js
  lib/plugins/aws/package/compile/events/cloudWatchLog/index.js
  lib/plugins/aws/package/compile/events/cloudWatchLog/index.test.js
Labels: pr/in-review

#5723 Suppress confusing warning "A valid undefined..."
  lib/classes/Variables.js
  lib/classes/Variables.test.js
Labels: pr/in-review

#5662 Provide AWS_PROFILE from configuration for invoke local
  lib/plugins/aws/invokeLocal/index.js
  lib/plugins/aws/invokeLocal/index.test.js
  lib/plugins/aws/provider/awsProvider.js
  lib/plugins/aws/provider/awsProvider.test.js
Labels: pr/in-review

#5715 Enable download template from a private github repo using personal access token
  lib/utils/downloadTemplateFromRepo.js
Labels: pr/in-progress

#5738 Update getting-started.md
  docs/getting-started.md
Labels: pr/in-review

#5705 Convert reservedConcurrency to integer to allow use env var
  lib/plugins/aws/package/compile/functions/index.js
  lib/plugins/aws/package/compile/functions/index.test.js
Labels: pr/in-review

#5311 Upgrade google-cloudfunctions to v2 and set defaults to node8 etc
  lib/plugins/create/templates/google-nodejs/serverless.yml
Labels: pr/in-review

#4888 Fix broken Azure Hello World Example documentation
  docs/providers/azure/examples/hello-world/node/README.md
Labels: pr/in-review

#4712 Enable tab completion for slss shortcut
  scripts/postinstall.js
Labels: pr/in-review

#5495 Add uploaded file name to log while AWS deploy
  lib/plugins/aws/deploy/lib/uploadArtifacts.js
  lib/plugins/aws/deploy/lib/uploadArtifacts.test.js
Labels: pr/in-review

#5720 Lambda Layers - cast account id to string if number provided
  lib/plugins/aws/package/compile/layers/index.js
  lib/plugins/aws/package/compile/layers/index.test.js
Labels: pr/in-review

#5731 Fix link
  docs/providers/aws/guide/variables.md
Labels: pr/in-review

#4822 Add resource count and warning to info display
  lib/plugins/aws/info/display.js
  lib/plugins/aws/info/display.test.js
  lib/plugins/aws/info/getResourceCount.js
  lib/plugins/aws/info/getResourceCount.test.js
  lib/plugins/aws/info/index.js
  lib/plugins/aws/info/index.test.js
Labels: pr/in-review

#5161 Updated aws provider to invoke .promise on methods that support it. Otherwise falls back to .send with a callback
  lib/plugins/aws/provider/awsProvider.js
  lib/plugins/aws/provider/awsProvider.test.js
Labels: pr/in-review

#5577 Add template for provided runtime with the bash sample from AWS
  docs/providers/aws/cli-reference/create.md
  docs/providers/aws/guide/services.md
  lib/plugins/create/create.js
  lib/plugins/create/create.test.js
  lib/plugins/create/templates/aws-provided/bootstrap
  lib/plugins/create/templates/aws-provided/gitignore
  lib/plugins/create/templates/aws-provided/handler.sh
  lib/plugins/create/templates/aws-provided/serverless.yml
  tests/templates/test_all_templates
Labels: pr/in-progress

#5754 Add Hello World Ruby Example
  docs/providers/aws/examples/hello-world/ruby/README.md
Labels: pr/accepted

#5728 Do not print logs if print command is used.
  lib/Serverless.js
  lib/classes/CLI.js
  lib/classes/CLI.test.js
Labels: pr/in-review

#5714 AWS: Tell S3 bucket name and how to recover if deployment bucket does not exist
  lib/plugins/aws/deploy/lib/checkForChanges.js
  lib/plugins/aws/deploy/lib/checkForChanges.test.js
Labels: pr/in-progress

#5710 Fix #5664 - Rollback fails due to a timestamp parsing error
  lib/plugins/aws/rollback/index.js
  lib/plugins/aws/rollback/index.test.js
Labels: pr/in-progress

#5139 Allows Fn::GetAtt with Lambda DLQ-onError
  docs/providers/aws/guide/functions.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/compile/functions/index.js
  lib/plugins/aws/package/compile/functions/index.test.js
Labels: pr/in-review

#5744 Resolve profile before performing aws-sdk dependent actions
  lib/classes/Variables.js
  lib/classes/Variables.test.js
  lib/plugins/aws/provider/awsProvider.js
Labels: pr/in-review

#5760 don't check call tty on macs
  lib/plugins/aws/invokeLocal/invoke.py
Labels: pr/in-review

#5656 handle layers paths with trailing slash and leading ./ or just .
  lib/plugins/package/lib/packageService.js
  lib/plugins/package/lib/packageService.test.js
  lib/plugins/package/lib/zipService.js
Labels: pr/in-review

#5763 Require provider.credentials vars to be resolved before s3/ssm/cf vars
  lib/classes/Variables.js
  lib/classes/Variables.test.js
Labels: pr/in-review

#5636 Throw an error if plugin is executed outside of a serverless directory
  lib/Serverless.js
  lib/classes/PluginManager.js
  lib/classes/PluginManager.test.js
Labels: pr/in-review
