Repository serverless/serverless, pull requests merged in 2019-08, with the labels that each got.

#6484 Fix invalid path char in GoLang packaging on Windows
  lib/plugins/package/lib/packageService.js
  lib/plugins/package/lib/packageService.test.js
Labels: bug, cat/deployment, os/windows, pr/in-review

#6477 Multiple event definitions for existing S3 bucket
  docs/providers/aws/events/s3.md
  lib/plugins/aws/customResources/resources/s3/handler.js
  lib/plugins/aws/customResources/resources/s3/lib/bucket.js
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/lib/naming.test.js
  lib/plugins/aws/package/compile/events/s3/index.js
  lib/plugins/aws/package/compile/events/s3/index.test.js
  tests/integration-all/s3/service/core.js
  tests/integration-all/s3/service/serverless.yml
  tests/integration-all/s3/tests.js
Labels: bug, cat/event-src, pr/in-review

#6501 Remove Enterprise and Platform from log info
  lib/classes/CLI.js
  lib/classes/CLI.test.js
Labels: cat/enterprise, enhancement, pr/in-review

#6471 Allow AWS Subscription Filters to be reordered
  lib/plugins/aws/deploy/lib/checkForChanges.js
  lib/plugins/aws/deploy/lib/checkForChanges.test.js
Labels: bug, cat/event-src, pr/in-review

#6506 Check if more than 1 existing bucket is configured
  lib/plugins/aws/package/compile/events/s3/index.js
  lib/plugins/aws/package/compile/events/s3/index.test.js
Labels: cat/dx, enhancement, pr/in-review

#6491 Multiple event definitions for existing Cognito User Pools
  docs/providers/aws/events/cognito-user-pool.md
  lib/plugins/aws/customResources/resources/cognitoUserPool/handler.js
  lib/plugins/aws/customResources/resources/cognitoUserPool/lib/userPool.js
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/lib/naming.test.js
  lib/plugins/aws/package/compile/events/cognitoUserPool/index.js
  lib/plugins/aws/package/compile/events/cognitoUserPool/index.test.js
  tests/integration-all/cognito-user-pool/service/core.js
  tests/integration-all/cognito-user-pool/service/serverless.yml
  tests/integration-all/cognito-user-pool/tests.js
  tests/utils/cognito/index.js
Labels: bug, cat/event-src, pr/in-review

#6502 Improve error handling
  bin/serverless.js
  lib/classes/Error.js
  lib/classes/Error.test.js
Labels: enhancement, pr/in-review

#6511 Add PreTokenGeneration & UserMigration Cognito triggers
  lib/plugins/aws/package/compile/events/cognitoUserPool/index.js
Labels: cat/event-src, enhancement, pr/in-review

#6467 Add Twilio Runtime to create templates
  docker-compose.yml
  lib/plugins/create/create.js
  lib/plugins/create/create.test.js
  lib/plugins/create/templates/twilio-nodejs/example.jpg
  lib/plugins/create/templates/twilio-nodejs/gitignore
  lib/plugins/create/templates/twilio-nodejs/handler.js
  lib/plugins/create/templates/twilio-nodejs/package-lock.json
  lib/plugins/create/templates/twilio-nodejs/package.json
  lib/plugins/create/templates/twilio-nodejs/serverless.yml
  tests/templates/test-all-templates
Labels: cat/templates, feature, pr/in-review

#6513 Update kubeless guide docs
  docs/providers/kubeless/guide/functions.md
Labels: cat/providers, docs, pr/in-review

#6417 Fix ImportValue handling in existing S3 buckets #6416
  lib/plugins/aws/package/compile/events/s3/index.js
  lib/plugins/aws/package/compile/events/s3/index.test.js
Labels: bug, cat/event-src, pr/in-review

#6449 Improve interactive AWS creds flow
  lib/plugins/interactiveCli/setupAws.js
  lib/utils/open.js
  lib/utils/openBrowser.js
  package.json
Labels: cat/providers, enhancement, pr/in-review

#6519 Retain existing Cognito User Pool config
  lib/plugins/aws/customResources/resources/cognitoUserPool/lib/userPool.js
  tests/integration-all/cognito-user-pool/tests.js
  tests/utils/cognito/index.js
Labels: bug, cat/event-src, pr/in-review

#6517 Switch integration tests runner from Jest to Mocha
  .travis.yml
  package.json
  scripts/test-isolated.js
  tests/integration-all/api-gateway/tests.js
  tests/integration-all/cognito-user-pool/tests.js
  tests/integration-all/event-bridge/tests.js
  tests/integration-all/s3/tests.js
  tests/integration-basic/tests.js
  tests/integration-package/cloudformation.tests.js
  tests/integration-package/lambda-files.tests.js
  tests/mocha-reporter.js
  tests/setup-tests.js
  tests/utils/misc/index.js
Labels: pr/in-review, tests

#6520 Change strategy for deciding to deploy new function.
  lib/plugins/aws/deploy/lib/checkForChanges.js
  lib/plugins/aws/deploy/lib/checkForChanges.test.js
Labels: cat/deployment, enhancement, pr/in-review

#6518 Fix support for EventBridge partner event sources
  lib/plugins/aws/customResources/resources/eventBridge/lib/utils.js
  lib/plugins/aws/package/compile/events/eventBridge/index.js
  lib/plugins/aws/package/compile/events/eventBridge/index.test.js
Labels: bug, cat/event-src, pr/in-review

#6526 fix(GITHUB-6525-5172): Rewrite copyDirContentsSyncAllow to call fs-extra::copySync() on the directories instead of calling it on the files to copy individually
  lib/classes/Utils.test.js
  lib/utils/fs/copyDirContentsSync.js
  lib/utils/fs/copyDirContentsSync.test.js
Labels: bug

#6535 Do not crash CI on Coveralls error
  .travis.yml
Labels: pr/in-review, tests

#6531 Setup APIGW CloudWatch role via custom resource
  .travis.yml
  lib/plugins/aws/customResources/.eslintrc.js
  lib/plugins/aws/customResources/index.js
  lib/plugins/aws/customResources/index.test.js
  lib/plugins/aws/customResources/resources/apiGatewayCloudWatchRole/handler.js
  lib/plugins/aws/customResources/resources/utils.js
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/lib/naming.test.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/stage/index.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/stage/index.test.js
  tests/integration-all/api-gateway/tests.js
  tests/utils/misc/index.js
Labels: bug, pr/in-review

#6537 Fix deploy command if package.individually set on a function-level
  README.md
  lib/plugins/aws/deploy/lib/extendedValidate.js
  lib/plugins/aws/deploy/lib/extendedValidate.test.js
Labels: bug, cat/packaging, pr/in-review

#6547 add docs for options misused in #6546
  docs/providers/aws/guide/serverless.yml.md
Labels: docs

#6548 AWS API Gateway set value of provider.logRetentionInDays for log group expiration
  lib/plugins/aws/package/compile/events/apiGateway/lib/stage/index.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/stage/index.test.js
  lib/plugins/aws/package/lib/mergeIamTemplates.js
  lib/plugins/aws/provider/awsProvider.js
Labels: cat/api-gw, enhancement

#6543 Add support for external websocketApiId
  lib/plugins/aws/package/compile/events/websockets/lib/deployment.js
  lib/plugins/aws/package/compile/events/websockets/lib/deployment.test.js
  lib/plugins/aws/package/compile/events/websockets/lib/stage.js
  lib/plugins/aws/package/compile/events/websockets/lib/stage.test.js
  package.json
  tests/integration-all/websocket/service/core.js
  tests/integration-all/websocket/service/serverless.yml
  tests/integration-all/websocket/tests.js
  tests/utils/misc/index.js
  tests/utils/websocket/index.js
Labels: bug

#6571 Ensure AWS SDK is mocked for tests that call it
  lib/plugins/aws/deploy/lib/checkForChanges.test.js
Labels: pr/in-review, tests

#6586 Allow unresolved Rest API id with provider.tags setting
  lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
Labels: bug, cat/api-gw

#6585 Improve error reporting
  lib/classes/Error.js
  lib/classes/Error.test.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
Labels: cat/dx, enhancement

#6589 Fix exclusion of Yarn logs in Lambda packages
  lib/plugins/package/lib/packageService.js
Labels: cat/packaging, enhancement

#6587 Improve Rest API id resolution for SDK updates
  lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js
Labels: bug, cat/api-gw, pr/in-review

#6549 Interactive CLI interactive hook
  lib/plugins/interactiveCli/index.js
Labels: cat/dashboard, enhancement, pr/in-review

#6588 Fix ServerlessError handling
  lib/classes/Error.js
  lib/classes/Error.test.js
  lib/plugins/aws/deploy/lib/createStack.js
  lib/plugins/aws/deploy/lib/createStack.test.js
Labels: bug, cat/dx, pr/in-review

#6599 PLAT-1629 - Fix custom resource lambda naming
  lib/plugins/aws/customResources/index.js
  lib/plugins/aws/customResources/index.test.js
Labels: bug, cat/packaging, pr/in-review

#6591 Ensure API Gateway CloudWatch role is setup via custom resource
  lib/plugins/aws/customResources/index.js
  lib/plugins/aws/customResources/index.test.js
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/lib/naming.test.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/stage/index.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/stage/index.test.js
  lib/plugins/aws/package/compile/events/cognitoUserPool/index.js
  lib/plugins/aws/package/compile/events/cognitoUserPool/index.test.js
  lib/plugins/aws/package/compile/events/eventBridge/index.js
  lib/plugins/aws/package/compile/events/eventBridge/index.test.js
  lib/plugins/aws/package/compile/events/lib/ensureApiGatewayCloudWatchRole.js
  lib/plugins/aws/package/compile/events/lib/ensureApiGatewayCloudWatchRole.test.js
  lib/plugins/aws/package/compile/events/s3/index.js
  lib/plugins/aws/package/compile/events/s3/index.test.js
  lib/plugins/aws/package/compile/events/websockets/lib/stage.js
  lib/plugins/aws/package/compile/events/websockets/lib/stage.test.js
Labels: bug, cat/api-gw, pr/in-review

#6603 Release v1.51.0
  CHANGELOG.md
  package.json
Labels: pr/in-review
