Repository serverless/serverless, pull requests merged in 2019-07, with the labels that each got.

#6323 Add null as a consultant
  README.md
Labels: docs, enhancement, pr/in-review

#6321 Update very minor typo in credentials.md
  docs/providers/aws/guide/credentials.md
Labels: cat/providers, docs, pr/in-review

#6318 Expose non-errors in informative way
  lib/classes/Error.js
  lib/classes/Error.test.js
Labels: bug, cat/dx, pr/in-review

#6319 Fix async leaks detection conditional
  tests/mocha-reporter.js
Labels: pr/in-review, tests

#6325 Typo fix in AWS ALB event documentation
  docs/providers/aws/events/alb.md
Labels: cat/event-src, docs, pr/in-review

#6310 Websockets: fix passing log group ARN
  lib/plugins/aws/package/compile/events/websockets/lib/stage.js
  lib/plugins/aws/package/compile/events/websockets/lib/stage.test.js
Labels: bug, cat/api-gw, pr/in-review

#6327 specify invoke local option in the guide
  README.md
Labels: cat/providers, docs, pr/in-review

#6324 Update Webpack version and usage of aws-nodejs-ecma-script template
  lib/plugins/create/templates/aws-nodejs-ecma-script/package.json
  lib/plugins/create/templates/aws-nodejs-ecma-script/webpack.config.js
Labels: bug, cat/templates, pr/in-review

#6322 Make ALB event target group names unique
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/lib/naming.test.js
  lib/plugins/aws/package/compile/events/alb/lib/targetGroups.js
  lib/plugins/aws/package/compile/events/alb/lib/targetGroups.test.js
Labels: cat/event-src, enhancement, pr/in-review

#6330 Improve Travis CI conf
  .travis.yml
Labels: pr/in-review

#6332 Support for Github Entreprise in sls create
  docs/providers/aws/cli-reference/install.md
  docs/providers/azure/cli-reference/install.md
  docs/providers/google/cli-reference/install.md
  docs/providers/openwhisk/cli-reference/install.md
  lib/utils/downloadTemplateFromRepo.js
  lib/utils/downloadTemplateFromRepo.test.js
Labels: cat/templates, feature, pr/in-review

#6290 Add support for existing S3 buckets
  docs/providers/aws/events/s3.md
  lib/plugins/aws/customResources/index.js
  lib/plugins/aws/customResources/index.test.js
  lib/plugins/aws/customResources/resources/README.md
  lib/plugins/aws/customResources/resources/s3/handler.js
  lib/plugins/aws/customResources/resources/s3/lib/bucket.js
  lib/plugins/aws/customResources/resources/s3/lib/permissions.js
  lib/plugins/aws/customResources/resources/utils.js
  lib/plugins/aws/customResources/resources/utils.test.js
  lib/plugins/aws/deploy/lib/uploadArtifacts.js
  lib/plugins/aws/deploy/lib/uploadArtifacts.test.js
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/lib/naming.test.js
  lib/plugins/aws/package/compile/events/s3/index.js
  lib/plugins/aws/package/compile/events/s3/index.test.js
  lib/utils/fs/createZipFile.js
  lib/utils/fs/createZipFile.test.js
  tests/integration-all/s3/service/core.js
  tests/integration-all/s3/service/serverless.yml
  tests/integration-all/s3/service/utils.js
  tests/integration-all/s3/tests.js
  tests/utils/misc/index.js
  tests/utils/s3/index.js
Labels: cat/event-src, feature, pr/in-review

#6294 PLAT-1202 - Interactive `serverless` create
  bin/serverless.js
  lib/classes/PluginManager.test.js
  lib/classes/Service.js
  lib/plugins/Plugins.json
  lib/plugins/aws/configCredentials/awsConfigCredentials.js
  lib/plugins/aws/configCredentials/awsConfigCredentials.test.js
  lib/plugins/aws/utils/credentials.js
  lib/plugins/aws/utils/credentials.test.js
  lib/plugins/create/create.js
  lib/plugins/interactiveCli/index.js
  lib/plugins/interactiveCli/index.test.js
  lib/plugins/interactiveCli/initializeService.js
  lib/plugins/interactiveCli/inquirer.js
  lib/plugins/interactiveCli/setupAws.js
  lib/plugins/interactiveCli/utils.js
  lib/utils/createFromTemplate.js
  lib/utils/createFromTemplate.test.js
  lib/utils/getServerlessConfigFile.js
  package.json
Labels: cat/dx, feature, pr/in-review

#6238 PLAT-1091 - message in `npm i` output about the `serverless` quickstart command
  scripts/postinstall.js
Labels: cat/dx, pr/in-review

#6365 Allow optionally splitting SSM parameter value for StringList type
  docs/providers/aws/guide/variables.md
  lib/classes/Variables.js
  lib/classes/Variables.test.js
Labels: cat/variable, feature, pr/in-review

#6366 Cross region SNS Trigger
  docs/providers/aws/events/sns.md
  lib/plugins/aws/package/compile/events/sns/index.js
  lib/plugins/aws/package/compile/events/sns/index.test.js
Labels: cat/event-src, feature, pr/in-review

#6367 Fix premature interactiveCli setup
  lib/plugins/interactiveCli/index.js
Labels: bug, pr/in-review

#6379 Fix typo
  docs/providers/google/guide/quick-start.md
Labels: cat/providers, docs, pr/in-review

#6345 Add SLS_NO_WARNINGS env var
  lib/classes/CLI.js
  lib/classes/Error.js
  lib/classes/Error.test.js
Labels: cat/dx, enhancement, pr/in-review

#6385 Fix async S3 test
  lib/plugins/aws/package/compile/events/s3/index.test.js
Labels: cat/event-src, pr/in-review, tests

#6377 Log message out when user says no to aws setup
  lib/plugins/interactiveCli/setupAws.js
Labels: cat/dx, enhancement, pr/in-review

#6387 Fix AWS secret access key validation in interactive CLI
  lib/plugins/interactiveCli/setupAws.js
Labels: bug, pr/in-review

#6388 Improve post install message
  scripts/postinstall.js
Labels: enhancement, pr/in-review

#6386 PLAT-1385 Ensure expected service name in interactively created project
  lib/plugins/create/create.js
  lib/utils/createFromTemplate.js
  lib/utils/createFromTemplate.test.js
Labels: bug, pr/in-review

#6378 If user has no profiles, always create them the default profile
  lib/plugins/interactiveCli/setupAws.js
Labels: cat/dx, enhancement, pr/in-review

#6372 Updated gradle and kotlin.js gradle plugin fixing #5598
  lib/plugins/create/create.test.js
  lib/plugins/create/templates/aws-kotlin-nodejs-gradle/build.gradle
  lib/plugins/create/templates/aws-kotlin-nodejs-gradle/build.gradle.kts
  lib/plugins/create/templates/aws-kotlin-nodejs-gradle/gradle/wrapper/gradle-wrapper.properties
  lib/plugins/create/templates/aws-kotlin-nodejs-gradle/package.json
  lib/plugins/create/templates/aws-kotlin-nodejs-gradle/serverless.yml
  lib/plugins/create/templates/aws-kotlin-nodejs-gradle/settings.gradle.kts
Labels: bug, cat/templates, pr/in-review

#6350 Integrating Components
  bin/serverless.js
  package.json
Labels: feature, pr/in-review

#6362 Add support for existing Cognito User Pools
  docs/providers/aws/events/cognito-user-pool.md
  lib/plugins/aws/customResources/index.js
  lib/plugins/aws/customResources/index.test.js
  lib/plugins/aws/customResources/resources/cognitoUserPool/handler.js
  lib/plugins/aws/customResources/resources/cognitoUserPool/lib/permissions.js
  lib/plugins/aws/customResources/resources/cognitoUserPool/lib/userPool.js
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/lib/naming.test.js
  lib/plugins/aws/package/compile/events/cognitoUserPool/index.js
  lib/plugins/aws/package/compile/events/cognitoUserPool/index.test.js
  tests/integration-all/cognito-user-pool/service/core.js
  tests/integration-all/cognito-user-pool/service/serverless.yml
  tests/integration-all/cognito-user-pool/tests.js
  tests/integration-all/s3/service/core.js
  tests/integration-all/s3/tests.js
  tests/integration-all/shared/utils.js
  tests/setup-tests.js
  tests/utils/cognito/index.js
  tests/utils/misc/index.js
Labels: cat/event-src, feature, pr/in-review

#6398 Add the missing colon
  docs/providers/aws/events/streams.md
Labels: cat/event-src, docs, pr/in-review

#6373 Documentation Updates
  docs/README.md
  docs/dashboard/README.md
  docs/dashboard/access-roles.md
  docs/dashboard/insights.md
  docs/dashboard/notifications.md
  docs/dashboard/output-variables.md
  docs/dashboard/pipelines.md
  docs/dashboard/profiles.md
  docs/dashboard/safeguards.md
  docs/dashboard/secrets.md
  docs/getting-started.md
  docs/providers/README.md
  docs/providers/aws/README.md
  docs/providers/aws/cli-reference/README.md
  docs/providers/aws/cli-reference/login.md
  docs/providers/aws/cli-reference/plugin-install.md
  docs/providers/aws/cli-reference/plugin-list.md
  docs/providers/aws/cli-reference/plugin-search.md
  docs/providers/aws/cli-reference/plugin-uninstall.md
  docs/providers/aws/cli-reference/print.md
  docs/providers/aws/cli-reference/rollback.md
  docs/providers/aws/cli-reference/slstats.md
  docs/providers/aws/events/README.md
  docs/providers/aws/examples/README.md
  docs/providers/aws/guide/README.md
  docs/providers/aws/guide/credentials.md
  docs/providers/aws/guide/installation.md
  docs/providers/aws/guide/quick-start.md
  docs/providers/aws/guide/services.md
  docs/providers/aws/guide/v0_to_v1.md
  docs/providers/aws/guide/workflow.md
Labels: docs, pr/in-review

#6402 Changed AWS subscription filters to use function object name
  lib/plugins/aws/deploy/lib/checkForChanges.js
  lib/plugins/aws/deploy/lib/checkForChanges.test.js
Labels: bug, cat/deployment, pr/in-review

#6393 Fail faster when no AWS creds exist
  lib/plugins/aws/provider/awsProvider.js
  lib/plugins/aws/provider/awsProvider.test.js
Labels: cat/providers, enhancement, pr/in-review

#6408 Strip trailing comment when renaming a service
  lib/utils/renameService.js
  lib/utils/renameService.test.js
Labels: cat/templates, enhancement, pr/in-review

#6410 Improve tracking reliability
  bin/serverless.js
  lib/classes/Error.js
  lib/classes/Error.test.js
  lib/classes/Utils.js
  lib/classes/Utils.test.js
  lib/utils/isTrackingDisabled.js
  lib/utils/segment.js
  lib/utils/tracking.js
  lib/utils/tracking.test.js
  lib/utils/userStats.js
  tests/mocha-reporter.js
Labels: bug, pr/in-review

#6411 Fix broken lint outcome after 'no-confusing-arrow' change
  lib/classes/Variables.test.js
  lib/plugins/aws/invokeLocal/index.js
  lib/plugins/aws/invokeLocal/index.test.js
  lib/plugins/aws/provider/awsProvider.js
  lib/plugins/package/lib/packageService.js
  lib/utils/getServerlessConfigFile.js
Labels: cleanup

#6415 Fix postinstall and preuninstall scripts
  CHANGELOG.md
  package.json
  scripts/postinstall.js
  scripts/preuninstall.js
Labels: bug

#6422 Issue 6364 request path
  docs/providers/aws/events/apigateway.md
  lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration.js
Labels: cat/api-gw, enhancement, pr/in-progress

#6419 Remove spaces from Cognito Pool Name
  lib/plugins/aws/customResources/resources/cognitoUserPool/lib/permissions.js
  tests/integration-all/cognito-user-pool/tests.js
Labels: bug, cat/event-src, pr/in-review

#6428 Use slss.io for links
  lib/classes/CLI.js
  lib/plugins/aws/provider/awsProvider.js
  lib/plugins/interactiveCli/setupAws.js
Labels: cat/dx, enhancement, pr/in-review

#6427 Fix #6414 by checking for ec2 metadata
  CHANGELOG.md
  lib/plugins/aws/invoke/index.test.js
  lib/plugins/aws/invokeLocal/index.test.js
  lib/plugins/aws/lib/validate.js
  lib/plugins/aws/lib/validate.test.js
  lib/plugins/aws/logs/index.test.js
  lib/plugins/aws/provider/awsProvider.js
  lib/plugins/aws/provider/awsProvider.test.js
  package.json
Labels: bug, cat/providers, pr/in-review

#6435 Add note for supported version of existing bucket feature
  docs/providers/aws/events/s3.md
Labels: cat/event-src, docs, pr/in-review

#6440 PLAT-1390 - check for cached creds in interactive setupAws
  lib/plugins/interactiveCli/setupAws.js
Labels: cat/enterprise, enhancement, pr/in-review

#6447 Only check creds on deploy
  CHANGELOG.md
  lib/plugins/aws/lib/validate.js
  lib/plugins/aws/lib/validate.test.js
  package.json
Labels: bug, cat/providers, pr/in-review

#6446 Remove hard coded partition when validating subscription filters
  lib/plugins/aws/deploy/lib/checkForChanges.js
  lib/plugins/aws/deploy/lib/checkForChanges.test.js
Labels: bug, cat/lambda, pr/in-review

#6445 Fix cross-account/cross-regions SNS subscriptions to topics with the same name
  docs/providers/aws/events/sns.md
  lib/plugins/aws/package/compile/events/sns/index.js
  lib/plugins/aws/package/compile/events/sns/index.test.js
Labels: bug, cat/event-src, pr/in-review

#6397 Add EventBridge event source
  .gitignore
  docs/providers/aws/README.md
  docs/providers/aws/events/cognito-user-pool.md
  docs/providers/aws/events/event-bridge.md
  lib/plugins/Plugins.json
  lib/plugins/aws/customResources/index.js
  lib/plugins/aws/customResources/index.test.js
  lib/plugins/aws/customResources/resources/eventBridge/handler.js
  lib/plugins/aws/customResources/resources/eventBridge/lib/eventBridge.js
  lib/plugins/aws/customResources/resources/eventBridge/lib/permissions.js
  lib/plugins/aws/customResources/resources/eventBridge/lib/utils.js
  lib/plugins/aws/customResources/resources/package.json
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/lib/naming.test.js
  lib/plugins/aws/package/compile/events/eventBridge/index.js
  lib/plugins/aws/package/compile/events/eventBridge/index.test.js
  lib/utils/fs/getTmpDirPath.js
  lib/utils/fs/getTmpDirPath.test.js
  tests/integration-all/event-bridge/service/core.js
  tests/integration-all/event-bridge/service/serverless.yml
  tests/integration-all/event-bridge/tests.js
  tests/utils/eventBridge/index.js
Labels: cat/event-src, feature, pr/in-review

#6466 Update invoke-local.md documentation
  docs/providers/aws/cli-reference/invoke-local.md
Labels: cat/local-dev, docs, enhancement, pr/in-review

#6456 Existing S3 bucket fixes
  lib/plugins/aws/customResources/resources/s3/lib/bucket.js
  lib/plugins/aws/customResources/resources/utils.test.js
  lib/plugins/aws/package/compile/events/s3/index.js
  lib/plugins/aws/package/compile/events/s3/index.test.js
  tests/integration-all/s3/service/serverless.yml
  tests/integration-all/s3/tests.js
Labels: bug, cat/event-src, pr/in-review

#6476 Releasing v1.49.0
  CHANGELOG.md
  package.json
Labels: pr/in-review

#6478 Render event information in aws-ruby handler template
  lib/plugins/create/templates/aws-ruby/handler.rb
Labels: cat/templates, enhancement, pr/in-review

#6473 Adding ap-south-1 to supported region list
  docs/dashboard/README.md
Labels: cat/enterprise, docs, pr/in-review
