Repository serverless/serverless, pull requests merged in 2019-03, with the labels that each got.

#5884 Add Geniusee to Consultants list
  README.md
Labels: pr/in-review

#5883 Print customized function names correctly in sls info output
  lib/plugins/aws/info/getStackInfo.js
  lib/plugins/aws/info/getStackInfo.test.js
Labels: pr/in-review

#5894 Update getting started page
  docs/getting-started.md
Labels: pr/in-review

#5880 Fix bug when using websocket events with functions with custom roles
  lib/plugins/aws/package/compile/events/websockets/lib/api.js
  lib/plugins/aws/package/compile/events/websockets/lib/api.test.js
Labels: pr/in-review

#5885 Fix CloudFormation template normalization
  lib/plugins/aws/lib/normalizeFiles.js
  lib/plugins/aws/lib/normalizeFiles.test.js
Labels: pr/in-review

#5860 Add AWS x-ray support for Lambda
  docs/providers/aws/guide/functions.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/compile/functions/index.js
  lib/plugins/aws/package/compile/functions/index.test.js
Labels: pr/in-review

#5351 Allow Fn::Join in SQS arn builder
  docs/providers/aws/events/sqs.md
  lib/plugins/aws/package/compile/events/sqs/index.js
  lib/plugins/aws/package/compile/events/sqs/index.test.js
Labels: pr/in-review

#5509 Support API Gateway stage deployment description
  docs/providers/aws/events/apigateway.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/compile/events/apiGateway/lib/deployment.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/deployment.test.js
  lib/plugins/aws/provider/awsProvider.js
Labels: pr/in-review

#5743 Allow individual packaging with TypeScript source maps
  lib/plugins/create/templates/aws-alexa-typescript/handler.ts
  lib/plugins/create/templates/aws-alexa-typescript/package.json
  lib/plugins/create/templates/aws-alexa-typescript/source-map-install.js
  lib/plugins/create/templates/aws-alexa-typescript/webpack.config.js
  lib/plugins/create/templates/aws-nodejs-typescript/handler.ts
  lib/plugins/create/templates/aws-nodejs-typescript/package.json
  lib/plugins/create/templates/aws-nodejs-typescript/source-map-install.js
  lib/plugins/create/templates/aws-nodejs-typescript/webpack.config.js
Labels: pr/in-review

#5889 Cleanup Serverless.js file from unused code
  lib/Serverless.js
Labels: pr/in-progress

#5909 Add links to the respective core concepts
  docs/providers/aws/guide/resources.md
Labels: docs

#5911 Add type configuration to aws serverless.yml guide for authorizer
  docs/providers/aws/guide/serverless.yml.md
Labels: pr/in-review

#5912 Support for Cloudwatch Event InputTransformer
  docs/providers/aws/events/cloudwatch-event.md
  docs/providers/aws/events/schedule.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/compile/events/cloudWatchEvent/index.js
  lib/plugins/aws/package/compile/events/cloudWatchEvent/index.test.js
  lib/plugins/aws/package/compile/events/schedule/index.js
  lib/plugins/aws/package/compile/events/schedule/index.test.js
Labels: pr/in-review

#5863 Invoke local docker
  docs/providers/aws/cli-reference/invoke-local.md
  lib/plugins/aws/invokeLocal/index.js
  lib/plugins/aws/invokeLocal/index.test.js
  lib/plugins/aws/package/compile/functions/index.js
  lib/plugins/invoke/invoke.js
  package-lock.json
  package.json
Labels: pr/in-review

#5899 [SLS-6891] fix regression with golang check on windows
  lib/plugins/package/lib/packageService.js
  lib/plugins/package/lib/packageService.test.js
Labels: pr/in-review

#5297 Fixed #4188 - Package generating incorrect package artifact path in serverless-state.json
  lib/plugins/aws/package/lib/saveServiceState.js
  lib/plugins/aws/package/lib/saveServiceState.test.js
Labels: pr/in-review

#5924 Releasing v1.39.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: pr/in-review

#5922 Fixed typo "disonnect"
  docs/providers/aws/events/websocket.md
Labels: pr/in-review

#5936 Revert "Fixed #4188 - Package generating incorrect package artifact path in serverless-state.json"
  lib/plugins/aws/package/lib/saveServiceState.js
  lib/plugins/aws/package/lib/saveServiceState.test.js
Labels: pr/in-review

#5937 Align error logging
  lib/classes/Error.js
Labels: pr/in-review

#5943 Fixing minor typo
  docs/providers/aws/cli-reference/invoke-local.md
Labels: pr/in-review

#5944 Documentation tweak around shared authorizers
  docs/providers/aws/events/apigateway.md
Labels: pr/in-review

#5898 Support for asynchronous lambda invocation with integration type AWS
  docs/providers/aws/events/apigateway.md
  lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/validate.test.js
Labels: cat/api-gw, enhancement, pr/in-review

#5948 Add unit tests for getLocalAccessKey function
  lib/classes/Utils.test.js
Labels: pr/in-review

#5949 Document changes from #4951
  docs/providers/aws/guide/services.md
Labels: pr/in-review

#5335 Fixes #5188 "Failed to fetch the event types list due the error: API …
  lib/classes/Utils.js
Labels: pr/in-review

#5640 Allow * in variable string literal defaults
  lib/classes/Service.js
  lib/classes/Service.test.js
  lib/classes/Variables.test.js
  lib/plugins/print/print.js
  lib/plugins/print/print.test.js
Labels: pr/in-review

#5926 Add Serverless instanceId concept
  docs/providers/aws/guide/resources.md
  docs/providers/aws/guide/variables.md
  lib/Serverless.js
  lib/Serverless.test.js
  lib/classes/Variables.js
  lib/classes/Variables.test.js
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/lib/naming.test.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/deployment.js
  lib/plugins/aws/package/compile/events/websockets/lib/deployment.js
  lib/plugins/aws/package/compile/events/websockets/lib/stage.test.js
Labels: pr/in-review

#5957 Doc: Include that APIGateway status code of async events
  docs/providers/aws/events/apigateway.md
Labels: pr/in-review

#5968 Update npm dependencies
  package-lock.json
  package.json
Labels: pr/in-review

#5963 Version 1.40.0 release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: pr/in-progress

#5964 Add error message when provider does not exist
  lib/plugins/deploy/deploy.js
  lib/plugins/deploy/deploy.test.js
Labels: pr/in-review

#5973 The code for removing comments is easy to read
  bin/serverless
Labels: pr/in-review

#5971 Added rust template for Cloudflare WASM
  docs/providers/cloudflare/cli-reference/create.md
  docs/providers/cloudflare/guide/services.md
  lib/plugins/create/create.js
  lib/plugins/create/create.test.js
  lib/plugins/create/templates/cloudflare-workers-rust/.gitignore
  lib/plugins/create/templates/cloudflare-workers-rust/helloWorld.js
  lib/plugins/create/templates/cloudflare-workers-rust/package.json
  lib/plugins/create/templates/cloudflare-workers-rust/rust-wasm/Cargo.toml
  lib/plugins/create/templates/cloudflare-workers-rust/rust-wasm/src/lib.rs
  lib/plugins/create/templates/cloudflare-workers-rust/serverless.yml
  lib/plugins/create/templates/cloudflare-workers-rust/webpack.config.js
Labels: pr/in-review
