Repository serverless/serverless, pull requests merged in 2019-12, with the labels that each got.

#6981 Provide backoff for retryable aws requests and the option to adjust the cf status check interval via an environment variable
  docs/providers/aws/cli-reference/deploy.md
  lib/plugins/aws/lib/monitorStack.js
  lib/plugins/aws/provider/awsProvider.js
Labels: cat/deployment, enhancement, pr/in-review

#6988 Add page for best practices on CI/CD
  docs/dashboard/cicd/best-practices.md
Labels: cat/dashboard, docs, pr/in-progress

#7032 Optimize custom resources generation
  lib/plugins/aws/customResources/generateZip.js
  lib/plugins/aws/customResources/index.js
  lib/plugins/aws/customResources/index.test.js
  lib/plugins/aws/deploy/lib/uploadArtifacts.js
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/lib/naming.test.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/stage/index.test.js
  lib/plugins/aws/package/compile/events/websockets/lib/stage.test.js
Labels: bug, cat/packaging, pr/in-review

#7033 Update API GW stage settings only when explicitly set
  lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js
Labels: bug, cat/api-gw, pr/in-review

#7034 Do not apply APIGW wide settings on externally referenced APIGW
  lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js
Labels: bug, cat/api-gw, pr/in-review

#6992 Enable Content Trust checking when pulling lambci/lambda images
  lib/plugins/aws/invokeLocal/index.js
  lib/plugins/aws/invokeLocal/index.test.js
Labels: cat/local-dev, enhancement, pr/in-review

#7039 Fix resolution of user configured APIGW
  lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js
Labels: bug, cat/api-gw, pr/in-review

#7035 Add option to change log level for websocket logs
  docs/providers/aws/events/websocket.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/compile/events/websockets/lib/stage.js
  lib/plugins/aws/package/compile/events/websockets/lib/stage.test.js
Labels: cat/api-gw, enhancement, pr/in-review

#7043 Support lambda provisioned concurrency
  docs/providers/aws/guide/functions.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/compile/functions/index.js
  lib/plugins/aws/package/compile/functions/index.test.js
Labels: cat/lambda, enhancement, pr/in-review

#7044 Fix AWS creds handling
  lib/plugins/aws/invokeLocal/index.js
  lib/plugins/aws/invokeLocal/index.test.js
Labels: bug, cat/dx, pr/in-review

#7045 Fix lambda provisioned concurrency setup
  lib/plugins/aws/package/compile/functions/index.js
  lib/plugins/aws/package/compile/functions/index.test.js
Labels: bug

#7046 Release v1.59.0
  CHANGELOG.md
  package.json
Labels: pr/in-review

#7002 Resource policy
  lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.test.js
Labels: bug, cat/api-gw, pr/in-review

#7048 Revert "Resource policy" fix
  lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.test.js
Labels: bug

#7040 Adding configurable MaximumRetryAttempts for stream(Dynamo& Kinesis) event sourcing
  docs/providers/aws/events/streams.md
  lib/plugins/aws/package/compile/events/stream/index.js
  lib/plugins/aws/package/compile/events/stream/index.test.js
Labels: cat/event-src, enhancement, pr/in-review

#6977 New flag to bypass validation when deploying from ec2 machine
  lib/plugins/aws/lib/validate.js
  lib/plugins/aws/lib/validate.test.js
Labels: bug, cat/dx, pr/in-review

#7068 Add docs on Python support in CI/CD
  docs/dashboard/cicd/README.md
Labels: cat/dashboard, docs

#7072 Update aws-kotlin-jvm-gradle template to Gradle 6 and Java 11
  lib/plugins/create/templates/aws-kotlin-jvm-gradle/README.md
  lib/plugins/create/templates/aws-kotlin-jvm-gradle/build.gradle
  lib/plugins/create/templates/aws-kotlin-jvm-gradle/gradle/wrapper/gradle-wrapper.properties
  lib/plugins/create/templates/aws-kotlin-jvm-gradle/serverless.yml
Labels: cat/templates, enhancement, pr/in-review

#7079 CI: Fix npm update related issues
  .travis.yml
Labels: enhancement, pr/in-review

#7083 Allow use of Ref, Fn::GetAtt and Fn::ImportValue in awsKmsKeyArn
  lib/plugins/aws/package/compile/functions/index.js
  lib/plugins/aws/package/compile/functions/index.test.js
Labels: enhancement

#7071 Plugins - now allow falsy default values.
  lib/classes/PluginManager.js
  lib/classes/PluginManager.test.js
Labels: bug, cat/plugin, pr/in-review

#7089 CI: Run integration tests concurrently
  package.json
Labels: cat/tests, enhancement, pr/in-review

#7091 Implement In-memory cache for node dev dependencies.
  lib/plugins/package/lib/zipService.js
Labels: cat/dx, enhancement, pr/in-progress

#7104 Fix AWS partition reference in APIGW CloudWatch role setup
  lib/plugins/aws/package/compile/events/lib/ensureApiGatewayCloudWatchRole.js
Labels: bug, cat/api-gw, pr/in-review

#7092 Docs - updates per new dashboard CI/CD features
  docs/dashboard/cicd/README.md
  docs/dashboard/cicd/best-practices.md
  docs/dashboard/cicd/branch-deployments.md
  docs/dashboard/cicd/custom-scripts.md
  docs/dashboard/cicd/faq.md
  docs/dashboard/cicd/mono-repo.md
  docs/dashboard/cicd/preview-deployments.md
  docs/dashboard/cicd/private-packages.md
  docs/dashboard/cicd/running-in-your-own-cicd.md
  docs/dashboard/cicd/running-tests.md
  docs/dashboard/cicd/troubleshooting.md
Labels: cat/dashboard, docs, pr/in-progress

#7119 Release v1.60.1
  CHANGELOG.md
  package.json
Labels: pr/in-review

#7122 Fix multiple custom resource generation
  lib/plugins/aws/customResources/index.js
Labels: bug

#7124 Improve binary installer documentation
  docs/getting-started.md
Labels: docs

#7120 Fix access rules for CloudWatch logs creation
  lib/plugins/aws/customResources/index.js
  lib/plugins/aws/customResources/index.test.js
  lib/plugins/aws/package/lib/iam-role-lambda-execution-template.json
  lib/plugins/aws/package/lib/mergeIamTemplates.test.js
Labels: bug

#7129 Add README_CN.md
  README.md
  README_CN.md
Labels: docs

#7138 Resource policy
  lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.test.js
Labels: bug, cat/api-gw
