Repository serverless/serverless, pull requests merged in 2019-09, with the labels that each got.

#6611 Fix API Gateway name not being resolved API Gateway Resource not in main stack
  lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js
Labels: bug, cat/api-gw, pr/in-review

#6608 Support optional CloudWatch logs writing for custom resource lambdas
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/customResources/index.js
  lib/plugins/aws/customResources/index.test.js
Labels: cat/dx, enhancement, pr/in-review

#6616 Ensure inquirer's chalk override works through symlinks
  lib/plugins/interactiveCli/inquirer.js
  package.json
Labels: bug, cat/dx, pr/in-review

#6615 Fixes aws partition name in apigateway resourceArn to support GovCloud
  lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js
Labels: bug, cat/api-gw, pr/in-review

#6618 Do not retry on AWS 403 errors
  lib/plugins/aws/provider/awsProvider.js
  lib/plugins/aws/provider/awsProvider.test.js
Labels: bug, cat/dx, pr/in-review

#6606 Fix overriding package settings after packaging function
  lib/plugins/package/lib/packageService.js
  lib/plugins/package/lib/packageService.test.js
  tests/integration-package/fixtures/individually-function/handler.js
  tests/integration-package/fixtures/individually-function/handler2.js
  tests/integration-package/fixtures/individually-function/serverless.yml
  tests/integration-package/lambda-files.tests.js
Labels: bug, cat/packaging, pr/in-review

#6604 Download templates from a Bitbucket Server
  docs/providers/aws/cli-reference/install.md
  docs/providers/azure/cli-reference/install.md
  docs/providers/fn/cli-reference/create.md
  docs/providers/google/cli-reference/install.md
  docs/providers/openwhisk/cli-reference/install.md
  lib/utils/downloadTemplateFromRepo.js
  lib/utils/downloadTemplateFromRepo.test.js
Labels: cat/dx, feature, pr/in-review

#6622 Update Readme to replace SC5.io with nordcloud.com
  README.md
Labels: cat/refactoring, docs, pr/in-review

#6566 Add plugin hooks to define config variable getters
  docs/providers/aws/guide/plugins.md
  lib/Serverless.js
  lib/Serverless.test.js
  lib/classes/PluginManager.js
  lib/classes/PluginManager.test.js
  lib/classes/Variables.js
  lib/classes/Variables.test.js
Labels: cat/plugin, cat/variable, enhancement

#6624 Allow for tail on GetAtt parsing
  lib/plugins/aws/lib/cloudformationSchema.js
  lib/utils/fs/parse.test.js
Labels: bug, cat/dx, pr/in-review

#6631 Resolve empty config object for an empty config file
  lib/utils/getServerlessConfigFile.js
  lib/utils/getServerlessConfigFile.test.js
Labels: bug, cat/dx, pr/in-review

#6625 Remove enterprise from upgrade notes
  lib/classes/PluginManager.js
Labels: cat/dashboard, enhancement, pr/in-review

#6512 Add support for Lambda@Edge
  docs/providers/aws/README.md
  docs/providers/aws/events/cloudfront.md
  lib/plugins/Plugins.json
  lib/plugins/aws/info/display.js
  lib/plugins/aws/info/display.test.js
  lib/plugins/aws/info/getStackInfo.js
  lib/plugins/aws/info/getStackInfo.test.js
  lib/plugins/aws/lib/monitorStack.js
  lib/plugins/aws/lib/monitorStack.test.js
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/lib/naming.test.js
  lib/plugins/aws/lib/updateStack.test.js
  lib/plugins/aws/package/compile/events/cloudFront/index.js
  lib/plugins/aws/package/compile/events/cloudFront/index.test.js
  lib/plugins/aws/package/compile/functions/index.js
  lib/plugins/aws/package/compile/functions/index.test.js
  lib/plugins/aws/provider/awsProvider.test.js
  lib/plugins/aws/remove/index.test.js
Labels: cat/event-src, feature, pr/in-review

#6635 Tests for interactive CLI
  lib/plugins/aws/configCredentials/awsConfigCredentials.test.js
  lib/plugins/aws/invoke/index.test.js
  lib/plugins/aws/invokeLocal/index.test.js
  lib/plugins/aws/utils/credentials.test.js
  lib/plugins/interactiveCli/initializeService.js
  lib/plugins/interactiveCli/initializeService.test.js
  lib/plugins/interactiveCli/setupAws.js
  lib/plugins/interactiveCli/setupAws.test.js
  lib/plugins/interactiveCli/test/configure-inquirer-stub.js
  lib/plugins/interactiveCli/test/fixtures/some-aws-service/serverless.yml
  lib/plugins/interactiveCli/test/fixtures/some-other-service/serverless.yml
  lib/plugins/interactiveCli/utils.js
  package.json
  tests/utils/run-serverless.js
Labels: pr/in-review, tests

#6645 Support functions without events in CloudFront remove logging
  lib/plugins/aws/package/compile/events/cloudFront/index.js
  lib/plugins/aws/package/compile/events/cloudFront/index.test.js
  package.json
Labels: bug, cat/event-src, pr/in-review

#6642 Add support for Condition and DependsOn
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/compile/functions/index.js
  lib/plugins/aws/package/compile/functions/index.test.js
Labels: cat/lambda, feature, pr/in-review

#6646 Improve plugin loading error reporting
  lib/classes/PluginManager.js
  lib/classes/PluginManager.test.js
Labels: bug, cat/dx

#6652 Use hooks to log Lambda@Edge removal reminder
  lib/plugins/aws/package/compile/events/cloudFront/index.js
  lib/plugins/aws/package/compile/events/cloudFront/index.test.js
Labels: bug, cat/event-src, pr/in-review

#6653 Quickfix "too many open files" issue on Windows
  bin/serverless.js
  lib/plugins/package/lib/zipService.js
  lib/plugins/package/lib/zipService.test.js
Labels: bug, cat/packaging, os/windows, pr/in-review

#6654 Bump sfe plugin!
  package.json
Labels: cat/dashboard, enhancement, pr/in-review

#6663 Update insights.md
  docs/dashboard/insights.md
Labels: docs

#6665 Release v1.52.0
  CHANGELOG.md
  RELEASE_CHECKLIST.md
  package.json
Labels: pr/in-review

#6658 Respect logRetentionInDays in log group for websocket
  lib/plugins/aws/package/compile/events/websockets/lib/stage.js
  lib/plugins/aws/package/compile/events/websockets/lib/stage.test.js
Labels: cat/api-gw, enhancement, pr/in-review

#6678 [Docs] Added clarification on specifying SNS ARN
  docs/providers/aws/events/sns.md
Labels: cat/event-src, docs, pr/in-review

#6689 Fix regular expression escaping in aws plugin.
  lib/plugins/aws/package/compile/functions/index.js
  lib/plugins/aws/package/compile/functions/index.test.js
Labels: bug

#6376 Update Azure quickstart and Azure Node.js project README
  docs/providers/azure/guide/quick-start.md
  lib/plugins/create/templates/azure-nodejs/README.md
Labels: cat/providers, docs, pr/in-review

#6380 Update Azure CLI Reference Docs
  docs/providers/azure/cli-reference/create.md
  docs/providers/azure/cli-reference/deploy-function.md
  docs/providers/azure/cli-reference/deploy-list.md
  docs/providers/azure/cli-reference/deploy.md
  docs/providers/azure/cli-reference/install.md
  docs/providers/azure/cli-reference/invoke.md
  docs/providers/azure/cli-reference/login.md
  docs/providers/azure/cli-reference/logs.md
  docs/providers/azure/cli-reference/plugin-install.md
  docs/providers/azure/cli-reference/plugin-list.md
  docs/providers/azure/cli-reference/plugin-search.md
  docs/providers/azure/cli-reference/plugin-uninstall.md
  docs/providers/azure/cli-reference/print.md
  docs/providers/azure/cli-reference/remove.md
  docs/providers/azure/cli-reference/rollback.md
Labels: cat/providers, docs, pr/in-review

#6664 Docs: update and clean up hello world app documentation
  docs/providers/azure/events/blobstorage.md
  docs/providers/azure/events/eventhubs.md
  docs/providers/azure/events/http.md
  docs/providers/azure/events/other.md
  docs/providers/azure/events/queuestorage.md
  docs/providers/azure/events/servicebus.md
  docs/providers/azure/events/timer.md
  docs/providers/azure/examples/README.md
  docs/providers/azure/examples/hello-world/README.md
  docs/providers/azure/examples/hello-world/node/README.md
  docs/providers/azure/examples/hello-world/node/handler.js
  docs/providers/azure/examples/hello-world/node/package.json
  docs/providers/azure/examples/hello-world/node/serverless.yml
  docs/providers/azure/guide/credentials.md
Labels: cat/providers, docs, pr/in-review

#6403 Update Azure provider guide docs
  docs/providers/azure/README.md
  docs/providers/azure/guide/README.md
  docs/providers/azure/guide/credentials.md
  docs/providers/azure/guide/deploying.md
  docs/providers/azure/guide/events.md
  docs/providers/azure/guide/function-apps.md
  docs/providers/azure/guide/functions.md
  docs/providers/azure/guide/installation.md
  docs/providers/azure/guide/intro.md
  docs/providers/azure/guide/packaging.md
  docs/providers/azure/guide/plugins.md
  docs/providers/azure/guide/services.md
  docs/providers/azure/guide/testing.md
  docs/providers/azure/guide/variables.md
  docs/providers/azure/guide/workflow.md
Labels: cat/providers, docs, pr/in-review

#6626 Update azure nodejs template
  lib/plugins/create/create.test.js
  lib/plugins/create/templates/azure-nodejs/README.md
  lib/plugins/create/templates/azure-nodejs/package.json
  lib/plugins/create/templates/azure-nodejs/serverless.yml
  lib/plugins/create/templates/azure-nodejs/src/handlers/goodbye.js
  lib/plugins/create/templates/azure-nodejs/src/handlers/hello.js
Labels: cat/templates, enhancement, pr/in-review

#6660 Move common test utils to @serverless/test
  lib/classes/Variables.test.js
  lib/plugins/aws/invokeLocal/index.test.js
  lib/plugins/interactiveCli/initializeService.test.js
  lib/plugins/interactiveCli/setupAws.test.js
  lib/plugins/interactiveCli/test/configure-inquirer-stub.js
  lib/utils/fs/copyDirContentsSync.test.js
  lib/utils/fs/walkDirSync.test.js
  package.json
  scripts/test-isolated.js
  tests/mocha-reporter.js
  tests/utils/fs/index.js
  tests/utils/misc/index.js
  tests/utils/run-serverless.js
Labels: cat/dashboard, tests

#6696 Add testing docs
  docs/dashboard/testing.md
Labels: cat/dashboard, docs, pr/in-review

#6687 Move where initialize lifecycle hook is called
  lib/classes/PluginManager.js
  lib/classes/PluginManager.test.js
Labels: cat/variable, enhancement, pr/in-progress

#4922 Add aliyun provider
  docker-compose.yml
  docs/README.md
  docs/getting-started.md
  docs/providers/README.md
  docs/providers/aliyun/README.md
  docs/providers/aliyun/cli-reference/README.md
  docs/providers/aliyun/cli-reference/create.md
  docs/providers/aliyun/cli-reference/deploy.md
  docs/providers/aliyun/cli-reference/info.md
  docs/providers/aliyun/cli-reference/install.md
  docs/providers/aliyun/cli-reference/invoke.md
  docs/providers/aliyun/cli-reference/login.md
  docs/providers/aliyun/cli-reference/logs.md
  docs/providers/aliyun/cli-reference/package.md
  docs/providers/aliyun/cli-reference/remove.md
  docs/providers/aliyun/events/README.md
  docs/providers/aliyun/events/http.md
  docs/providers/aliyun/events/oss.md
  docs/providers/aliyun/guide/README.md
  docs/providers/aliyun/guide/credentials.md
  docs/providers/aliyun/guide/deploying.md
  docs/providers/aliyun/guide/events.md
  docs/providers/aliyun/guide/functions.md
  docs/providers/aliyun/guide/installation.md
  docs/providers/aliyun/guide/intro.md
  docs/providers/aliyun/guide/packaging.md
  docs/providers/aliyun/guide/plugins.md
  docs/providers/aliyun/guide/quick-start.md
  docs/providers/aliyun/guide/services.md
  docs/providers/aliyun/guide/variables.md
  docs/providers/aliyun/guide/workflow.md
  lib/plugins/create/create.js
  lib/plugins/create/create.test.js
  lib/plugins/create/templates/aliyun-nodejs/gitignore
  lib/plugins/create/templates/aliyun-nodejs/index.js
  lib/plugins/create/templates/aliyun-nodejs/package.json
  lib/plugins/create/templates/aliyun-nodejs/serverless.yml
  tests/templates/test-all-templates
Labels: cat/providers, feature, pr/in-review

#6703 Update homepage in package.json to point to the docs
  package.json
Labels: cat/dx, enhancement, pr/in-review

#6712 Fix typo
  docs/providers/aws/events/cloudfront.md
Labels: docs

#6708 Truncated aliyun events menuText
  docs/providers/aliyun/events/README.md
Labels: cat/providers, docs, pr/in-review

#6702 Added Components Versions
  lib/classes/CLI.js
  lib/classes/CLI.test.js
  lib/classes/Error.js
  package.json
Labels: cat/dx, enhancement, pr/in-review

#6707 Add commas when specifying Google roles for legibility
  docs/providers/google/guide/credentials.md
Labels: cat/providers, docs, pr/in-review

#6713 Add Theodo to the consultants section of the README
  README.md
Labels: docs, pr/in-review

#6686 Remove incorrect AWS Access Role test instruction
  docs/dashboard/access-roles.md
Labels: cat/dashboard, docs, pr/in-review

#6711 Feat: add qualifier option to invoke command
  docs/providers/aws/cli-reference/invoke.md
  lib/plugins/aws/invoke/index.js
  lib/plugins/aws/invoke/index.test.js
  lib/plugins/invoke/invoke.js
Labels: cat/lambda, feature, pr/in-review

#6714 Upgrade @serverless/test to v2
  lib/plugins/interactiveCli/initializeService.test.js
  lib/plugins/interactiveCli/setupAws.test.js
  package.json
Labels: cat/dx, pr/in-review, tests

#6717 Lock graceful-fs at 4.2.1
  package.json
Labels: bug, cat/dx, pr/in-review

#6718 Release v1.52.2
  CHANGELOG.md
  package.json
Labels: pr/in-review

#6719 Allow plugins not in registry to be installed
  lib/plugins/plugin/install/install.js
  lib/plugins/plugin/install/install.test.js
  lib/plugins/plugin/lib/utils.js
  lib/plugins/plugin/lib/utils.test.js
  lib/plugins/plugin/uninstall/uninstall.js
  lib/plugins/plugin/uninstall/uninstall.test.js
Labels: cat/plugin, enhancement, pr/in-review

#6639 PLAT-1599 Modularize interactive AWS setup
  lib/plugins/interactiveCli/index.js
  lib/plugins/interactiveCli/setupAws.js
Labels: cat/dashboard, enhancement

#6721 documented url+zip deploy strategy for serverless-kubeless
  docs/providers/kubeless/guide/deploying.md
Labels: cat/providers, docs, pr/in-review

#6728 Improve message for Windows users in AWS credentials setup
  lib/plugins/interactiveCli/setupAws.js
Labels: cat/dx, enhancement

#6742 Fix custom resources install
  lib/plugins/aws/customResources/index.js
Labels: bug, cat/packaging, os/windows, pr/in-review

#6741 Add support for MaximumBatchingWindowInSeconds property on stream events
  docs/providers/aws/events/streams.md
  lib/plugins/aws/package/compile/events/stream/index.js
  lib/plugins/aws/package/compile/events/stream/index.test.js
Labels: cat/event-src, feature, pr/in-review

#6744 Alibaba Docs Update
  docs/providers/aliyun/guide/credentials.md
Labels: cat/providers, docs, pr/in-review

#6748 Update Jackson versions
  lib/plugins/aws/invokeLocal/java/pom.xml
  lib/plugins/create/templates/aws-java-gradle/build.gradle
  lib/plugins/create/templates/aws-java-maven/pom.xml
  lib/plugins/create/templates/aws-kotlin-jvm-gradle/build.gradle
  lib/plugins/create/templates/aws-kotlin-jvm-maven/pom.xml
Labels: cat/security, enhancement, pr/in-review

#6749 Improvements to stats handling
  bin/serverless.js
  lib/utils/tracking.js
  lib/utils/tracking.test.js
  package.json
Labels: enhancement, pr/in-review

#6746 Fixing typos in variable names
  lib/plugins/aws/customResources/resources/apiGatewayCloudWatchRole/handler.js
  lib/plugins/aws/customResources/resources/cognitoUserPool/handler.js
  lib/plugins/aws/customResources/resources/eventBridge/handler.js
  lib/plugins/aws/customResources/resources/s3/handler.js
  lib/plugins/aws/lib/naming.test.js
Labels: cat/refactoring, enhancement, pr/in-review

#6753 Simplify GitHub Issue / PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cat/dx, docs, needs feedback, pr/in-review

#6757 Capture and span docs
  docs/dashboard/monitoring/README.md
Labels: docs

#6743 Automate keeping the sfe-next branch upto date
  .github/workflows/update-sfe-next.yml
  scripts/update-sfe-dep.js
Labels: cat/dashboard, feature, pr/in-review

#6754 Update dependencies in aws-scala-sbt template
  docker-compose.yml
  lib/plugins/create/templates/aws-scala-sbt/build.sbt
  lib/plugins/create/templates/aws-scala-sbt/project/build.properties
  lib/plugins/create/templates/aws-scala-sbt/project/plugins.sbt
Labels: cat/templates, enhancement, pr/in-review

#6763 PR Template --> Hide useful scripts in expandable section
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cat/dx, docs, pr/in-review

#6758 Doc refactoring and new features
  docs/dashboard/README.md
  docs/dashboard/cicd.md
  docs/dashboard/insights.md
  docs/dashboard/monitoring/README.md
  docs/dashboard/monitoring/alerts.md
  docs/dashboard/monitoring/metrics.md
  docs/dashboard/monitoring/notifications.md
  docs/dashboard/profiles.md
  docs/dashboard/safeguards/README.md
  docs/dashboard/safeguards/available.md
  docs/dashboard/safeguards/custom.md
  docs/dashboard/secrets.md
  docs/getting-started.md
Labels: cat/dashboard, docs, pr/in-review
