Repository serverless/serverless, pull requests merged in 2020-06, with the labels that each got.

#7755 add serverless.ts support
  lib/classes/Utils.js
  lib/classes/Utils.test.js
  lib/utils/getServerlessConfigFile.js
  lib/utils/getServerlessConfigFile.test.js
  tests/fixtures/serverlessTs/serverless.ts
Labels: enhancement

#7799 Make it easier to use a CognitoUserPool authorizer when the pool is configured in the same service.
  docs/providers/aws/events/apigateway.md
  lib/plugins/aws/package/compile/events/apiGateway/lib/authorizers.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/authorizers.test.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/method/authorization.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/validate.test.js
Labels: cat/aws-event-api-gateway, enhancement

#7789 feat(httpApi): external authorizer
  docs/providers/aws/events/http-api.md
  lib/plugins/aws/package/compile/events/httpApi/index.js
  lib/plugins/aws/package/compile/events/httpApi/index.test.js
Labels: cat/aws-event-http-api, enhancement

#7782 Replace lodash _.find with native Array.find
  lib/classes/Utils.js
  lib/plugins/aws/deploy/lib/createStack.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/resources.js
  lib/plugins/aws/package/compile/events/sns/index.js
  tests/integration-all/api-gateway/tests.js
  tests/integration-all/http-api/tests.js
  tests/integration-all/websocket/tests.js
Labels: cat/dependency, refactor

#7804 Fix AWS API Gateway key names resolution
  lib/plugins/aws/info/getApiKeyValues.js
Labels: bug, cat/aws-event-api-gateway

#7805 Replace lodash _.join with native array.join
  lib/classes/PluginManager.js
  lib/plugins/aws/provider/awsProvider.js
  lib/utils/log/fileLog.js
Labels: cat/dependency, refactor

#7808 refactor: Replace _.toUpper(string) with string.toUpperCase
  lib/classes/Utils.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration.js
Labels: cat/dependency, refactor

#7809 refactor: Replace `_.isNil(value)` with `value == null`
  lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js
  lib/plugins/aws/provider/awsProvider.js
  lib/plugins/plugin/install/install.js
Labels: cat/dependency, refactor

#7810 refactor: Replace `_.isFunction(value)` with `typeof value === 'function'`
  lib/classes/PluginManager.js
  lib/classes/Variables.js
Labels: cat/dependency, refactor

#7806 add remaining '.ts' checks
  lib/plugins/plugin/install/install.js
  lib/plugins/plugin/install/install.test.js
  lib/plugins/plugin/uninstall/uninstall.js
  lib/plugins/plugin/uninstall/uninstall.test.js
Labels: bug

#7813 Replace lodash unset with native delete objectProp
  lib/plugins/plugin/uninstall/uninstall.js
  lib/utils/yamlAstParser.js
Labels: cat/dependency, refactor

#7816 Replace lodash _.first with native array[0]
  lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.test.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlanKeys.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlanKeys.test.js
Labels: cat/dependency, refactor

#7817 Replace lodash _.head with array[0]
  lib/utils/yamlAstParser.js
Labels: cat/dependency, refactor

#7818 Replace lodash _.includes with native includes
  lib/classes/PluginManager.js
  lib/plugins/aws/invokeLocal/index.js
  lib/plugins/aws/lib/cloudformationSchema.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/hack/disassociateUsagePlan.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlanKeys.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
  lib/plugins/aws/package/compile/events/cognitoUserPool/index.js
  lib/plugins/aws/package/compile/functions/index.js
  lib/plugins/aws/package/lib/mergeIamTemplates.js
  lib/plugins/aws/utils/findReferences.js
Labels: cat/dependency, refactor

#7825 Replace _.indexOf with native includes
  lib/plugins/aws/package/compile/events/cloudWatchLog/index.js
Labels: cat/dependency, refactor

#7820 Replace _.split with string.split
  lib/classes/PluginManager.js
  lib/plugins/aws/invokeLocal/index.js
  lib/plugins/aws/invokeLocal/invoke.rb
  lib/plugins/aws/package/lib/saveServiceState.js
  lib/plugins/aws/provider/awsProvider.js
  lib/plugins/invoke/invoke.js
  lib/plugins/package/lib/zipService.js
  lib/plugins/plugin/install/install.js
  lib/plugins/plugin/lib/utils.js
  lib/plugins/plugin/uninstall/uninstall.js
Labels: cat/dependency, refactor

#7831 refactor: Replace `_.takeRight` with `array.slice`
  lib/plugins/aws/deploy/lib/cleanupS3Bucket.js
Labels: cat/dependency, refactor

#7832 Revert "Adding in configurable MaximumRetryAttempts for SQS"
  docs/providers/aws/events/sqs.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/compile/events/sqs/index.js
  lib/plugins/aws/package/compile/events/sqs/index.test.js
Labels: bug, cat/aws-event-sqs

#7826 Replace _.isUndefined with native undefined check
  lib/classes/Variables.js
  lib/plugins/aws/invokeLocal/index.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js
  lib/plugins/aws/package/compile/events/stream/index.js
  lib/plugins/aws/package/compile/events/websockets/lib/permissions.js
  lib/plugins/aws/package/lib/mergeIamTemplates.js
  lib/plugins/aws/provider/awsProvider.js
  lib/plugins/print/print.js
  lib/utils/yamlAstParser.js
Labels: cat/dependency, refactor

#7827 Replace _.map with array.map
  lib/classes/PluginManager.js
  lib/classes/Variables.js
  lib/plugins/aws/deploy/lib/uploadArtifacts.js
  lib/plugins/aws/deployList/index.js
  lib/plugins/aws/info/getApiKeyValues.js
  lib/plugins/aws/lib/cloudformationSchema.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
  lib/plugins/aws/package/compile/events/cognitoUserPool/index.js
  lib/plugins/aws/package/compile/events/s3/index.js
  lib/plugins/aws/package/lib/generateCoreTemplate.js
  lib/plugins/aws/utils/findAndGroupDeployments.js
  lib/plugins/package/lib/packageService.js
Labels: cat/dependency, refactor

#7833 feat: Add support for maximumRecordAgeInSeconds property
  docs/providers/aws/events/streams.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/compile/events/stream/index.js
  lib/plugins/aws/package/compile/events/stream/index.test.js
Labels: cat/event-aws-stream, enhancement

#7835 fix: replace `${self:provider.stage}` with `${opt:stage, self:provider.stage, 'dev'}` in docs
  docs/dashboard/cicd/preview-deployments.md
  docs/providers/aws/guide/credentials.md
  docs/providers/aws/guide/functions.md
  docs/providers/aws/guide/layers.md
  docs/providers/aws/guide/serverless.yml.md
  docs/providers/aws/guide/services.md
  docs/providers/aws/guide/variables.md
Labels: documentation

#7839 docs: add link to ruby example
  docs/providers/aws/examples/hello-world/README.md
Labels: documentation

#7841 Replace _.nth with array[index]
  lib/plugins/aws/provider/awsProvider.js
Labels: cat/dependency, refactor

#7843 Replace _.replace with string.replace
  lib/classes/PluginManager.js
Labels: cat/dependency, refactor

#7842 Replace _.repeat with string.repeat
  lib/classes/CLI.js
Labels: cat/dependency, refactor

#7845 AWS API Gateway: Fix handling of usagePlan array
  lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.test.js
Labels: bug, cat/aws-event-api-gateway

#7836 document additional APIGateway logging options
  docs/providers/aws/events/apigateway.md
Labels: cat/aws-event-api-gateway, documentation

#7840 Replace _.min with Math.min
  lib/plugins/aws/deploy/lib/checkForChanges.js
Labels: cat/dependency, refactor

#7849 fix: Remove disableLogs from provider in doc
  docs/providers/aws/guide/serverless.yml.md
Labels: bug, cat/lambda, documentation

#7823 Replace _.sortBy with array.sort
  lib/classes/CLI.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/resources.js
  lib/plugins/package/lib/zipService.js
Labels: cat/dependency, refactor

#7856 Respect logRetentionInDays in log group for httpApi
  lib/plugins/aws/package/compile/events/httpApi/index.js
  lib/plugins/aws/package/compile/events/httpApi/index.test.js
  tests/fixtures/httpApi/serverless.yml
Labels: bug, cat/aws-event-http-api

#7857 AWS Websockets: Fix response resource handling
  lib/plugins/aws/package/compile/events/websockets/lib/deployment.js
Labels: bug, cat/aws-event-websocket

#7858 replaced lodash compact with array.filter(Boolean)
  lib/plugins/package/lib/zipService.js
Labels: cat/dependency, refactor

#7862 Replace lodash chain with native array chain
  lib/plugins/aws/logs/index.js
  lib/plugins/aws/metrics/awsMetrics.js
Labels: cat/dependency, refactor

#7870 Corrected invoke function command
  docs/providers/aliyun/guide/workflow.md
Labels: bug, documentation, provider/aliyun

#7875 Incorrect Documentation for AliYun
  docs/providers/aliyun/guide/functions.md
Labels: documentation, provider/aliyun

#7873 replace _.isEmpty with array.length and Object.keys()
  lib/classes/CLI.js
  lib/classes/PluginManager.js
  lib/classes/Variables.js
  lib/plugins/aws/deploy/lib/extendedValidate.js
  lib/plugins/aws/deployFunction/index.js
  lib/plugins/aws/info/getResourceCount.js
  lib/plugins/aws/lib/updateStack.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/cors.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/stage/index.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlan.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
  lib/plugins/aws/package/lib/generateCoreTemplate.js
  lib/plugins/aws/package/lib/mergeIamTemplates.js
  lib/plugins/aws/utils/findReferences.js
  lib/plugins/package/lib/zipService.js
  lib/plugins/plugin/uninstall/uninstall.js
  lib/utils/getCommandSuggestion.js
  lib/utils/yamlAstParser.js
Labels: cat/dependency, refactor

#7877 Replace _.parseInt with Number
  lib/plugins/aws/package/compile/functions/index.js
Labels: cat/dependency, refactor

#7861 Replaced lodash pullAllWith with Array.filter()
  lib/plugins/aws/deploy/lib/cleanupS3Bucket.js
Labels: cat/dependency, refactor

#7780 feat: add a support for onUnauthenticatedRequest property
  docs/deprecations.md
  docs/providers/aws/events/alb.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/compile/events/alb/index.test.js
  lib/plugins/aws/package/compile/events/alb/lib/validate.js
  lib/plugins/aws/package/compile/events/alb/lib/validate.test.js
Labels: cat/aws-event-alb, deprecation, enhancement

#7883 Replace _.reduce with array.reduce
  lib/classes/CLI.js
  lib/classes/PluginManager.js
  lib/classes/Utils.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/resources.js
  lib/plugins/aws/package/compile/events/cognitoUserPool/index.js
Labels: cat/dependency, refactor

#7880 Remove is boolean
  lib/plugins/aws/package/compile/events/alb/lib/validate.js
  lib/plugins/aws/package/compile/events/alb/lib/validate.test.js
Labels: cat/dependency, refactor

#7887 Override default stackTags with custom stackTags using a case-insensitive merge
  lib/plugins/aws/deploy/lib/createStack.js
  lib/plugins/aws/deploy/lib/createStack.test.js
  lib/plugins/aws/lib/updateStack.js
  lib/plugins/aws/lib/updateStack.test.js
Labels: bug, cat/deployment

#7878 Remove _.isInteger
  lib/plugins/aws/package/compile/events/apiGateway/lib/cors.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.test.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
  lib/plugins/aws/package/compile/functions/index.js
  lib/plugins/aws/package/compile/functions/index.test.js
  lib/plugins/aws/provider/awsProvider.js
Labels: cat/dependency, refactor

#7851 Replace _.concat with array.concat
  lib/plugins/aws/invokeLocal/index.js
  lib/plugins/aws/package/compile/events/alb/lib/validate.js
  lib/plugins/invoke/invoke.js
Labels: cat/dependency, refactor
