Repository serverless/serverless, pull requests merged in 2020-03, with the labels that each got.

#7412 fix(Standalone): Fix bug where chalk is called as a method
  lib/Serverless.js
Labels: bug

#7417 Fix #7103 Add source account to lambda permissions for s3 events
  lib/plugins/aws/customResources/resources/s3/handler.js
  lib/plugins/aws/customResources/resources/s3/lib/permissions.js
  lib/plugins/aws/package/compile/events/s3/index.js
Labels: bug, cat/security

#7386 Improve contributors documentation
  CONTRIBUTING.md
Labels: docs

#7420 AWS HTTP API: Ensure function timeout setting is respected
  docs/providers/aws/events/http-api.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/compile/events/httpApi/index.js
  lib/plugins/aws/package/compile/events/httpApi/index.test.js
Labels: bug

#7421 Docs sfp cicd
  docs/dashboard/cicd/branch-deployments.md
  docs/dashboard/cicd/preview-deployments.md
Labels: cat/dashboard, docs

#7233 Add support for two-way websocket routes. Fixes #6130
  docs/providers/aws/events/websocket.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/lib/naming.test.js
  lib/plugins/aws/package/compile/events/websockets/index.js
  lib/plugins/aws/package/compile/events/websockets/lib/routeResponses.js
  lib/plugins/aws/package/compile/events/websockets/lib/routeResponses.test.js
  lib/plugins/aws/package/compile/events/websockets/lib/routes.js
  lib/plugins/aws/package/compile/events/websockets/lib/routes.test.js
  lib/plugins/aws/package/compile/events/websockets/lib/validate.js
  lib/plugins/aws/package/compile/events/websockets/lib/validate.test.js
  tests/integration-all/websocket/service/core.js
  tests/integration-all/websocket/service/serverless.yml
  tests/integration-all/websocket/tests.js
Labels: enhancement

#7381 untildify path for creating template
  lib/plugins/create/create.js
  lib/plugins/create/create.test.js
Labels: bug, cat/templates

#7467 AWS HTTP API: Do not validate timeout when no httpApi event
  lib/plugins/aws/package/compile/events/httpApi/index.js
Labels: bug

#7476 Respect external IAM role at lambda destinations
  lib/plugins/aws/package/compile/functions/index.js
  lib/plugins/aws/package/compile/functions/index.test.js
Labels: bug, cat/lambda
