Repository serverless/serverless, pull requests merged in 2020-02, with the labels that each got.

#7283 feat: add deploymentBucket.maxPreviousDeploymentArtifacts configuration
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/deploy/lib/cleanupS3Bucket.js
  lib/plugins/aws/deploy/lib/cleanupS3Bucket.test.js
Labels: enhancement

#7299 docs: clarify the sls logs command's startTime parameter's default value
  lib/plugins/logs/logs.js
Labels: docs

#7300 fix: Limited permission for authorizers
  lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.test.js
Labels: bug, cat/api-gw

#7178 improve performance of invoke when using docker
  docs/providers/aws/cli-reference/invoke-local.md
  lib/classes/Utils.js
  lib/plugins/aws/invokeLocal/index.js
  lib/plugins/aws/invokeLocal/index.test.js
  lib/utils/fs/dirExists.js
  package.json
Labels: cat/local-dev

#7319 Add iam role permission boundaries
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/lib/mergeIamTemplates.js
  lib/plugins/aws/package/lib/mergeIamTemplates.test.js
Labels: enhancement

#7324 Fix broken link
  docs/providers/openwhisk/events/apigateway.md
Labels: docs

#7320 Add support for Kinesis Data Streams Enhanced Fan-out (Consumers)
  docs/providers/aws/events/streams.md
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/lib/naming.test.js
  lib/plugins/aws/package/compile/events/stream/index.js
  lib/plugins/aws/package/compile/events/stream/index.test.js
Labels: enhancement

#7322 Add alb.targetGroupPrefix
  docs/providers/aws/events/alb.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/lib/naming.test.js
  lib/plugins/aws/provider/awsProvider.js
  lib/plugins/aws/provider/awsProvider.test.js
Labels: enhancement

#7346 HTTP API: JWT Authorizers
  docs/providers/aws/events/http-api.md
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/package/compile/events/httpApi/index.js
  lib/plugins/aws/package/compile/events/httpApi/index.test.js
  tests/integration-all/http-api/tests.js
Labels: enhancement

#7357 Saner role names
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/lib/naming.test.js
  lib/plugins/aws/package/lib/mergeIamTemplates.test.js
Labels: cat/iam, enhancement

#7368 fix excludeNodeDevDependencies method: dev modules not excluded on invalid package
  lib/plugins/package/lib/zipService.js
Labels: bug, cat/packaging

#7382 Enable association of VPC endpoint ids on AWS private API Gateways
  docs/providers/aws/events/apigateway.md
  lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.test.js
Labels: cat/api-gw, enhancement

#7388 Fix path resolving
  lib/plugins/aws/lib/getServiceState.js
  lib/plugins/aws/lib/getServiceState.test.js
Labels: bug, cat/packaging

#7383 Fix HTTP API default stage handling
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/package/compile/events/httpApi/index.js
  lib/plugins/aws/package/compile/events/httpApi/index.test.js
Labels: bug

#7384 AWS HTTP API serverless.yml documenation
  docs/providers/aws/guide/serverless.yml.md
Labels: docs

#7385 HTTP API: Access logs configuration
  docs/providers/aws/events/http-api.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/package/compile/events/httpApi/index.js
  lib/plugins/aws/package/compile/events/httpApi/index.test.js
  tests/integration-all/http-api/tests.js
Labels: enhancement

#7392 Fixed Typo
  lib/plugins/create/templates/azure-python/serverless.yml
Labels: docs

#7396 HTTP API: Support attachment to externally created API
  docs/providers/aws/events/http-api.md
  lib/plugins/aws/info/getStackInfo.js
  lib/plugins/aws/package/compile/events/httpApi/index.js
  lib/plugins/aws/package/compile/events/httpApi/index.test.js
  tests/fixtures/httpApiExport/serverless.yml
  tests/integration-all/http-api/tests.js
Labels: enhancement

#7393 docs: add missing colons to AWSAccountID
  docs/providers/aws/guide/iam.md
Labels: docs

#7401 AWS HTTP API: Support `timeout` setting
  docs/providers/aws/events/http-api.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/compile/events/httpApi/index.js
  lib/plugins/aws/package/compile/events/httpApi/index.test.js
  tests/fixtures/httpApi/index.js
  tests/integration-all/http-api/tests.js
Labels: enhancement

#7400 Remove stale files which do not specifically have to be in this repository
  0.5.x-RESOURCES.md
Labels: cleanup
