Repository serverless/serverless, pull requests merged in 2020-05, with the labels that each got.

#7648 Change version to function-version in rollback command
  docs/providers/aws/cli-reference/rollback-function.md
  lib/plugins/aws/rollbackFunction/index.js
  lib/plugins/aws/rollbackFunction/index.test.js
  lib/plugins/rollback/index.js
Labels: bug, cat/deployment

#7644 Filter out duplicate create/delete event bus custom policies
  lib/plugins/aws/package/compile/events/eventBridge/index.js
  lib/plugins/aws/package/compile/events/eventBridge/index.test.js
Labels: bug/perf, cat/aws-event-event-bridge

#7632 Implement bool primitive overwrite
  docs/providers/aws/guide/variables.md
  lib/classes/Variables.js
  lib/classes/Variables.test.js
Labels: cat/variable, enhancement

#7666 Remove -v from rollback command
  docs/providers/aws/cli-reference/rollback-function.md
  lib/plugins/aws/rollbackFunction/index.js
  lib/plugins/rollback/index.js
Labels: cat/deployment, refactor

#7665 Refactor conditional logic flaw in deployment monitoring logic
  lib/plugins/aws/lib/monitorStack.js
Labels: cat/deployment, refactor

#7668 Modify cors headers validation to accept single value
  docs/providers/aws/events/apigateway.md
  lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/validate.test.js
Labels: cat/aws-event-api-gateway, enhancement

#7672 Add missing armTemplate attribute to complete Azure serverless.yml
  docs/providers/azure/guide/serverless.yml.md
Labels: docs, provider/azure

#7673 Doc: Update supported regions
  docs/dashboard/README.md
Labels: cat/dashboard, docs

#7674 New contribution guideliness and issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/questions.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  tests/README.md
Labels: docs

#7663 Ensure to update API Gateway stage only for deployed API's
  lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js
Labels: bug, cat/aws-event-api-gateway

#7682 Updating stream event properties "MaximumRetryAttempts" & "BisectBatchOnFunctionError" when value is falsy.
  lib/plugins/aws/package/compile/events/stream/index.js
Labels: bug, cat/event-aws-stream

#7692 Drop sentry reporting logic, as it's not really used
  bin/serverless.js
  lib/classes/Error.js
  lib/classes/Error.test.js
  lib/utils/sentry.js
  package.json
Labels: cat/dependency, cat/security, refactor

#7688 Upgrade dependencies
  package.json
Labels: cat/dependency, refactor

#7684 Fix generation of custom resource lambda zip
  lib/plugins/aws/customResources/generateZip.js
Labels: bug, cat/deployment

#7698 Add missing armTemplate attribute "parameters" to complete serverless.yml
  docs/providers/azure/guide/serverless.yml.md
Labels: documentation, provider/azure

#7701 change api name for serachable
  docs/providers/google/guide/credentials.md
Labels: documentation, provider/google

#7703 Replace _.isArray with native Array.isArray
  lib/classes/PluginManager.js
  lib/classes/Service.js
  lib/classes/Variables.js
  lib/plugins/aws/deployFunction/index.js
  lib/plugins/aws/info/getApiKeyValues.js
  lib/plugins/aws/package/compile/events/alb/lib/validate.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlan.js
  lib/plugins/aws/package/compile/events/s3/index.js
  lib/plugins/aws/package/compile/functions/index.js
  lib/plugins/aws/package/lib/mergeIamTemplates.js
  lib/plugins/aws/utils/findReferences.js
  lib/plugins/plugin/install/install.js
  lib/plugins/plugin/uninstall/uninstall.js
  lib/plugins/print/print.js
  lib/utils/config/index.js
  lib/utils/getCommandSuggestion.js
  lib/utils/yamlAstParser.js
Labels: cat/dependency, refactor

#7707 update uuid v2.0.3 to v8.0.0 #7693 fix
  package.json
Labels: cat/dependency, refactor

#7708 Update aws-csharp to .NET Core 3.1
  docker-compose.yml
  docs/providers/aws/examples/hello-world/csharp/README.md
  lib/plugins/create/templates/aws-csharp/Handler.cs
  lib/plugins/create/templates/aws-csharp/aws-csharp.csproj
  lib/plugins/create/templates/aws-csharp/build.cmd
  lib/plugins/create/templates/aws-csharp/build.sh
  lib/plugins/create/templates/aws-csharp/serverless.yml
Labels: cat/template, runtime/dotnet

#7709 Update aws-fsharp to .NET Core 3.1
  docker-compose.yml
  docs/providers/aws/examples/hello-world/fsharp/README.md
  lib/plugins/create/templates/aws-fsharp/Handler.fs
  lib/plugins/create/templates/aws-fsharp/aws-fsharp.fsproj
  lib/plugins/create/templates/aws-fsharp/build.cmd
  lib/plugins/create/templates/aws-fsharp/build.sh
  lib/plugins/create/templates/aws-fsharp/serverless.yml
Labels: cat/template, runtime/dotnet

#7712 Upgrade archiver to 3.1.1
  package.json
Labels: cat/dependency, refactor

#7694 Fix IAM role and policy name resolution
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/lib/naming.test.js
  lib/plugins/aws/package/lib/mergeIamTemplates.test.js
Labels: bug, cat/aws-iam

#7699 Fix `pkg` issue workaround, so it works on Windows
  lib/utils/standalone-patch.js
Labels: bug, cat/standalone, os/windows

#7717 Improve "Get started.." documentation
  docs/getting-started.md
Labels: documentation

#7677 Allow parameters to be passed in by plugins
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/lib/updateStack.js
  lib/plugins/aws/lib/updateStack.test.js
Labels: cat/deployment, enhancement

#7720 Disable CloudWatch Log Group per function
  docs/providers/aws/guide/functions.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/lib/mergeIamTemplates.js
  lib/plugins/aws/package/lib/mergeIamTemplates.test.js
  tests/.gitignore
Labels: cat/lambda, enhancement

#7721 Ensure lambda edge has no vpc or env
  lib/plugins/aws/package/compile/events/cloudFront/index.js
  lib/plugins/aws/package/compile/events/cloudFront/index.test.js
  tests/fixtures/functionCloudFront/index.js
  tests/fixtures/functionCloudFront/serverless.yml
Labels: bug, cat/aws-event-cloudfront

#7719 Upgrade fs-extra to v8.1.0
  lib/classes/Utils.js
  lib/classes/Variables.js
  lib/classes/Variables.test.js
  lib/plugins/aws/configCredentials/awsConfigCredentials.test.js
  lib/plugins/aws/customResources/generateZip.js
  lib/plugins/aws/customResources/index.js
  lib/plugins/aws/invokeLocal/index.js
  lib/plugins/aws/utils/credentials.test.js
  lib/plugins/executable/index.js
  lib/plugins/interactiveCli/initializeService.test.js
  lib/plugins/interactiveCli/setupAws.test.js
  lib/plugins/plugin/install/install.js
  lib/plugins/plugin/uninstall/uninstall.js
  lib/utils/downloadTemplateFromRepo.test.js
  lib/utils/fs/copyDirContentsSync.js
  lib/utils/fs/dirExists.js
  lib/utils/fs/dirExistsSync.js
  lib/utils/fs/fileExists.js
  lib/utils/fs/fileExistsSync.js
  lib/utils/fs/fileExistsSync.test.js
  lib/utils/fs/fse.js
  lib/utils/fs/readFile.js
  lib/utils/fs/readFileSync.js
  lib/utils/fs/removeFile.js
  lib/utils/fs/removeFileSync.js
  lib/utils/fs/writeFile.js
  lib/utils/fs/writeFile.test.js
  lib/utils/fs/writeFileSync.js
  lib/utils/fs/writeFileSync.test.js
  lib/utils/npm-command-deferred.js
  lib/utils/tracking.js
  lib/utils/tracking.test.js
  package.json
  scripts/pkg/build.js
  scripts/pkg/generate-choco-package.js
  tests/fixtures/index.js
Labels: cat/dependency, refactor

#7725 docs: fix typo
  docs/providers/aws/events/websocket.md
Labels: documentation

#7728 Display error message on duplictate conf path
  lib/utils/resolveCliInput.js
  lib/utils/resolveCliInput.test.js
Labels: bug, cat/cli

#7722 Remove obsolete dependson for iamrolelambdaexecution
  lib/plugins/aws/package/compile/functions/index.js
  lib/plugins/aws/package/compile/functions/index.test.js
  tests/integration-package/cloudformation.tests.js
Labels: bug, cat/lambda

#7730 Upgrade semver to v6
  package.json
Labels: cat/dependency, refactor

#7731 Fix disabled LogGroup exists in DependsOn
  lib/plugins/aws/package/compile/functions/index.js
  lib/plugins/aws/package/compile/functions/index.test.js
Labels: bug, cat/lambda

#7742 checkForChanges should consider user-defined artifact
  lib/plugins/aws/deploy/lib/checkForChanges.js
  lib/plugins/aws/deploy/lib/checkForChanges.test.js
Labels: bug, cat/deployment

#7739 Properly merge OAI value in cloudfront template
  lib/plugins/aws/package/compile/events/cloudFront/index.js
  lib/plugins/aws/package/compile/events/cloudFront/index.test.js
Labels: bug, cat/aws-event-cloudfront

#7622 Fixes serverless#7609 - Improve invoke local docker performance
  lib/plugins/aws/invokeLocal/index.js
  lib/plugins/aws/invokeLocal/index.test.js
Labels: cat/local-dev, enhancement, needs feedback

#7743 Join with serverless dir path only if not start with it
  lib/plugins/aws/deploy/lib/checkForChanges.js
  lib/plugins/aws/deploy/lib/checkForChanges.test.js
Labels: bug, cat/packaging

#7715 Replace lodash utility with String native methods
  lib/classes/PluginManager.js
  lib/plugins/aws/common/lib/artifacts.js
  lib/plugins/aws/deploy/lib/checkForChanges.js
  lib/plugins/aws/invokeLocal/index.test.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/cors.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js
  lib/plugins/aws/package/compile/functions/index.js
  lib/plugins/aws/utils/findReferences.test.js
  lib/plugins/package/lib/zipService.js
Labels: cat/dependency, refactor

#7680 Faster deployment by skipping unchanged lambda layers
  lib/plugins/aws/deploy/lib/uploadArtifacts.js
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/package/compile/layers/index.js
  lib/plugins/aws/package/compile/layers/index.test.js
  lib/plugins/aws/utils/getLambdaLayerArtifactPath.js
Labels: cat/dx, cat/packaging, perf

#7750 Upgrade globby to v9.2.0
  lib/plugins/package/lib/packageService.js
  package.json
Labels: cat/dependency, refactor

#7540 Support non-function exports when including variables from js files
  docs/providers/aws/guide/variables.md
  lib/classes/Variables.js
  lib/classes/Variables.test.js
Labels: cat/variable, enhancement

#7741 Add logDeprecation and tests
  docs/deprecations.md
  docs/providers/aws/guide/serverless.yml.md
  lib/classes/Service.js
  lib/utils/logDeprecation.js
  lib/utils/logDeprecation.test.js
Labels: cat/cli, enhancement

#7760 Fix typo in powershell command example
  docs/providers/aws/examples/hello-world/csharp/README.md
Labels: documentation, runtime/dotnet

#7761 Test: Reliable reproduction test for #7753
  lib/plugins/aws/deploy/lib/checkForChanges.test.js
  tests/fixtures/packageArtifact/artifact.zip
  tests/fixtures/packageArtifact/serverless.yml
Labels: tests

#7759 Deprecate bin/serverless binary
  bin/serverless
  docs/deprecations.md
Labels: cat/cli, deprecation

#7729 Replace internal inquirer with @serverless/inquirer
  lib/plugins/interactiveCli/index.js
  lib/plugins/interactiveCli/initializeService.js
  lib/plugins/interactiveCli/initializeService.test.js
  lib/plugins/interactiveCli/inquirer.js
  lib/plugins/interactiveCli/setupAws.js
  lib/plugins/interactiveCli/setupAws.test.js
  lib/plugins/interactiveCli/tabCompletion.js
  lib/plugins/interactiveCli/tabCompletion.test.js
  lib/plugins/interactiveCli/utils.js
  package.json
Labels: cat/dependency, refactor

#7763 Update json-refs lib
  lib/classes/YamlParser.js
  package.json
Labels: cat/dependency, refactor

#7764 Replace lodash _.every(array) with native Array.every
  lib/plugins/aws/package/compile/events/apiGateway/lib/resources.js
  lib/plugins/aws/utils/findReferences.test.js
Labels: cat/dependency, refactor

#7766 Replace _.assign and _.extend with Object.assign
  lib/classes/PluginManager.js
  lib/classes/Variables.js
  lib/plugins/aws/deploy/lib/createStack.js
  lib/plugins/aws/deploy/lib/extendedValidate.js
  lib/plugins/aws/lib/updateStack.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/authorizers.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
  lib/plugins/aws/package/compile/events/s3/index.js
  lib/plugins/aws/package/lib/generateCoreTemplate.js
  lib/plugins/aws/package/lib/saveServiceState.js
  lib/plugins/aws/provider/awsProvider.js
  lib/plugins/plugin/install/install.test.js
  lib/utils/yamlAstParser.test.js
Labels: cat/dependency, refactor

#7772 Improve documentation: API Gateway payload version
  docs/providers/aws/guide/serverless.yml.md
Labels: cat/aws-event-http-api, documentation

#7775 refactor(lodash): Replace _.filter with array.filter
  lib/plugins/aws/package/compile/events/cognitoUserPool/index.js
  lib/plugins/package/lib/zipService.js
Labels: cat/dependency, refactor

#7778 Downgrade uuid to v3
  package.json
Labels: cat/dependency, refactor

#7765 docs: Azure Functions Doc Updates
  docs/providers/azure/cli-reference/deploy-list.md
  docs/providers/azure/cli-reference/deploy.md
  docs/providers/azure/cli-reference/invoke.md
  docs/providers/azure/cli-reference/logs.md
  docs/providers/azure/cli-reference/remove.md
  docs/providers/azure/cli-reference/rollback.md
  docs/providers/azure/events/blobstorage.md
  docs/providers/azure/events/cosmosdb.md
  docs/providers/azure/events/eventhubs.md
  docs/providers/azure/events/http.md
  docs/providers/azure/events/other.md
  docs/providers/azure/events/queuestorage.md
  docs/providers/azure/events/servicebus.md
  docs/providers/azure/events/timer.md
  docs/providers/azure/guide/deploying.md
  docs/providers/azure/guide/function-apps.md
  docs/providers/azure/guide/functions.md
  docs/providers/azure/guide/intro.md
  docs/providers/azure/guide/quick-start.md
  docs/providers/azure/guide/serverless.yml.md
Labels: documentation, provider/azure

#7784 Replace lodash _.keys with native Object.keys
  lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.test.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/resources.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlanKeys.test.js
  lib/plugins/aws/package/compile/events/cognitoUserPool/index.test.js
  lib/plugins/aws/package/compile/functions/index.js
  lib/plugins/aws/package/lib/generateCoreTemplate.js
  lib/plugins/package/lib/zipService.js
  lib/utils/yamlAstParser.js
Labels: cat/dependency, refactor

#7786 Support customerId in API keys
  docs/providers/aws/events/apigateway.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/info/getApiKeyValues.js
  lib/plugins/aws/info/getApiKeyValues.test.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.test.js
Labels: cat/aws-event-api-gateway, enhancement

#7754 fix(AWS API Gateway) Enable detailed CloudWatch Metrics
  docs/providers/aws/events/apigateway.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.test.js
Labels: cat/aws-event-api-gateway, enhancement

#7787 docs: suggest using latest node version in getting start doc
  docs/getting-started.md
Labels: documentation

#7748 Replace lodash forEach(array) with native Array.forEach
  lib/classes/CLI.js
  lib/classes/PluginManager.js
  lib/classes/Service.js
  lib/plugins/aws/deploy/lib/extendedValidate.js
  lib/plugins/aws/info/display.js
  lib/plugins/aws/info/getApiKeyValues.js
  lib/plugins/aws/package/compile/events/alb/lib/validate.js
  lib/plugins/aws/package/compile/events/alb/lib/validate.test.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.test.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/method/responses.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlan.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlanKeys.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlanKeys.test.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
  lib/plugins/aws/package/compile/events/cognitoUserPool/index.js
  lib/plugins/aws/package/compile/events/s3/index.js
  lib/plugins/aws/package/compile/events/websockets/lib/validate.js
  lib/plugins/aws/package/compile/functions/index.js
  lib/plugins/aws/package/lib/saveServiceState.js
  lib/plugins/aws/provider/awsProvider.test.js
  lib/plugins/package/lib/zipService.js
  lib/utils/getCommandSuggestion.js
  lib/utils/log/log.js
  lib/utils/yamlAstParser.js
Labels: cat/dependency, refactor
