Repository serverless/serverless, pull requests merged in 2020-12, with the labels that each got.

#8561 fixed added deny iam policy when user opt disable log for a function
  lib/plugins/aws/package/lib/mergeIamTemplates.js
  test/unit/lib/plugins/aws/package/lib/mergeIamTemplates.test.js
Labels: bug, cat/lambda

#8569 feat(aws): increase memory limits for functions
  lib/plugins/aws/package/compile/events/cloudFront/index.js
  lib/plugins/aws/provider/awsProvider.js
  test/unit/lib/plugins/aws/package/compile/events/cloudFront/index.test.js
Labels: enhancement

#8574 AWS API Gateway: Fix `integration` schema
  lib/plugins/aws/package/compile/events/apiGateway/index.js
Labels: bug, cat/aws-event-api-gateway, cat/config-schema

#8577 Tests: Refactor main AWS ALB tests
  test/unit/lib/plugins/aws/package/compile/events/alb/index.test.js
Labels: refactor, tests

#8572 AWS Lambda: Container Image Support
  docs/providers/aws/guide/functions.md
  lib/plugins/aws/deploy/lib/extendedValidate.js
  lib/plugins/aws/deploy/lib/uploadArtifacts.js
  lib/plugins/aws/deployFunction/index.js
  lib/plugins/aws/invokeLocal/index.js
  lib/plugins/aws/package/compile/functions/index.js
  lib/plugins/aws/provider/awsProvider.js
  lib/plugins/package/lib/packageService.js
  test/unit/lib/plugins/aws/deploy/lib/checkForChanges.test.js
  test/unit/lib/plugins/aws/package/compile/functions/index.test.js
Labels: cat/lambda, enhancement

#8584 Tests: Pave path for layers tests refactor
  test/fixtures/layer/index.js
  test/fixtures/layer/layer/index.js
  test/fixtures/layer/serverless.yml
  test/unit/lib/plugins/aws/package/compile/layers/index.test.js
Labels: refactor, tests

#8580 Fix broken url in docs
  docs/guides/monitoring/notifications.md
Labels: bug, documentation

#8575 Test:Refactoring lib/plugins/aws/package/lib/mergeIamTemplates.test.js
  test/unit/lib/plugins/aws/package/lib/mergeIamTemplates.test.js
Labels: refactor, tests

#8595 Refactor: Remove superfluous fs utils
  lib/utils/fs/removeFile.js
  lib/utils/fs/removeFileSync.js
  test/unit/lib/utils/fs/copyDirContentsSync.test.js
Labels: refactor

#8596 Tests: Improve AWS HTTP API tests organization
  test/unit/lib/plugins/aws/package/compile/events/httpApi/index.test.js
Labels: refactor, tests

#8598 Remove unused
  lib/utils/fs/readFileIfExists.js
  lib/utils/getTrackingConfigFileName.js
  test/unit/lib/utils/fs/readFileIfExists.test.js
Labels: refactor

#8608 Standalone: Fix upgrade command
  lib/plugins/standalone/index.js
Labels: bug, cat/standalone

#8610 Fix broken url in docs
  docs/guides/profiles.md
Labels: documentation

#8571 Make ALB event path optional
  lib/plugins/aws/package/compile/events/alb/index.js
  lib/plugins/aws/package/compile/events/alb/lib/listenerRules.js
  lib/plugins/aws/package/compile/events/alb/lib/validate.js
  test/unit/lib/plugins/aws/package/compile/events/alb/index.test.js
Labels: cat/aws-event-alb, enhancement

#8602 fix(Packaging): Not exclude layers when packaging a layer
  lib/plugins/package/lib/packageService.js
Labels: bug, cat/packaging, needs feedback

#8611 doc: Add details about how layers patterns are resolved
  docs/providers/aws/guide/layers.md
Labels: documentation

#8601 refactor: Remove dependency to stream-promise
  lib/plugins/standalone/index.js
  package.json
Labels: cat/standalone, refactor

#8615 fix(Packaging): Add exec bit for packaged files on Windows
  lib/plugins/package/lib/packageService.js
  lib/plugins/package/lib/zipService.js
  test/unit/lib/plugins/package/lib/packageService.test.js
  test/unit/lib/plugins/package/lib/zipService.test.js
Labels: bug, cat/packaging

#8593 Remove bluebird and use async/await from most of the AWS plugin
  lib/classes/Variables.js
  lib/plugins/aws/configCredentials.js
  lib/plugins/aws/deployFunction.js
  lib/plugins/aws/deployList.js
  lib/plugins/aws/invoke.js
  lib/plugins/aws/invokeLocal/index.js
  lib/plugins/aws/logs.js
  lib/plugins/aws/metrics.js
  test/unit/lib/plugins/aws/deployFunction.test.js
  test/unit/lib/plugins/aws/deployList.test.js
  test/unit/lib/plugins/aws/invoke.test.js
  test/unit/lib/plugins/aws/invokeLocal/index.test.js
  test/unit/lib/plugins/aws/logs.test.js
  test/unit/lib/plugins/aws/metrics.test.js
Labels: refactor

#8634 fix(Packaging): ensure that .env files are excluded from package
  lib/plugins/package/lib/packageService.js
  test/fixtures/packaging/.env
  test/fixtures/packaging/.env.stage
  test/unit/lib/plugins/package/lib/packageService.test.js
Labels: bug, cat/packaging

#8623 chore(aws): refactor provider-related tests in compile/functions
  test/fixtures/packageArtifact/artifact-function.zip
  test/fixtures/packageArtifact/serverless.yml
  test/unit/lib/plugins/aws/package/compile/functions.test.js
Labels: refactor, tests

#8639 AWS Lambda: Improve "image" property validation
  lib/plugins/aws/provider.js
Labels: bug, cat/lambda-image

#8638 fix(AWS): Allow to disable creation of default bucket policy
  docs/providers/aws/guide/deploying.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/lib/generateCoreTemplate.js
  lib/plugins/aws/provider.js
  test/unit/lib/plugins/aws/package/lib/generateCoreTemplate.test.js
Labels: bug, cat/deployment

#8648 fix(Packaging): Exclude .env files only when useDotenv is set
  docs/deprecations.md
  docs/environment-variables.md
  docs/providers/aws/guide/packaging.md
  lib/plugins/package/lib/packageService.js
  test/unit/lib/plugins/package/lib/packageService.test.js
Labels: bug, cat/packaging

#8654 docs(Config Schema): Add docs for defineTopLevelProperty and helpers map
  docs/providers/aws/guide/plugins.md
Labels: cat/config-schema, documentation

#8659 ci: Correctly log error when China upload fails
  scripts/pkg/upload/index.js
Labels: cat/ci

#8655 Improve schema definition validation to prevent collisions
  lib/classes/ConfigSchemaHandler/index.js
  test/fixtures/configSchemaExtensionsError/test-plugin-with-colliding-custom-property.js
  test/fixtures/configSchemaExtensionsError/test-plugin-with-colliding-function-event-property.js
  test/fixtures/configSchemaExtensionsError/test-plugin-with-colliding-function-event.js
  test/fixtures/configSchemaExtensionsError/test-plugin-with-colliding-function-property.js
  test/fixtures/configSchemaExtensionsError/test-plugin-with-colliding-provider-property-in-function.js
  test/fixtures/configSchemaExtensionsError/test-plugin-with-colliding-provider-property-in-provider.js
  test/fixtures/configSchemaExtensionsError/test-plugin-with-colliding-top-level-property.js
  test/unit/lib/classes/ConfigSchemaHandler/index.test.js
Labels: cat/config-schema, enhancement

#8165 fix(Variables): Fix when properties are null
  lib/classes/Variables.js
Labels: bug, cat/variable, good first issue, help wanted

#8652 feat (AWS Invoke): Allow client context to be passed
  docs/providers/aws/cli-reference/invoke.md
  lib/plugins/aws/invoke.js
  lib/plugins/invoke.js
  test/fixtures/invocation/context.json
  test/unit/lib/plugins/aws/invoke.test.js
Labels: cat/dx, cat/lambda, enhancement

#8661 feat(AWS Deploy): Introduce new version of hashing algorithm
  docs/deprecations.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/lib/normalizeFiles.js
  lib/plugins/aws/package/compile/functions.js
  lib/plugins/aws/package/lib/getHashForFilePath.js
  lib/plugins/aws/provider.js
  lib/utils/deepSortObjectByKey.js
  test/unit/lib/plugins/aws/deploy/lib/checkForChanges.test.js
  test/unit/lib/plugins/aws/lib/normalizeFiles.test.js
  test/unit/lib/plugins/aws/package/compile/functions.test.js
  test/unit/lib/plugins/aws/package/lib/getHashForFilePath.test.js
  test/unit/lib/utils/analytics/generatePayload.test.js
  test/unit/lib/utils/deepSortObjectByKey.test.js
Labels: cat/deployment, cat/lambda, perf

#8685 AWS CloudFront: Ensure to describe resolved stage in comment
  lib/plugins/aws/package/compile/events/cloudFront.js
  test/unit/lib/plugins/aws/package/compile/events/cloudFront.test.js
Labels: bug, cat/aws-event-cloudfront

#8682 Docs: Remove configuration bad patterns
  docs/providers/aws/cli-reference/print.md
  docs/providers/aws/guide/credentials.md
  docs/providers/aws/guide/serverless.yml.md
  docs/providers/aws/guide/variables.md
  docs/providers/azure/guide/serverless.yml.md
Labels: documentation

#8683 feat(AWS Lambda): Support referencing images with tags
  docs/providers/aws/guide/functions.md
  lib/plugins/aws/package/compile/functions.js
  lib/plugins/aws/provider.js
  test/unit/lib/plugins/aws/package/compile/functions.test.js
Labels: cat/lambda-image, enhancement

#8679 docs: Deprecation notice for parameterized app, org, service, stage, …
  docs/deprecations.md
Labels: cat/dashboard, documentation

#8688 fix(AWS Lambda Layers): Permissions on lambda layer retained
  lib/plugins/aws/package/compile/layers.js
  test/unit/lib/plugins/aws/package/compile/layers.test.js
Labels: bug, cat/lambda

#8694 docs: Explanation why deployFunction doesn't have to resolve images
  lib/plugins/aws/deployFunction.js
Labels: documentation
