Repository serverless/serverless, pull requests merged in 2020-01, with the labels that each got.

#7155 Update download deps to latest
  package.json
Labels: cat/templates, cleanup

#7163 Switch to @commitlint/cli
  package.json
Labels: cleanup

#7165 Fix provisioned concurrency issues
  lib/plugins/aws/package/compile/functions/index.js
Labels: bug, cat/lambda

#7158 fix: Auto-delete on AWS stack create failure when using a custom deployment bucket
  lib/plugins/aws/lib/updateStack.js
  lib/plugins/aws/lib/updateStack.test.js
Labels: bug

#7182 Upgrade https-proxy-agent to v4
  package.json
Labels: cat/security

#7175 Remove hard-coded AWS partitions
  lib/plugins/aws/package/compile/events/alb/lib/validate.js
  lib/plugins/aws/package/compile/events/alb/lib/validate.test.js
  lib/plugins/aws/package/compile/events/cloudFront/index.js
  lib/plugins/aws/package/compile/events/cloudFront/index.test.js
  lib/plugins/aws/package/compile/events/websockets/lib/stage.js
  lib/plugins/aws/package/compile/events/websockets/lib/stage.test.js
  lib/plugins/aws/provider/awsProvider.js
Labels: bug

#7105 Add BisectBatchOnFunctionError option for Dynamo and Kinesis event sourcing
  docs/providers/aws/events/streams.md
  lib/plugins/aws/package/compile/events/stream/index.js
  lib/plugins/aws/package/compile/events/stream/index.test.js
Labels: cat/event-src, feature, pr/in-review

#7195 Tests: Fix download template race condition
  lib/utils/downloadTemplateFromRepo.test.js
Labels: cat/tests

#7170 Improve creation of origins and behaviors in cloudFront event
  docs/providers/aws/events/cloudfront.md
  lib/plugins/aws/invokeLocal/index.js
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/lib/naming.test.js
  lib/plugins/aws/package/compile/events/cloudFront/index.js
  lib/plugins/aws/package/compile/events/cloudFront/index.test.js
  lib/plugins/aws/package/compile/functions/index.js
  lib/plugins/aws/provider/awsProvider.js
  lib/plugins/package/lib/packageService.js
Labels: bug

#7193 add rollbackConfiguration
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/lib/updateStack.js
  lib/plugins/aws/lib/updateStack.test.js
Labels: enhancement

#7200 Upgrade `graceful-fs` to ^4.2.3
  package.json
Labels: cleanup

#7212 Fix default APIGW resource policy configuration
  lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.test.js
Labels: bug

#7213 Tests: Fix download template race condition
  lib/utils/downloadTemplateFromRepo.test.js
Labels: cat/tests

#7215 Tests: Upgrade to @serverless/test v3.4.0
  package.json
  tests/integration-all/api-gateway/tests.js
  tests/integration-all/websocket/tests.js
  tests/integration-basic/tests.js
  tests/utils/api-gateway/index.js
  tests/utils/cloudformation/index.js
  tests/utils/cloudwatch/index.js
  tests/utils/cognito/index.js
  tests/utils/dynamodb/index.js
  tests/utils/eventBridge/index.js
  tests/utils/iot/index.js
  tests/utils/kinesis/index.js
  tests/utils/misc/index.js
  tests/utils/s3/index.js
  tests/utils/sns/index.js
  tests/utils/sqs/index.js
  tests/utils/websocket/index.js
Labels: cat/tests

#7218 corrected spelling errors
  .travis.yml
  lib/plugins/executable/index.js
Labels: cleanup

#7230 Update quick-start.md
  docs/providers/azure/guide/quick-start.md
Labels: docs

#7221 Update /cn Component docs
  docs/cn/README.md
  docs/cn/providers/tencent/README.md
  docs/cn/providers/tencent/cli-reference/README.md
  docs/cn/providers/tencent/components/README.md
  docs/cn/providers/tencent/components/basic-components/README.md
  docs/cn/providers/tencent/components/basic-components/tencent-apigateway.md
  docs/cn/providers/tencent/components/basic-components/tencent-cam-policy.md
  docs/cn/providers/tencent/components/basic-components/tencent-cam-role.md
  docs/cn/providers/tencent/components/basic-components/tencent-cdn.md
  docs/cn/providers/tencent/components/basic-components/tencent-cos.md
  docs/cn/providers/tencent/components/basic-components/tencent-scf.md
  docs/cn/providers/tencent/components/high-level-components/README.md
  docs/cn/providers/tencent/components/high-level-components/tencent-egg.md
  docs/cn/providers/tencent/components/high-level-components/tencent-express.md
  docs/cn/providers/tencent/components/high-level-components/tencent-flask.md
  docs/cn/providers/tencent/components/high-level-components/tencent-hexo.md
  docs/cn/providers/tencent/components/high-level-components/tencent-koa.md
  docs/cn/providers/tencent/components/high-level-components/tencent-laravel.md
  docs/cn/providers/tencent/components/high-level-components/tencent-react-full-stack.md
  docs/cn/providers/tencent/components/high-level-components/tencent-rest-api.md
  docs/cn/providers/tencent/components/high-level-components/tencent-vue-full-stack.md
  docs/cn/providers/tencent/components/high-level-components/tencent-website.md
  docs/cn/providers/tencent/events/COS.md
Labels: docs

#7245 Do not overwrite `go.mod` on `make` if it exists.
  lib/plugins/create/templates/aws-go-mod/gomod.sh
Labels: bug, cat/templates

#7252 Added azure-nodejs-typescript template.
  lib/plugins/create/create.js
  lib/plugins/create/create.test.js
  lib/plugins/create/templates/azure-nodejs-typescript/README.md
  lib/plugins/create/templates/azure-nodejs-typescript/gitignore
  lib/plugins/create/templates/azure-nodejs-typescript/host.json
  lib/plugins/create/templates/azure-nodejs-typescript/package.json
  lib/plugins/create/templates/azure-nodejs-typescript/serverless.yml
  lib/plugins/create/templates/azure-nodejs-typescript/src/handlers/goodbye.ts
  lib/plugins/create/templates/azure-nodejs-typescript/src/handlers/hello.ts
  lib/plugins/create/templates/azure-nodejs-typescript/tsconfig.json
  lib/plugins/create/templates/azure-nodejs-typescript/webpack.config.js
Labels: cat/templates

#7248 CloudFormation normalization for WebSockets deployment resource
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/lib/naming.test.js
  lib/plugins/aws/lib/normalizeFiles.js
  lib/plugins/aws/lib/normalizeFiles.test.js
  lib/plugins/aws/package/compile/events/websockets/index.js
  lib/plugins/aws/package/compile/events/websockets/index.test.js
  lib/plugins/aws/package/compile/events/websockets/lib/deployment.js
  lib/plugins/aws/package/compile/events/websockets/lib/deployment.test.js
  lib/plugins/aws/package/compile/events/websockets/lib/pickWebsocketsTemplatePart.js
  lib/plugins/aws/package/compile/events/websockets/lib/pickWebsocketsTemplatePart.test.js
  lib/plugins/aws/package/compile/events/websockets/lib/stage.js
  lib/plugins/aws/package/compile/events/websockets/lib/stage.test.js
Labels: enhancement

#7273 Ensure to use proper CLI params parser in a script
  scripts/pkg/generate-choco-package.js
Labels: bug

#7270 fix: Ensure to show streaming logs for all lamda versions
  lib/plugins/aws/logs/index.js
Labels: bug, cat/lambda

#7156 Simplify s3 event with custom bucket configuration
  docs/providers/aws/events/s3.md
  lib/plugins/aws/package/compile/events/s3/index.js
  lib/plugins/aws/package/compile/events/s3/index.test.js
  tests/integration-all/s3/service/core.js
  tests/integration-all/s3/service/serverless.yml
  tests/integration-all/s3/tests.js
Labels: cat/lambda, enhancement
