Repository serverless/serverless, pull requests merged in 2021-01, with the labels that each got.

#8324 Add IoT fleet provisioning event type
  docs/providers/aws/README.md
  docs/providers/aws/events/iot-fleet-provisioning.md
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/package/compile/events/iotFleetProvisioning.js
  lib/plugins/index.js
  test/fixtures/iotFleetProvisioning/hook.js
  test/fixtures/iotFleetProvisioning/package.json
  test/fixtures/iotFleetProvisioning/registerDevice.js
  test/fixtures/iotFleetProvisioning/serverless.yml
  test/fixtures/iotFleetProvisioning/template.json
  test/integration/iotFleetProvisioning.test.js
  test/unit/lib/plugins/aws/package/compile/events/iotFleetProvisioning/index.test.js
  test/utils/iot.js
Labels: cat/aws-event-iot, enhancement

#8703 Update ajv to v7
  lib/classes/ConfigSchemaHandler/index.js
  lib/classes/ConfigSchemaHandler/normalizeAjvErrors.js
  lib/classes/ConfigSchemaHandler/resolveDataPathSize.js
  package.json
  test/unit/lib/classes/ConfigSchemaHandler/normalizeAjvErrors.test.js
  test/unit/lib/classes/ConfigSchemaHandler/resolveDataPathSize.test.js
Labels: cat/dependency, enhancement

#8711 Docs params update
  docs/guides/parameters.md
  docs/guides/profiles.md
  docs/guides/providers.md
Labels: cat/dashboard, documentation

#8723 feat: Update to Node 14 for standalone binaries
  scripts/pkg/build.js
Labels: cat/standalone, enhancement

#8722 fix(Config Schema): use ajv formats
  lib/classes/ConfigSchemaHandler/index.js
  package.json
Labels: bug, cat/config-schema

#8315 fix(Packaging): Consider absolute artifact paths (#8325)
  lib/plugins/package/lib/packageService.js
  test/unit/lib/plugins/package/lib/packageService.test.js
Labels: bug, cat/packaging, help wanted

#8728 docs: Updating migration and release dates
  docs/guides/profiles.md
Labels: cat/dashboard, documentation

#8719 docs: Improve documentation around deprecations #8665
  docs/deprecations.md
  lib/classes/CLI.js
Labels: documentation

#8732 CLI: Remove bluebird config
  scripts/serverless.js
Labels: bug, cat/cli

#8741 CLI: Seclude version output functionality out of CLI class
  lib/classes/CLI.js
  lib/cli/eventually-list-version.js
  scripts/serverless.js
  test/unit/lib/classes/CLI.test.js
  test/unit/lib/cli/eventually-list-version.test.js
Labels: cat/cli, refactor

#8743 Seclude ServerlessError into lib/serverless-error.js
  lib/Serverless.js
  lib/classes/Error.js
  lib/loadEnv.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
  lib/plugins/aws/package/compile/events/websockets/lib/stage.js
  lib/plugins/aws/utils/resolveCfImportValue.js
  lib/plugins/aws/utils/resolveCfRefValue.js
  lib/plugins/create/create.js
  lib/serverless-error.js
  lib/utils/downloadTemplateFromRepo.js
  lib/utils/getServerlessConfigFile.js
  lib/utils/renameService.js
  lib/utils/resolveCliInput.js
  test/unit/lib/classes/Error.test.js
  test/unit/lib/loadEnv.test.js
  test/unit/lib/serverless-error.test.js
Labels: refactor

#8745 test: Cover AwsRemove with runServerless-based tests
  test/unit/lib/plugins/aws/remove/index.test.js
Labels: refactor, tests

#8747 docs: Add note about disabledDeprecations setting
  docs/deprecations.md
Labels: documentation

#8744 refactor: Seclude ensureExists util
  lib/plugins/aws/customResources/generateZip.js
  lib/plugins/aws/invokeLocal/index.js
  lib/utils/ensureArtifact.js
  lib/utils/ensureExists.js
  lib/utils/getEnsureArtifact.js
  test/mochaPatch.js
  test/unit/lib/utils/ensureExists.test.js
  test/unit/lib/utils/getEnsureArtifact.test.js
Labels: refactor

#8746 test: Refactor several AwsDeploy tests to runServerless
  test/unit/lib/plugins/aws/deploy/index.test.js
Labels: refactor

#8749 refactor: Refactor Serverless.run to async
  lib/Serverless.js
Labels: refactor

#8710 feat(Variables): Introduce unresolvedVariablesNotificationMode
  docs/deprecations.md
  docs/providers/aws/guide/serverless.yml.md
  docs/providers/aws/guide/variables.md
  lib/classes/Service.js
  lib/classes/Variables.js
  lib/configSchema.js
  test/unit/lib/classes/Variables.test.js
Labels: cat/variable, deprecation, enhancement

#8751 refactor: Abstract custom deployment role usage
  lib/plugins/aws/customResources/index.js
  lib/plugins/aws/deploy/lib/createStack.js
  lib/plugins/aws/lib/updateStack.js
  lib/plugins/aws/provider.js
  lib/plugins/aws/remove/lib/stack.js
  test/unit/lib/plugins/aws/customResources/index.test.js
Labels: cat/aws-iam, refactor

#8759 AWS CloudFront: Fix deprecations visibility
  lib/plugins/aws/package/compile/events/cloudFront.js
Labels: bug, cat/aws-event-cloudfront

#8757 test: Do not rely on `updateConfig` between packageService tests
  test/fixtures/packageArtifact/absoluteArtifact.zip
  test/unit/lib/plugins/package/lib/packageService.test.js
Labels: tests

#8760 test: Cleanup invalid before in packageService.test.js
  test/unit/lib/plugins/package/lib/packageService.test.js
Labels: tests

#8762 fix(Config Schema): Revert to ajv v6
  lib/classes/ConfigSchemaHandler/index.js
  lib/classes/ConfigSchemaHandler/normalizeAjvErrors.js
  lib/classes/ConfigSchemaHandler/resolveDataPathSize.js
  package.json
  test/unit/lib/classes/ConfigSchemaHandler/normalizeAjvErrors.test.js
  test/unit/lib/classes/ConfigSchemaHandler/resolveDataPathSize.test.js
Labels: cat/dependency

#8767 Tests: Do not use Mocha parallel mode
  package.json
Labels: bug, tests

#8725 feat(AWS Lambda): Add support for building Docker images
  docs/providers/aws/guide/deploying.md
  docs/providers/aws/guide/functions.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/deploy/index.js
  lib/plugins/aws/deployFunction.js
  lib/plugins/aws/lib/checkIfEcrRepositoryExists.js
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/package/compile/functions.js
  lib/plugins/aws/provider.js
  lib/plugins/aws/remove/index.js
  lib/plugins/aws/remove/lib/ecr.js
  test/fixtures/ecr/Dockerfile
  test/fixtures/ecr/app.js
  test/fixtures/ecr/serverless.yml
  test/unit/lib/plugins/aws/deploy/index.test.js
  test/unit/lib/plugins/aws/deployFunction.test.js
  test/unit/lib/plugins/aws/package/compile/functions.test.js
  test/unit/lib/plugins/aws/provider.test.js
  test/unit/lib/plugins/aws/remove/index.test.js
Labels: cat/lambda-image, enhancement

#8775 fix(AWS Lambda): Ensure ECR repository name is lowercased
  lib/plugins/aws/lib/naming.js
Labels: bug, cat/lambda-image

#8777 fix(AWS Lambda): Ensure to attempt ECR login on expired token
  lib/plugins/aws/provider.js
  test/unit/lib/plugins/aws/provider.test.js
Labels: bug, cat/lambda-image

#8792 fix: Complete async refactor for `aws/deploy` and `customResources`
  lib/plugins/aws/customResources/resources/apiGatewayCloudWatchRole/handler.js
  lib/plugins/aws/customResources/resources/cognitoUserPool/lib/userPool.js
  lib/plugins/aws/customResources/resources/utils.js
  lib/plugins/aws/deploy/lib/createStack.js
  test/unit/lib/plugins/aws/deploy/lib/createStack.test.js
  test/unit/lib/plugins/aws/deploy/lib/uploadArtifacts.test.js
Labels: bug

#8793 CLI: Allow absolute path in `--config`
  lib/cli/resolve-configuration-path.js
  test/unit/lib/cli/resolve-configuration-path.test.js
Labels: cat/cli, enhancement

#8786 fix(AWS Lambda): Ensure function update works when image used
  lib/plugins/aws/deployFunction.js
  test/unit/lib/plugins/aws/deployFunction.test.js
Labels: cat/lambda, cat/lambda-image, enhancement

#8799 Test: Enable temporary patch unconditionally
  test/mochaPatch.js
Labels: tests

#8804 CLI: Bring back support for referencing nested configurations
  docs/deprecations.md
  lib/cli/resolve-configuration-path.js
  test/unit/lib/cli/resolve-configuration-path.test.js
Labels: bug, cat/cli, deprecation

#8809 fix(Standalone): Ensure proper resolution of runtime wrappers
  lib/plugins/aws/invokeLocal/index.js
Labels: bug, cat/local-dev, cat/standalone

#8788 Replace fse.exists with fs.promises.access
  lib/plugins/interactiveCli/initializeService.js
  lib/utils/createFromTemplate.js
Labels: refactor

#8697 feat: Support `kmsKeyArn` for `deploy function`
  lib/plugins/aws/deployFunction.js
  test/unit/lib/plugins/aws/deployFunction.test.js
Labels: bug, cat/deployment, cat/lambda

#8822 Tests: Cleanup packaging tests and spec
  test/fixtures/packaging/serverless.yml
  test/unit/lib/plugins/package/lib/packageService.test.js
Labels: cat/packaging, tests

#8825 CLI: Fix resolution of "--config=<configPath>" format
  lib/cli/resolve-configuration-path.js
  test/unit/lib/cli/resolve-configuration-path.test.js
Labels: bug, cat/cli

#8784 feat(AWS Lambda): Add support for self-managed `kafka` event
  docs/providers/aws/events/kafka.md
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/package/compile/events/kafka.js
  lib/plugins/index.js
  test/unit/lib/plugins/aws/lib/naming.test.js
  test/unit/lib/plugins/aws/package/compile/events/kafka.test.js
Labels: cat/aws-event-kafka, enhancement

#8831 fix(Packaging): Proper exclusion of dependencies across platforms
  lib/plugins/package/lib/zipService.js
Labels: bug, cat/packaging

#8826 fix(AWS CloudFront): Ensure unique names for cache policy
  docs/providers/aws/events/cloudfront.md
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/package/compile/events/cloudFront.js
  test/unit/lib/plugins/aws/package/compile/events/cloudFront.test.js
Labels: bug, cat/aws-event-cloudfront

#8766 Fix using dashes in AWS resource tags, add unit tests
  lib/plugins/aws/provider.js
  test/unit/lib/plugins/aws/package/compile/functions.test.js
Labels: bug, cat/lambda

#8835 CLI: fix service path resolution when nested config is involved
  lib/Serverless.js
  lib/cli/resolve-configuration-path.js
Labels: bug, cat/cli

#8844 fix(Config Schema): Add type to logRetentionInDays
  lib/plugins/aws/provider.js
Labels: bug, cat/config-schema

#8847 fix(Template): Ensure that `.gitignore` is packaged for templates
  .gitignore
  lib/plugins/create/templates/aliyun-nodejs/.gitignore
  lib/plugins/create/templates/aws-alexa-typescript/.gitignore
  lib/plugins/create/templates/aws-clojure-gradle/.gitignore
  lib/plugins/create/templates/aws-clojurescript-gradle/.gitignore
  lib/plugins/create/templates/aws-csharp/.gitignore
  lib/plugins/create/templates/aws-fsharp/.gitignore
  lib/plugins/create/templates/aws-go-dep/.gitignore
  lib/plugins/create/templates/aws-go-mod/.gitignore
  lib/plugins/create/templates/aws-go/.gitignore
  lib/plugins/create/templates/aws-groovy-gradle/.gitignore
  lib/plugins/create/templates/aws-java-gradle/.gitignore
  lib/plugins/create/templates/aws-java-maven/.gitignore
  lib/plugins/create/templates/aws-kotlin-jvm-gradle-kts/.gitignore
  lib/plugins/create/templates/aws-kotlin-jvm-gradle/.gitignore
  lib/plugins/create/templates/aws-kotlin-jvm-maven/.gitignore
  lib/plugins/create/templates/aws-kotlin-nodejs-gradle/.gitignore
  lib/plugins/create/templates/aws-nodejs-ecma-script/.gitignore
  lib/plugins/create/templates/aws-nodejs-typescript/.gitignore
  lib/plugins/create/templates/aws-nodejs/.gitignore
  lib/plugins/create/templates/aws-provided/.gitignore
  lib/plugins/create/templates/aws-python/.gitignore
  lib/plugins/create/templates/aws-python3/.gitignore
  lib/plugins/create/templates/aws-ruby/.gitignore
  lib/plugins/create/templates/aws-scala-sbt/.gitignore
  lib/plugins/create/templates/azure-csharp/.gitignore
  lib/plugins/create/templates/azure-nodejs-typescript/.gitignore
  lib/plugins/create/templates/azure-nodejs/.gitignore
  lib/plugins/create/templates/azure-python/.gitignore
  lib/plugins/create/templates/google-nodejs/.gitignore
  lib/plugins/create/templates/google-python/.gitignore
  lib/plugins/create/templates/hello-world/.gitignore
  lib/plugins/create/templates/knative-docker/.gitignore
  lib/plugins/create/templates/kubeless-nodejs/.gitignore
  lib/plugins/create/templates/kubeless-python/.gitignore
  lib/plugins/create/templates/openwhisk-nodejs/.gitignore
  lib/plugins/create/templates/openwhisk-php/.gitignore
  lib/plugins/create/templates/openwhisk-python/.gitignore
  lib/plugins/create/templates/openwhisk-ruby/.gitignore
  lib/plugins/create/templates/openwhisk-swift/.gitignore
  lib/plugins/create/templates/spotinst-nodejs/.gitignore
  lib/plugins/create/templates/spotinst-python/.gitignore
  lib/plugins/create/templates/spotinst-ruby/.gitignore
  lib/plugins/create/templates/tencent-go/.gitignore
  lib/plugins/create/templates/tencent-nodejs/.gitignore
  lib/plugins/create/templates/tencent-php/.gitignore
  lib/plugins/create/templates/tencent-python/.gitignore
  lib/plugins/create/templates/twilio-nodejs/.gitignore
  lib/utils/createFromTemplate.js
  test/unit/lib/plugins/create/create.test.js
Labels: cat/template, enhancement

#8845 feat(Templates): Add aws-nodejs-docker template
  lib/plugins/create/create.js
  lib/plugins/create/templates/aws-nodejs-docker/.gitignore
  lib/plugins/create/templates/aws-nodejs-docker/Dockerfile
  lib/plugins/create/templates/aws-nodejs-docker/README.md
  lib/plugins/create/templates/aws-nodejs-docker/app.js
  lib/plugins/create/templates/aws-nodejs-docker/serverless.yml
Labels: cat/template, enhancement

#8846 feat(Templates): Add aws-python-docker template
  lib/plugins/create/create.js
  lib/plugins/create/templates/aws-python-docker/.gitignore
  lib/plugins/create/templates/aws-python-docker/Dockerfile
  lib/plugins/create/templates/aws-python-docker/README.md
  lib/plugins/create/templates/aws-python-docker/app.py
  lib/plugins/create/templates/aws-python-docker/serverless.yml
Labels: cat/template, enhancement

#8853 refactor: Replace `fse.promises.realpath` with `fs.promises.realpath`
  test/unit/lib/cli/resolve-local-serverless-path.test.js
Labels: refactor
