Repository serverless/serverless, pull requests merged in 2021-03, with the labels that each got.

#8870 refactor: Use `async` in `lib/plugins/aws/package`
  lib/plugins/aws/package/compile/functions.js
  lib/plugins/aws/package/compile/layers.js
  lib/plugins/aws/package/index.js
  lib/plugins/aws/package/lib/generateArtifactDirectoryName.js
  lib/plugins/aws/package/lib/generateCoreTemplate.js
  lib/plugins/aws/package/lib/getHashForFilePath.js
  lib/plugins/aws/package/lib/mergeCustomProviderResources.js
  lib/plugins/aws/package/lib/saveServiceState.js
  test/unit/lib/plugins/aws/package/lib/generateArtifactDirectoryName.test.js
  test/unit/lib/plugins/aws/package/lib/mergeCustomProviderResources.test.js
  test/unit/lib/plugins/aws/package/lib/saveServiceState.test.js
Labels: refactor

#9028 refactor: Remove `bluebird` from `lib/plugins/package`
  lib/plugins/package/lib/packageService.js
  lib/plugins/package/lib/zipService.js
  lib/plugins/package/package.js
  test/unit/lib/plugins/package/lib/zipService.test.js
Labels: refactor

#9029 refactor: Remove `bluebird` from `lib/plugins/interactiveCli`
  lib/plugins/interactiveCli/setupAws.js
  lib/plugins/interactiveCli/tabCompletion.js
  test/unit/lib/plugins/interactiveCli/autoUpdate.test.js
  test/unit/lib/plugins/interactiveCli/setupAws.test.js
  test/unit/lib/plugins/interactiveCli/tabCompletion.test.js
Labels: refactor

#9035 Tests: Update integration tests to not rely on deprecated features
  test/fixtures/apiGateway/serverless.yml
  test/fixtures/apiGatewayExtended/serverless.yml
  test/fixtures/checkForChanges/serverless.yml
  test/fixtures/cognitoUserPool/serverless.yml
  test/fixtures/eventBridge/serverless.yml
  test/fixtures/function/serverless.yml
  test/fixtures/functionCloudFront/serverless.yml
  test/fixtures/functionDestinations/serverless.yml
  test/fixtures/functionLayers/serverless.yml
  test/fixtures/httpApi/serverless.yml
  test/fixtures/httpApiCatchAll/serverless.yml
  test/fixtures/httpApiExport/serverless.yml
  test/fixtures/invocation/serverless.yml
  test/fixtures/iot/serverless.yml
  test/fixtures/layer/serverless.yml
  test/fixtures/packageArtifact/serverless.yml
  test/fixtures/packageArtifactInServerlessDir/serverless.yml
  test/fixtures/packaging/serverless.yml
  test/fixtures/plugin/serverless.yml
  test/fixtures/provisionedConcurrency/serverless.yml
  test/fixtures/requestSchema/serverless.yml
  test/fixtures/sns/serverless.yml
  test/fixtures/sqs/serverless.yml
  test/fixtures/stream/serverless.yml
  test/integrationPackage/fixtures/artifact/serverless.yml
  test/integrationPackage/fixtures/individually-function/serverless.yml
  test/integrationPackage/fixtures/individually/serverless.yml
  test/integrationPackage/fixtures/regular/serverless.yml
  test/unit/lib/plugins/aws/deploy/index.test.js
  test/unit/lib/plugins/aws/deploy/lib/checkForChanges.test.js
Labels: tests

#9034 Improve deprecation message related to lambda versioning
  docs/deprecations.md
  lib/plugins/aws/package/compile/functions.js
Labels: bug, cat/dx

#9045 AWS Credentials: Fix unrecognized profile error reporting
  lib/plugins/aws/provider.js
Labels: bug, cat/aws-auth, cat/dx

#9050 Variables: Ensure to resolve variables in resolved strings
  lib/configuration/variables/resolve.js
  test/unit/lib/configuration/variables/resolve.test.js
Labels: bug, cat/variable

#9060 fix(Variables): Fix variables setup for external plugins usage
  lib/Serverless.js
Labels: bug, cat/plugin, cat/variable

#9061 Variables: Reject unresolved "plugins" property
  scripts/serverless.js
  test/unit/scripts/serverless.test.js
Labels: bug, cat/variable

#9059 docs: Update docs around `provider.iam` usage
  docs/providers/aws/cli-reference/invoke.md
  docs/providers/aws/events/apigateway.md
  docs/providers/aws/guide/functions.md
  docs/providers/aws/guide/serverless.yml.md
  docs/providers/aws/guide/variables.md
Labels: documentation

#9063 Variables: Ensure to apply intialization patch unconditionally
  lib/Serverless.js
  test/unit/lib/Serverless.test.js
Labels: bug, cat/plugin, cat/variable

#9086 Rely on "isHelpRequest" util internally
  lib/classes/CLI.js
  lib/classes/PluginManager.js
  test/unit/lib/classes/CLI.test.js
  test/unit/lib/classes/PluginManager.test.js
Labels: cat/cli, refactor

#9085 Variables: Improve error message related to JS function resolver
  lib/configuration/variables/sources/file.js
Labels: bug, cat/dx, cat/variable

#9039 feat(AWS IAM): Allow `tags` parameter on lambda execution role
  docs/providers/aws/guide/iam.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/compile/functions.js
  lib/plugins/aws/package/lib/mergeIamTemplates.js
  lib/plugins/aws/provider.js
  test/unit/lib/plugins/aws/package/lib/mergeIamTemplates.test.js
Labels: cat/aws-iam, enhancement

#9082 feat(Config Schema): Accept `accountId` as policy principal
  lib/plugins/aws/provider.js
Labels: bug, cat/config-schema

#9089 fix(Config Schema): Support CF functions for managed policies
  lib/plugins/aws/provider.js
Labels: bug, cat/config-schema

#9041 fix(AWS Deploy): Warn when invalid IAM policy to fetch lambda
  lib/plugins/aws/deploy/lib/checkForChanges.js
  test/unit/lib/plugins/aws/deploy/lib/checkForChanges.test.js
Labels: bug, cat/deployment

#9092 feat(CLI): Report Platform Client instead of SDK version
  lib/cli/list-version.js
  package.json
  test/unit/lib/cli/list-version.test.js
Labels: cat/cli, refactor

#9079 fix(AWS Local Invocation): Support `env` vars with `=` in value
  lib/plugins/invoke.js
  test/unit/lib/plugins/aws/invokeLocal/index.test.js
Labels: bug, cat/local-dev

#9102 AWS Deploy: Fix "sls deploy function" error handling
  lib/plugins/aws/deployFunction.js
  test/unit/lib/plugins/aws/deployFunction.test.js
Labels: bug, cat/deployment

#8850 refactor: seclude request from aws provider
  lib/aws/request.js
  lib/plugins/aws/provider.js
  test/unit/lib/aws/request.test.js
  test/unit/lib/plugins/aws/provider.test.js
Labels: refactor

#9106 fix(Templates): Fix runtime for `azure-nodejs-typescript`
  lib/plugins/create/templates/azure-nodejs-typescript/serverless.yml
Labels: bug, cat/template

#9110 Variables: Retry JS function resolvers on unresolved dependencies
  lib/configuration/variables/sources/file.js
  test/unit/lib/configuration/variables/sources/file.test.js
  test/unit/lib/configuration/variables/sources/fixture/file-function-access-unresolvable-property.js
  test/unit/lib/configuration/variables/sources/fixture/file-property-function-access-unresolvable-property.js
Labels: bug, cat/variable

#9103 fix(AWS IAM): Accept `arn:${AWS::Partition}` in function roles
  lib/plugins/aws/package/compile/functions.js
  test/unit/lib/plugins/aws/package/compile/functions.test.js
Labels: bug, cat/aws-iam

#9078 feat: Improve payload via `generatePayload`
  lib/utils/analytics/generatePayload.js
  package.json
  test/unit/lib/utils/analytics/generatePayload.test.js
Labels: enhancement

#9120 fix(AWS Lambda): Ensure correct schema for `vpc` definition
  lib/plugins/aws/provider.js
Labels: bug, cat/lambda

#9121 Fix AWS credentials resolution
  lib/plugins/aws/provider.js
  test/unit/lib/plugins/aws/provider.test.js
Labels: bug, cat/aws-auth

#9118 fix(AWS EventBridge): Clarify CF functions support for `eventBus`
  docs/providers/aws/events/event-bridge.md
  lib/plugins/aws/package/compile/events/eventBridge/index.js
Labels: bug, cat/aws-event-event-bridge, documentation

#9124 AWS Credentials: Fix credentials resolution (right way)
  lib/plugins/aws/provider.js
  test/unit/lib/plugins/aws/provider.test.js
Labels: bug, cat/aws-auth

#9127 Bring back "provider.sdk" property, to not break plugins
  lib/plugins/aws/provider.js
Labels: bug, cat/plugin

#9131 fix(CLI): support multiple env options
  lib/cli/commands-schema.js
  lib/cli/resolve-input.js
  test/unit/lib/cli/resolve-input.test.js
Labels: bug, cat/cli, cat/local-dev

#9133 fix: Ensure to handle empty func definition with meaningful error
  lib/classes/Service.js
  test/unit/lib/classes/Service.test.js
Labels: bug, cat/cli

#9142 fix(Packaging): Ensure to properly exclude when NODE_ENV set
  lib/plugins/package/lib/zipService.js
Labels: bug, cat/packaging

#9148 Improve AWS SDK errors reporting (debugging)
  lib/aws/request.js
Labels: cat/dx, enhancement

#9152 docs(AWS API Gateway): Update how to disable access and execution logs
  docs/providers/aws/events/apigateway.md
Labels: documentation

#9159 fix(AWS Deploy): Correctly detect finished stack removal with DEBUG
  lib/plugins/aws/lib/monitorStack.js
Labels: bug, cat/deployment

#9147 hotfix(env): (#9146) revert WHATWG URL to use url to verify usage of https-proxy-agent
  lib/aws/request.js
  lib/plugins/plugin/lib/utils.js
Labels: bug/external

#9160 feat(AWS API Gateway): Remove deprecation for old naming convention
  docs/deprecations.md
  lib/plugins/aws/package/compile/events/apiGateway/index.js
Labels: cat/aws-event-api-gateway, enhancement

#9164 fix(Variables): Ensure necessary resolution interface for plugins
  lib/Serverless.js
Labels: bug, cat/plugin, cat/variable

#9166 feat(AWS IAM): Add support for `iam.role.name` definition
  docs/providers/aws/guide/iam.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/provider.js
  test/unit/lib/plugins/aws/lib/naming.test.js
  test/unit/lib/plugins/aws/package/lib/mergeIamTemplates.test.js
Labels: cat/aws-iam, enhancement

#9175 feat: Detect Serverless CI/CD engine for analytics
  lib/utils/analytics/generatePayload.js
  test/unit/lib/utils/analytics/generatePayload.test.js
Labels: enhancement

#9177 feat(AWS Lambda): Do not require all image properties
  docs/providers/aws/guide/functions.md
  lib/plugins/aws/provider.js
Labels: cat/lambda-image, enhancement

#8581 feat(Packaging): Add patterns setting and deprecate include/exclude
  docs/deprecations.md
  docs/guides/monitoring/README.md
  docs/providers/aliyun/guide/packaging.md
  docs/providers/aws/guide/packaging.md
  docs/providers/aws/guide/serverless.yml.md
  docs/providers/azure/guide/packaging.md
  docs/providers/azure/guide/serverless.yml.md
  docs/providers/google/guide/packaging.md
  docs/providers/kubeless/guide/packaging.md
  docs/providers/openwhisk/guide/packaging.md
  docs/providers/tencent/guide/packaging.md
  lib/configSchema.js
  lib/plugins/aws/provider.js
  lib/plugins/create/templates/aws-clojurescript-gradle/serverless.yml
  lib/plugins/create/templates/aws-go-dep/serverless.yml
  lib/plugins/create/templates/aws-go-mod/serverless.yml
  lib/plugins/create/templates/aws-go/serverless.yml
  lib/plugins/create/templates/aws-nodejs/serverless.yml
  lib/plugins/create/templates/aws-provided/serverless.yml
  lib/plugins/create/templates/aws-python/serverless.yml
  lib/plugins/create/templates/aws-python3/serverless.yml
  lib/plugins/create/templates/aws-ruby/serverless.yml
  lib/plugins/create/templates/azure-nodejs/serverless.yml
  lib/plugins/create/templates/azure-python/serverless.yml
  lib/plugins/create/templates/tencent-go/serverless.yml
  lib/plugins/create/templates/tencent-nodejs/serverless.yml
  lib/plugins/create/templates/tencent-python/serverless.yml
  lib/plugins/package/lib/packageService.js
  lib/plugins/package/package.js
Labels: bug/design, cat/packaging, deprecation, enhancement

#9193 test: Refactor test for `getRegion` for `aws` provider
  test/unit/lib/plugins/aws/provider.test.js
Labels: tests

#9195 feat(AWS HTTP API): Add support for AWS IAM authorization
  docs/providers/aws/events/http-api.md
  lib/plugins/aws/package/compile/events/httpApi.js
  test/unit/lib/plugins/aws/package/compile/events/httpApi.test.js
Labels: cat/aws-event-http-api, enhancement

#9201 test: Separate external API integration tests for API Gateway
  test/fixtures/apiGateway/index.js
  test/fixtures/apiGateway/serverless.yml
  test/integration/apiGateway.test.js
  test/integration/apiGatewayExternal.test.js
Labels: tests

#9202 test: Remove unnecessary CLI params in `integrationBasic.test.js`
  test/integrationBasic.test.js
Labels: tests

#9206 fix(AWS IAM): Support for CF functions for `provider.iam.role`
  docs/providers/aws/guide/iam.md
  lib/plugins/aws/package/compile/functions.js
  lib/plugins/aws/package/lib/mergeIamTemplates.js
  lib/plugins/aws/provider.js
  test/unit/lib/plugins/aws/package/compile/functions.test.js
  test/unit/lib/plugins/aws/package/lib/mergeIamTemplates.test.js
Labels: bug, cat/aws-iam

#9209 CLI: Fix deprecation message typo
  lib/cli/ensure-supported-command.js
Labels: refactor
