Repository serverless/serverless, pull requests merged in 2021-07, with the labels that each got.

#9666 feat(AWS Lambda): Add support for `SASL/PLAIN` auth to `kafka` event
  docs/providers/aws/events/kafka.md
  lib/plugins/aws/package/compile/events/kafka.js
  test/unit/lib/plugins/aws/package/compile/events/kafka.test.js
Labels: cat/aws-event-kafka, enhancement

#9678 fix(Telemetry): Properly handle not in service dir in credentials
  lib/cli/interactive-setup/aws-credentials.js
  test/unit/lib/cli/interactive-setup/aws-credentials.test.js
Labels: bug, cat/telemetry

#9644 refactor: Use `async` in `lib/plugins/package`
  lib/plugins/package/lib/packageService.js
  lib/plugins/package/lib/zipService.js
  lib/plugins/package/package.js
Labels: refactor

#9682 chore: Fix typo in read.js
  lib/configuration/read.js
Labels: cat/cli, refactor

#9687 refactor: Replace `fse.createWriteStream` with `fs.createWriteStream`
  lib/utils/eventuallyUpdate.js
Labels: refactor

#9679 Test: Cover `serverless-plugin-requirements` plugin
  .github/workflows/integrate.yml
  test/fixtures/programmatic/curated-plugins-python/_setup.js
  test/fixtures/programmatic/curated-plugins-python/handler.py
  test/fixtures/programmatic/curated-plugins-python/package.json
  test/fixtures/programmatic/curated-plugins-python/requirements.txt
  test/fixtures/programmatic/curated-plugins-python/serverless.yml
  test/integration/curated-plugins-python.test.js
Labels: cat/plugin, tests

#9690 refactor(Telemetry): Report `commandUsage` as object
  lib/cli/handle-error.js
  lib/cli/interactive-setup/index.js
  lib/utils/tokenize-exception.js
  scripts/serverless.js
  test/unit/lib/cli/interactive-setup/index.test.js
  test/unit/lib/utils/tokenize-exception.test.js
Labels: cat/telemetry, refactor

#9695 CLI: Recognize `--verbose` option in `info` command
  lib/cli/commands-schema/aws-service.js
Labels: bug, cat/cli

#9693 New deprecations logging mode
  docs/deprecations.md
  docs/providers/aws/guide/serverless.yml.md
  lib/Serverless.js
  lib/cli/handle-error.js
  lib/configSchema.js
  lib/utils/logDeprecation.js
  scripts/serverless.js
  test/unit/lib/utils/logDeprecation.test.js
Labels: cat/cli, enhancement

#9692 Ensure generation and related utils are sync
  lib/Serverless.js
  lib/classes/PluginManager.js
  lib/cli/handle-error.js
  lib/cli/render-version.js
  lib/cli/resolve-local-serverless-path.js
  lib/plugins/config.js
  lib/utils/eventuallyUpdate.js
  lib/utils/is-locally-installed.js
  lib/utils/npmPackage/isGlobal.js
  lib/utils/telemetry/generatePayload.js
  lib/utils/telemetry/index.js
  scripts/postinstall.js
  scripts/serverless.js
  test/unit/lib/cli/handle-error.test.js
  test/unit/lib/cli/resolve-local-serverless-path.test.js
  test/unit/lib/plugins/aws/provider.test.js
  test/unit/lib/utils/telemetry/generatePayload.test.js
  test/unit/lib/utils/telemetry/index.test.js
Labels: cat/telemetry, refactor

#9698 Variables: Drop old engine related deprecation
  lib/classes/Variables.js
  lib/configuration/variables/eventually-report-resolution-errors.js
  scripts/serverless.js
  test/unit/lib/classes/Variables.test.js
Labels: cat/variable, deprecation, refactor

#9701 Ensure to pass all steps with configured questions
  lib/cli/interactive-setup/index.js
Labels: bug, cat/telemetry

#9699 feat(Telemetry): Handle interruptions and persist telemetry data
  scripts/serverless.js
Labels: cat/telemetry, enhancement

#9714 Up AWS event pom version to pull in deserialization fix
  lib/plugins/aws/invokeLocal/runtimeWrappers/java/pom.xml
Labels: bug, cat/local-dev, runtime/java

#9716 Telemetry: Ensure no doubled reports in edge cases
  scripts/serverless.js
Labels: bug, cat/telemetry

#9721 Packaging: Validate `package.artifact` paths
  lib/plugins/package/lib/packageService.js
Labels: bug, cat/packaging

#9725 Packaging: Fix `package.artifact` validation for S3 urls
  lib/plugins/package/lib/packageService.js
Labels: bug, cat/packaging

#9728 docs: Adjust `${aws::accountId}` reference example
  docs/providers/aws/guide/variables.md
Labels: documentation

#9734 docs: Add `s3` config options to `serverless.yml.md`
  docs/providers/aws/guide/serverless.yml.md
Labels: documentation, enhancement

#9735 docs(AWS IAM): Fix invalid example
  docs/providers/aws/guide/iam.md
Labels: documentation

#9743 Upgrade `filesize` to v7
  package.json
Labels: refactor

#9615 feat(CLI): Automatically expand loaded env variables
  docs/environment-variables.md
  lib/cli/load-dotenv.js
  package.json
  test/unit/lib/Serverless.test.js
Labels: cat/cli, enhancement

#9747 Variables: In `ssm` source auto parse only object JSON notation
  lib/configuration/variables/sources/instance-dependent/get-ssm.js
  test/unit/lib/configuration/variables/sources/instance-dependent/get-ssm.test.js
Labels: bug, cat/variable

#9748 Allow to disable default export names
  docs/deprecations.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/index.js
  lib/plugins/aws/package/lib/addExportNameForOutputs.js
  lib/plugins/aws/provider.js
  test/unit/lib/plugins/aws/package/lib/addExportNameForOutputs.test.js
Labels: deprecation, enhancement

#9750 Test: Cover `serverless-plugin-typescript` plugin
  package.json
  test/fixtures/programmatic/curated-plugins/index-ts.ts
  test/fixtures/programmatic/curated-plugins/package.json
  test/integration/curated-plugins.test.js
Labels: tests

#9752 refactor: fix comment typo
  test/unit/lib/plugins/aws/lib/naming.test.js
Labels: tests

#9754 refactor: Replace `fse.unlink` with `fs.promises.unlink`
  lib/utils/telemetry/index.js
  test/unit/lib/cli/resolve-configuration-path.test.js
  test/unit/lib/configuration/read.test.js
  test/unit/lib/utils/telemetry/index.test.js
Labels: refactor

#9756 Fix `functions[]` validation (ignore `null` values)
  lib/classes/Service.js
  test/unit/lib/classes/Service.test.js
Labels: bug

#9755 Telemetry: Update notifications code documentation
  docs/telemetry.md
Labels: cat/telemetry, documentation

#9757 Test: Cover `serverless-step-functions` plugin
  test/fixtures/programmatic/curated-plugins/package.json
  test/integration/curated-plugins.test.js
Labels: tests

#9762 fix(Config Schema): Fix deprecationNotificationMode
  lib/configSchema.js
Labels: bug, cat/cli

#9761 fix(CLI Onboarding): Ensure credentials resolution before deploy
  lib/cli/interactive-setup/deploy.js
  test/unit/lib/cli/interactive-setup/deploy.test.js
Labels: bug, cat/cli-onboarding

#9764 docs: Improve the Getting started guide
  docs/getting-started.md
Labels: documentation

#9767 docs: Adjust spelling in Node SDK guide
  docs/guides/sdk/nodejs.md
Labels: documentation

#9768 refactor(Telemetry): Use `prompt-with-history`
  lib/cli/interactive-setup/aws-credentials.js
  lib/cli/interactive-setup/dashboard-login.js
  lib/cli/interactive-setup/dashboard-set-org.js
  lib/cli/interactive-setup/deploy.js
  lib/cli/interactive-setup/service.js
  package.json
  test/unit/lib/cli/interactive-setup/aws-credentials.test.js
  test/unit/lib/cli/interactive-setup/dashboard-set-org.test.js
  test/unit/lib/cli/interactive-setup/service.test.js
Labels: cat/cli-onboarding, enhancement

#9773 docs: Suggest `python3` template over `python2`
  docs/providers/aws/examples/hello-world/python/README.md
Labels: documentation

#9780 refactor: Replace `fse.readdir` with `fs.promises.readdir`
  lib/utils/telemetry/index.js
  scripts/pkg/upload/world.js
  test/unit/lib/utils/telemetry/index.test.js
Labels: refactor

#9786 docs: Add note about config validation to contributors docs
  CONTRIBUTING.md
Labels: documentation, enhancement

#9680 refactor: Use `async` in `lib/plugins/plugin`
  lib/plugins/plugin/install.js
  lib/plugins/plugin/lib/utils.js
  lib/plugins/plugin/list.js
  lib/plugins/plugin/search.js
  lib/plugins/plugin/uninstall.js
  test/unit/lib/plugins/plugin/lib/utils.test.js
Labels: refactor

#9770 feat(Variables): Accept case-insensitive strings in `strToBool`
  docs/providers/aws/guide/variables.md
  lib/configuration/variables/sources/str-to-bool.js
  test/unit/lib/configuration/variables/sources/str-to-bool.test.js
Labels: cat/variable, enhancement

#9790 Detect used variable sources
  lib/cli/handle-error.js
  lib/configuration/variables/resolve.js
  lib/utils/telemetry/generatePayload.js
  scripts/serverless.js
  test/unit/lib/configuration/variables/resolve.test.js
  test/unit/lib/utils/telemetry/generatePayload.test.js
Labels: cat/telemetry, enhancement
