Repository serverless/serverless, pull requests merged in 2021-09, with the labels that each got.

#9895 feat(AWS CloudFront): Support `behavior.CachePolicyId`
  docs/providers/aws/events/cloudfront.md
  lib/plugins/aws/package/compile/events/cloudFront.js
  test/unit/lib/plugins/aws/package/compile/events/cloudFront.test.js
Labels: enhancement, cat/aws-event-cloudfront

#9905 fix(AWS Lambda): Recognize `Fn::If` function for `environment`
  lib/plugins/aws/provider.js
  test/unit/lib/plugins/aws/package/compile/functions.test.js
Labels: bug, cat/lambda

#9906 docs: Improve title in SQS docs
  docs/providers/aws/events/sqs.md
Labels: documentation

#9884 fix(AWS CloudFront): Recognize `behavior.TrustedKeyGroups` in schema
  lib/plugins/aws/package/compile/events/cloudFront.js
Labels: bug

#8840 feat(AWS Lambda): Add support for `activemq` event
  docs/providers/aws/events/activemq.md
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/package/compile/events/activemq.js
  lib/plugins/aws/package/compile/events/kafka.js
  lib/plugins/aws/provider.js
  lib/plugins/index.js
  scripts/test/integration-setup/cloudformation.yml
  scripts/test/integration-setup/index.js
  test/fixtures/programmatic/functionActivemq/core.js
  test/fixtures/programmatic/functionActivemq/package.json
  test/fixtures/programmatic/functionActivemq/serverless.yml
  test/integration/aws/infra-dependent/activemq.test.js
  test/unit/lib/plugins/aws/package/compile/events/activemq.test.js
  test/utils/cloudformation.js
Labels: enhancement

#9908 test(AWS Lambda): Fix `activemq` integration test
  test/integration/aws/infra-dependent/activemq.test.js
Labels: tests

#9915 refactor: Replace `fse.access` with `fs.promises.access`
  lib/plugins/aws/invokeLocal/index.js
Labels: refactor

#9910 fix(AWS API Gateway): Ensure proper `RequestValidator` name
  lib/plugins/aws/package/compile/events/apiGateway/index.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/requestValidator.js
Labels: bug, cat/aws-event-api-gateway

#9603 docs: Add `invoke local` doc for `google` provider
  docs/providers/google/cli-reference/invoke-local.md
  docs/providers/google/cli-reference/login.md
  docs/providers/google/cli-reference/logs.md
  docs/providers/google/cli-reference/plugin-install.md
  docs/providers/google/cli-reference/plugin-list.md
  docs/providers/google/cli-reference/plugin-search.md
  docs/providers/google/cli-reference/plugin-uninstall.md
  docs/providers/google/cli-reference/print.md
Labels: documentation

#9914 feat: Do not retry AWS requests if the token has expired
  .gitignore
  lib/aws/request.js
  test/unit/lib/aws/request.test.js
Labels: enhancement, cat/aws-auth

#9930 Documentation: Improve `dotenv` setup instructions
  docs/environment-variables.md
Labels: documentation

#9892 feat(AWS Schedule): Allow multiple rate expressions in single event
  docs/providers/aws/events/schedule.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/compile/events/schedule.js
  test/fixtures/programmatic/schedule/core.js
  test/fixtures/programmatic/schedule/serverless.yml
  test/integration/aws/schedule.test.js
  test/unit/lib/plugins/aws/package/compile/events/schedule.test.js
Labels: enhancement, cat/aws-event-schedule

#9918 feat(AWS API Gateway): Support `enabled` for `apiKeys` config
  docs/providers/aws/events/apigateway.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js
  lib/plugins/aws/provider.js
  test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.test.js
Labels: enhancement, cat/aws-event-api-gateway

#9936 Support `error` hook to be triggered on command error
  lib/classes/PluginManager.js
Labels: enhancement

#9935 refactor: Replace `fse.readFile` with `fs.promises.readFile`
  lib/configuration/read.js
  lib/configuration/variables/sources/file.js
  lib/plugins/aws/invokeLocal/index.js
  lib/utils/fs/readFile.js
  scripts/test/integration-setup/index.js
  test/unit/lib/plugins/package/lib/packageService.test.js
  test/unit/lib/utils/fs/writeFile.test.js
  test/unit/lib/utils/fs/writeFileSync.test.js
  test/utils/integration.js
Labels: refactor

#9926 refactor: Use `getCompiledTemplateS3Suffix` from `provider.naming`
  lib/plugins/aws/deploy/lib/validateTemplate.js
Labels: refactor

#9903 feat(AWS EventBridge): Support `deadLetterQueue` and `retryPolicy`
  docs/providers/aws/events/event-bridge.md
  lib/plugins/aws/package/compile/events/eventBridge/index.js
  test/unit/lib/plugins/aws/package/compile/events/eventBridge/index.test.js
Labels: enhancement, cat/aws-event-event-bridge

#9934 feat(CLI): Introduce first iteration of modern logs for `deploy`
  lib/cli/handle-error.js
  lib/plugins/aws/deploy/index.js
  lib/plugins/aws/deploy/lib/checkForChanges.js
  lib/plugins/aws/deploy/lib/cleanupS3Bucket.js
  lib/plugins/aws/deploy/lib/createStack.js
  lib/plugins/aws/deploy/lib/extendedValidate.js
  lib/plugins/aws/deploy/lib/uploadArtifacts.js
  lib/plugins/aws/deploy/lib/validateTemplate.js
  lib/plugins/aws/info/display.js
  lib/plugins/aws/info/index.js
  lib/plugins/aws/lib/monitorStack.js
  lib/plugins/aws/lib/updateStack.js
  lib/plugins/deploy.js
  lib/plugins/package/lib/packageService.js
  lib/plugins/package/lib/zipService.js
  package.json
  test/unit/lib/plugins/aws/deploy/lib/checkForChanges.test.js
  test/unit/lib/plugins/aws/deploy/lib/extendedValidate.test.js
  test/unit/lib/plugins/aws/deploy/lib/uploadArtifacts.test.js
  test/unit/lib/plugins/aws/deploy/lib/validateTemplate.test.js
  test/unit/lib/plugins/aws/info/display.test.js
Labels: enhancement, cat/cli

#9938 docs: Clarify the differences between API Gateway versions
  docs/providers/aws/events/apigateway.md
  docs/providers/aws/events/http-api.md
Labels: documentation

#9909 fix(AWS API Gateway): Ensure consistent default for `cors` conf
  lib/plugins/aws/package/compile/events/apiGateway/index.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
  test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/validate.test.js
Labels: enhancement, cat/aws-event-api-gateway

#9937 refactor: Replace `_.pick` with native property assignment
  lib/plugins/aws/info/getApiKeyValues.js
  test/unit/lib/plugins/aws/info/getApiKeyValues.test.js
Labels: refactor

#9952 feat(CLI): First iteration of support for `verbose` mode in `deploy`
  lib/plugins/aws/deploy/index.js
  lib/plugins/aws/deploy/lib/cleanupS3Bucket.js
  lib/plugins/aws/deploy/lib/createStack.js
  lib/plugins/aws/deploy/lib/uploadArtifacts.js
  lib/plugins/aws/info/display.js
  lib/plugins/aws/lib/monitorStack.js
  lib/plugins/aws/lib/updateStack.js
  lib/plugins/package/lib/packageService.js
  lib/plugins/package/lib/zipService.js
Labels: enhancement, cat/cli

#9954 feat(CLI Onboarding): Switch to `httpApi`-based templates
  lib/cli/interactive-setup/service.js
Labels: enhancement, cat/cli-onboarding

#9948 refactor: Replace `_.flatMap` usage
  lib/classes/PluginManager.js
  lib/plugins/aws/invokeLocal/index.js
Labels: refactor

#9959 feat(CLI): Add timer to final command message in modern logs
  lib/classes/PluginManager.js
  lib/plugins/aws/deploy/index.js
  lib/plugins/aws/deploy/lib/checkForChanges.js
Labels: enhancement, cat/cli

#9960 feat(CLI): Add deprecation summary for modern logs
  lib/utils/logDeprecation.js
  package.json
Labels: enhancement, cat/cli

#9969 docs: Remove Pro and Enterprise references
  docs/getting-started.md
  docs/guides/cicd/best-practices.md
  docs/guides/cicd/custom-scripts.md
  docs/guides/cicd/faq.md
  docs/guides/cicd/notifications.md
  docs/guides/cicd/preview-deployments.md
  docs/guides/monitoring/README.md
  docs/guides/safeguards.md
Labels: documentation, cat/dashboard

#9979 Support `tumblingWindowInSeconds` for streaming events
  docs/providers/aws/events/streams.md
  lib/plugins/aws/package/compile/events/stream.js
  test/unit/lib/plugins/aws/package/compile/events/stream.test.js
Labels: enhancement, cat/aws-event-stream

#9994 CLI: Fix general help output when in context of AWS service
  scripts/serverless.js
Labels: bug, cat/cli

#9996 Leftover use of "pro dashboard" in README
  docs/README.md
Labels: documentation, cat/dashboard

#9997 Docs: Alibaba Cloud - fixed available events
  docs/providers/aliyun/guide/events.md
Labels: documentation

#9999 Plugins: Ensure to keep `options` as passed to plugins up to date
  lib/Serverless.js
  package.json
  scripts/serverless.js
Labels: bug, cat/plugin

#9968 Add overview documentation for Lambda events
  docs/providers/aws/events/README.md
  docs/providers/aws/guide/events.md
Labels: documentation

#10000 CLI: Modern logs for `deploy list` and `deploy list functions`
  lib/plugins/aws/deployList.js
  test/unit/lib/plugins/aws/deployList.test.js
Labels: refactor, cat/cli

#10001 CLI: Remove missing CLI options schema deprecation
  lib/cli/commands-schema/resolve-final.js
Labels: cat/plugin, deprecation, cat/cli

#10003 CLI: Revert from unconditional `.env` support
  lib/cli/conditionally-load-dotenv.js
Labels: deprecation, cat/cli

#10004 refactor: Bring back `_.flatMap` usage
  lib/plugins/aws/invokeLocal/index.js
Labels: refactor

#10007 docs: Removed duplicated paragraph
  docs/providers/aws/events/streams.md
Labels: documentation

#10023 AWS EventBridge: Fix `MaximumEventAgeInSecond` template reference
  lib/plugins/aws/package/compile/events/eventBridge/index.js
  test/unit/lib/plugins/aws/package/compile/events/eventBridge/index.test.js
Labels: bug, cat/aws-event-event-bridge

#10030 fix(AWS EventBridge): Ensure proper support for `deadLetterConfig`
  docs/providers/aws/events/event-bridge.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/compile/events/eventBridge/index.js
  test/unit/lib/plugins/aws/package/compile/events/eventBridge/index.test.js
Labels: bug, cat/aws-event-event-bridge
