Repository serverless/serverless, pull requests merged in 2021-02, with the labels that each got.

#8865 feat(AWS Lambda): Add ability to customize file for Dockerfile
  docs/providers/aws/guide/functions.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/provider.js
  test/fixtures/ecr/Dockerfile.dev
  test/unit/lib/plugins/aws/provider.test.js
Labels: cat/lambda-image, enhancement

#8863 docs: Update migration/deprecation dates
  docs/guides/profiles.md
Labels: cat/dashboard, documentation

#8868 Properly handle error if Java bridge is not present
  lib/plugins/aws/invokeLocal/index.js
Labels: bug, cat/local-dev, runtime/java

#8872 refactor: Use async in `lib/plugins/aws/lib`
  lib/plugins/aws/lib/monitorStack.js
  lib/plugins/aws/lib/setBucketName.js
  lib/plugins/aws/lib/updateStack.js
Labels: refactor

#8874 refactor: Use `async` in `compile/events/websockets`
  lib/plugins/aws/package/compile/events/websockets/index.js
  lib/plugins/aws/package/compile/events/websockets/lib/api.js
  lib/plugins/aws/package/compile/events/websockets/lib/authorizers.js
  lib/plugins/aws/package/compile/events/websockets/lib/deployment.js
  lib/plugins/aws/package/compile/events/websockets/lib/integrations.js
  lib/plugins/aws/package/compile/events/websockets/lib/permissions.js
  lib/plugins/aws/package/compile/events/websockets/lib/routes.js
  lib/plugins/aws/package/compile/events/websockets/lib/stage.js
  test/unit/lib/plugins/aws/package/compile/events/websockets/lib/api.test.js
  test/unit/lib/plugins/aws/package/compile/events/websockets/lib/authorizers.test.js
  test/unit/lib/plugins/aws/package/compile/events/websockets/lib/deployment.test.js
  test/unit/lib/plugins/aws/package/compile/events/websockets/lib/integrations.test.js
  test/unit/lib/plugins/aws/package/compile/events/websockets/lib/permissions.test.js
  test/unit/lib/plugins/aws/package/compile/events/websockets/lib/routes.test.js
Labels: refactor

#8881 Tests: Specify refactor of checkForChanges.js tests
  test/fixtures/checkForChanges/artifact.zip
  test/fixtures/checkForChanges/fn.js
  test/fixtures/checkForChanges/fnIndividually.js
  test/fixtures/checkForChanges/serverless.yml
  test/unit/lib/plugins/aws/deploy/lib/checkForChanges.test.js
Labels: cat/deployment, refactor, tests

#8894 feat(AWS Lambda): Add support for `nodejs14.x` runtime
  lib/plugins/aws/provider.js
Labels: enhancement

#8900 fix: Handle gently npm response errors
  lib/utils/eventuallyUpdate.js
Labels: bug

#8901 fix(AWS Deploy): Gracefully handle denied access to ecr
  lib/plugins/aws/lib/checkIfEcrRepositoryExists.js
  test/unit/lib/plugins/aws/remove/index.test.js
Labels: bug, cat/deployment

#8899 fix: Properly resolve local version
  lib/cli/eventually-list-version.js
  lib/cli/handle-error.js
  scripts/serverless.js
Labels: bug, cat/cli

#8871 refactor: Use `async/await` in `lib/plugins/aws`.
  lib/plugins/aws/configCredentials.js
  lib/plugins/aws/deployFunction.js
  lib/plugins/aws/deployList.js
  lib/plugins/aws/provider.js
  lib/plugins/aws/rollback.js
  lib/plugins/aws/rollbackFunction.js
Labels: refactor

#8875 refactor: Use `async/await` in `lib/plugins`.
  lib/plugins/aws/info/getApiKeyValues.js
  lib/plugins/aws/info/getResourceCount.js
  lib/plugins/aws/info/getStackInfo.js
  lib/plugins/aws/info/index.js
  lib/plugins/config.js
  lib/plugins/deploy.js
  lib/plugins/install.js
  lib/plugins/invoke.js
  lib/plugins/print.js
  lib/plugins/slstats.js
  lib/plugins/standalone.js
  test/unit/lib/plugins/install.test.js
  test/unit/lib/plugins/invoke.test.js
  test/unit/lib/plugins/slstats.test.js
Labels: refactor

#8908 fix(AWS Lambda): Ensure proper normalization of ecr repo name
  lib/plugins/aws/lib/naming.js
  test/unit/lib/plugins/aws/lib/naming.test.js
Labels: bug, cat/lambda-image

#8897 refactor: Use standalone `ServerlessError`.
  lib/classes/CLI.js
  lib/classes/ConfigSchemaHandler/index.js
  lib/classes/PluginManager.js
  lib/classes/Variables.js
  lib/plugins/aws/configCredentials.js
  lib/plugins/aws/customResources/index.js
  lib/plugins/aws/deploy/lib/checkForChanges.js
  lib/plugins/aws/deploy/lib/createStack.js
  lib/plugins/aws/deploy/lib/existsDeploymentBucket.js
  lib/plugins/aws/deploy/lib/extendedValidate.js
  lib/plugins/aws/deployFunction.js
  lib/plugins/aws/info/getStackInfo.js
  lib/plugins/aws/invoke.js
  lib/plugins/aws/invokeLocal/index.js
  lib/plugins/aws/lib/monitorStack.js
  lib/plugins/aws/lib/validate.js
  lib/plugins/aws/logs.js
  lib/plugins/aws/package/compile/events/alb/lib/validate.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlanKeys.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
  lib/plugins/aws/package/compile/events/cloudFront.js
  lib/plugins/aws/package/compile/events/cloudWatchEvent.js
  lib/plugins/aws/package/compile/events/cloudWatchLog.js
  lib/plugins/aws/package/compile/events/cognitoUserPool.js
  lib/plugins/aws/package/compile/events/eventBridge/index.js
  lib/plugins/aws/package/compile/events/httpApi.js
  lib/plugins/aws/package/compile/events/iotFleetProvisioning.js
  lib/plugins/aws/package/compile/events/s3/index.js
  lib/plugins/aws/package/compile/events/sns.js
  lib/plugins/aws/package/compile/events/websockets/lib/validate.js
  lib/plugins/aws/package/compile/functions.js
  lib/plugins/aws/package/lib/generateCoreTemplate.js
  lib/plugins/aws/provider.js
  lib/plugins/config.js
  lib/plugins/create/create.js
  lib/plugins/deploy.js
  lib/plugins/package/lib/packageService.js
  lib/plugins/package/lib/zipService.js
  lib/plugins/plugin/lib/utils.js
  lib/plugins/print.js
  lib/plugins/standalone.js
  test/unit/lib/Serverless.test.js
  test/unit/lib/classes/Error.test.js
  test/unit/lib/classes/PluginManager.test.js
  test/unit/lib/classes/Variables.test.js
  test/unit/lib/cli/handle-error.test.js
  test/unit/lib/plugins/aws/deploy/lib/checkForChanges.test.js
  test/unit/lib/plugins/aws/deploy/lib/createStack.test.js
  test/unit/lib/plugins/aws/invoke.test.js
  test/unit/lib/plugins/aws/lib/validate.test.js
  test/unit/lib/plugins/aws/package/compile/events/alb/index.test.js
  test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/validate.test.js
  test/unit/lib/plugins/config.test.js
Labels: refactor

#8914 feat(Templates): Update `aws-nodejs-typescript` for `nodejs14.x`
  lib/plugins/create/templates/aws-nodejs-typescript/.nvmrc
  lib/plugins/create/templates/aws-nodejs-typescript/package.json
  lib/plugins/create/templates/aws-nodejs-typescript/serverless.ts
  lib/plugins/create/templates/aws-nodejs-typescript/tsconfig.json
Labels: cat/template

#8869 refactor: Use `async/await` in `events/apiGateway`.
  lib/plugins/aws/package/compile/events/apiGateway/index.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/authorizers.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/cors.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/deployment.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/hack/disassociateUsagePlan.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/resources.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/stage.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlan.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlanKeys.js
  test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.test.js
  test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/authorizers.test.js
  test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/cors.test.js
  test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/deployment.test.js
  test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test.js
  test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.test.js
  test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/resources.test.js
  test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.test.js
  test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlan.test.js
  test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/usagePlanKeys.test.js
Labels: refactor

#8876 refactor: Use `async/await` in `lib/plugins/aws/invokeLocal`.
  lib/plugins/aws/invokeLocal/fixture/asyncHandlerWithError.js
  lib/plugins/aws/invokeLocal/fixture/asyncHandlerWithSuccess.js
  lib/plugins/aws/invokeLocal/index.js
Labels: refactor

#8923 Docs: Improve deprecations setup doc
  CONTRIBUTING.md
Labels: documentation

#8918 Properly resolve SHA for repo with slashes
  lib/plugins/aws/provider.js
  test/unit/lib/plugins/aws/provider.test.js
Labels: bug, cat/lambda-image

#8929 fix: aws-nodejs-typescript template issue where serverless.ts could not reference type definitions
  lib/plugins/create/templates/aws-nodejs-typescript/tsconfig.json
Labels: cat/template

#8701 feat(AWS IAM): Group IAM-related settings under `provider.iam`
  docs/deprecations.md
  docs/providers/aws/guide/iam.md
  lib/plugins/aws/package/lib/mergeIamTemplates.js
  lib/plugins/aws/provider.js
  lib/utils/report-deprecated-properties.js
  test/unit/lib/plugins/aws/deploy/lib/createStack.test.js
  test/unit/lib/plugins/aws/package/compile/functions.test.js
  test/unit/lib/plugins/aws/package/lib/mergeIamTemplates.test.js
  test/unit/lib/utils/report-deprecated-properties.test.js
Labels: cat/aws-iam, enhancement

#8939 refactor: Remove unneeded `split` in `getHttp`
  lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
Labels: refactor

#8945 fix: Ensure that `list-version` is invoked
  scripts/serverless.js
Labels: bug

#8948 AWS Deploy: Ensure to handle artifact stream read errors
  lib/plugins/aws/deploy/lib/uploadArtifacts.js
  test/unit/lib/plugins/aws/deploy/lib/uploadArtifacts.test.js
Labels: bug, cat/deployment

#8947 fix(Templates): Bring back `gitignore` to include in package
  .gitignore
  .npmignore
Labels: bug, cat/template

#8649 feat(AWS HTTP API): add 'disableDefaultEndpoint' boolean configuratio…
  lib/plugins/aws/package/compile/events/httpApi.js
  lib/plugins/aws/provider.js
  test/unit/lib/plugins/aws/package/compile/events/httpApi.test.js
Labels: cat/aws-event-http-api, enhancement

#8952 CLI: Ensure to support "_" in param names
  lib/cli/parse-args.js
  test/unit/lib/cli/parse-args.test.js
Labels: bug, cat/cli

#8961 fix(AWS Lambda): Throw verbose error when referencing invalid layer
  lib/plugins/aws/package/compile/functions.js
  test/unit/lib/plugins/aws/package/compile/functions.test.js
Labels: bug, cat/lambda

#8962 fix(Variables): Properly resolve vars if `prototype` in path
  lib/classes/Variables.js
  test/fixtures/variables/serverless.yml
  test/unit/lib/classes/Variables.test.js
Labels: bug, cat/variable

#8964 CLI: Ensure to recognize "-v" param as boolean in all cases
  lib/cli/resolve-input.js
  test/unit/lib/cli/resolve-input.test.js
Labels: bug, cat/cli

#8967 fix(Templates): Properly package `gradle-wrapper` into npm package
  lib/plugins/create/templates/aws-groovy-gradle/.gitignore
  lib/plugins/create/templates/aws-java-gradle/.gitignore
  lib/plugins/create/templates/aws-kotlin-jvm-gradle-kts/.gitignore
  lib/plugins/create/templates/aws-kotlin-jvm-gradle/.gitignore
Labels: bug, cat/template

#8970 Improve testing standalone and package artifacts
  .github/workflows/integrate.yml
  .github/workflows/publish.yml
Labels: cat/ci, enhancement

#8965 fix(AWS ALB): Conform to CF schema with multiple host header
  lib/plugins/aws/package/compile/events/alb/lib/listenerRules.js
  test/unit/lib/plugins/aws/package/compile/events/alb/index.test.js
  test/unit/lib/plugins/aws/package/compile/events/alb/lib/listenerRules.test.js
Labels: bug, cat/aws-event-alb

#8943 refactor: Remove `bluebird` from `lib/classes`
  lib/classes/PluginManager.js
  lib/classes/Utils.js
  lib/classes/Variables.js
  test/unit/lib/classes/PluginManager.test.js
  test/unit/lib/classes/Variables.test.js
Labels: refactor

#8972 refactor: Remove `bluebird` from `lib/utils`
  lib/utils/createFromTemplate.js
  lib/utils/downloadTemplateFromRepo.js
  lib/utils/fs/createZipFile.js
  lib/utils/open.js
  lib/utils/yamlAstParser.js
  test/utils/kinesis.js
Labels: refactor

#8973 refactor: Remove `bluebird` from top-level `lib/plugins`
  lib/plugins/config.js
  lib/plugins/deploy.js
  lib/plugins/install.js
  lib/plugins/invoke.js
  lib/plugins/print.js
  test/unit/lib/plugins/config.test.js
  test/unit/lib/plugins/deploy.test.js
  test/unit/lib/plugins/invoke.test.js
Labels: refactor

#8978 CLI: Fix resolution of empty valued params as `param=`
  lib/cli/parse-args.js
  test/unit/lib/cli/parse-args.test.js
Labels: bug, cat/cli

#8979 fix: Correctly define print hook
  lib/plugins/print.js
  test/unit/lib/plugins/print.test.js
Labels: bug

#8980 Display function versioning related deprecation only when some functions are configured
  lib/plugins/aws/package/compile/functions.js
Labels: bug, cat/lambda

#8986 docs: Fix typo in deprecation docs for `iam` properties
  docs/deprecations.md
Labels: documentation

#8968 Typescript template support for paths
  lib/plugins/create/templates/aws-nodejs-typescript/README.md
  lib/plugins/create/templates/aws-nodejs-typescript/package.json
  lib/plugins/create/templates/aws-nodejs-typescript/serverless.ts
  lib/plugins/create/templates/aws-nodejs-typescript/src/functions/hello/index.ts
  lib/plugins/create/templates/aws-nodejs-typescript/src/libs/handlerResolver.ts
  lib/plugins/create/templates/aws-nodejs-typescript/tsconfig.json
  lib/plugins/create/templates/aws-nodejs-typescript/tsconfig.paths.json
  lib/plugins/create/templates/aws-nodejs-typescript/webpack.config.js
Labels: cat/template, enhancement

#8920 Update docs to add default org provider for dashboard
  docs/guides/providers.md
Labels: cat/dashboard, documentation

#8991 ci: Properly resolve package version generated by npm pack
  .github/workflows/publish.yml
Labels: cat/ci

#8913 refactor: aws checkForChanges tests for cloudwatch logs use run-serve…
  lib/plugins/aws/deploy/lib/checkForChanges.js
  test/unit/lib/plugins/aws/deploy/lib/checkForChanges.test.js
Labels: cat/deployment, refactor, tests

#8975 Strip null properties from final CloudFormation template
  docs/providers/aws/guide/resources.md
  lib/plugins/aws/package/index.js
  lib/plugins/aws/package/lib/stripNullPropsFromTemplateResources.js
  test/unit/lib/plugins/aws/package/lib/stripNullPropsFromTemplateResources.test.js
Labels: cat/deployment

#8437 feat(AWS EventBridge): Support for using native CloudFormation
  docs/deprecations.md
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/package/compile/events/eventBridge/index.js
  lib/plugins/aws/package/compile/events/eventBridge/utils.js
  lib/plugins/aws/provider.js
  test/fixtures/eventBridge/core.js
  test/integration/eventBridge.test.js
  test/unit/lib/plugins/aws/lib/naming.test.js
  test/unit/lib/plugins/aws/package/compile/events/eventBridge/index.test.js
Labels: cat/aws-event-event-bridge, enhancement, help wanted

#9000 Variables: Ensure vars are parsed in address followed by source
  lib/configuration/variables/parse.js
  test/unit/lib/configuration/variables/parse.test.js
Labels: bug, cat/variable

#8997 CLI: Recognize "-s" as "--stage" alias, and other common params
  lib/cli/resolve-input.js
  test/unit/lib/cli/resolve-input.test.js
Labels: bug, cat/cli

#8992 Variables: Communicate not accessible "provider" and "provider.stage" properties
  scripts/serverless.js
  test/unit/scripts/serverless.test.js
Labels: cat/variable, enhancement

#9008 Variables: Report with "null" not existing "file" sources
  lib/configuration/variables/sources/file.js
  test/unit/lib/configuration/variables/sources/file.test.js
  test/unit/lib/configuration/variables/sources/fixture/file-function-errored-non-error.js
  test/unit/lib/configuration/variables/sources/fixture/file-function-errored.js
  test/unit/lib/configuration/variables/sources/fixture/file-promise-rejected-non-error.js
  test/unit/lib/configuration/variables/sources/fixture/file-promise-rejected.js
  test/unit/lib/configuration/variables/sources/fixture/file-property-function-errored-non-error.js
  test/unit/lib/configuration/variables/sources/fixture/file-property-function-errored.js
Labels: bug, cat/variable

#9011 Variables: Fix infinite loop parsing issue
  lib/configuration/variables/parse.js
  test/unit/lib/configuration/variables/parse.test.js
Labels: bug, cat/variable

#7619 feat(AWS API Gateway): Allow reuse and customization of schema models
  docs/deprecations.md
  docs/providers/aws/events/apigateway.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/package/compile/events/apiGateway/index.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/requestValidator.js
  lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js
  lib/plugins/aws/provider.js
  test/fixtures/requestSchema/dummySchema.json
  test/fixtures/requestSchema/serverless.yml
  test/fixtures/requestSchema/target.js
  test/unit/lib/plugins/aws/lib/naming.test.js
  test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test.js
  test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/requestValidator.test.js
Labels: cat/aws-event-api-gateway, enhancement, help wanted

#9023 Prevent reader confusion
  docs/providers/aws/guide/variables.md
Labels: documentation
