Repository serverless/serverless, pull requests merged in 2022-05, with the labels that each got.

#11027 docs: Fix URL in documentation menu
  docs/menu.json
Labels: documentation

#10875 [Docs] Add maximumRetryAttempts to AWS guide
  docs/providers/aws/guide/serverless.yml.md
Labels: documentation

#11028 docs: Change page title with valid YAML
  docs/tutorial.md
Labels: documentation

#10931 feat(AWS Websocket): Allow propagating tags to Websocket APIGW
  docs/deprecations.md
  docs/providers/aws/events/websocket.md
  lib/plugins/aws/package/compile/events/websockets/lib/api.js
  lib/plugins/aws/provider.js
  test/unit/lib/plugins/aws/package/compile/events/websockets/index.test.js
Labels: enhancement, cat/aws-event-websocket

#11036 docs: Improve and reword the "Concepts" page
  docs/providers/aws/guide/intro.md
  docs/providers/aws/guide/services.md
Labels: documentation

#11044 Add Console integration procedure to `README`
  README.md
Labels: documentation

#11035 Update tutorial.md
  docs/tutorial.md
Labels: documentation

#11049 feat(AWS Lambda): Add support for `nodejs16.x` runtime
  lib/plugins/aws/provider.js
Labels: enhancement

#11057 docs: Replace Gitter links with Slack
  docs/providers/aliyun/README.md
  docs/providers/aliyun/cli-reference/README.md
  docs/providers/aliyun/events/README.md
  docs/providers/aliyun/guide/README.md
  docs/providers/aws/cli-reference/README.md
  docs/providers/aws/events/README.md
  docs/providers/aws/examples/README.md
  docs/providers/azure/cli-reference/README.md
  docs/providers/azure/events/README.md
  docs/providers/azure/examples/README.md
  docs/providers/azure/guide/README.md
  docs/providers/cloudflare/cli-reference/README.md
  docs/providers/cloudflare/events/README.md
  docs/providers/cloudflare/guide/README.md
  docs/providers/fn/cli-reference/README.md
  docs/providers/fn/events/README.md
  docs/providers/fn/guide/README.md
  docs/providers/google/cli-reference/README.md
  docs/providers/google/events/README.md
  docs/providers/google/examples/README.md
  docs/providers/google/guide/README.md
  docs/providers/kubeless/cli-reference/README.md
  docs/providers/kubeless/events/README.md
  docs/providers/kubeless/guide/README.md
  docs/providers/kubeless/guide/debugging.md
  docs/providers/openwhisk/cli-reference/README.md
  docs/providers/openwhisk/events/README.md
  docs/providers/openwhisk/examples/README.md
  docs/providers/openwhisk/guide/README.md
  docs/providers/spotinst/guide/README.md
Labels: documentation

#11066 feat(AWS S3): Support `forceDeploy` setting
  docs/providers/aws/events/s3.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/compile/events/s3/index.js
  test/unit/lib/plugins/aws/package/compile/events/s3/index.test.js
Labels: bug, cat/aws-event-s3

#11069 fix(AWS Lambda): Ensure proper `DependsOn` settings when `url: true`
  lib/plugins/aws/package/compile/functions.js
  test/unit/lib/plugins/aws/package/compile/functions.test.js
Labels: bug, cat/lambda

#11076 refactor(AWS Lambda): Recognize all supported log retention days
  lib/plugins/aws/provider.js
Labels: enhancement, cat/lambda

#11060 feat(AWS MSK): Add support for SASL/SCRAM authentication
  docs/providers/aws/events/msk.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/compile/events/msk/index.js
  test/unit/lib/plugins/aws/package/compile/events/msk/index.test.js
Labels: enhancement, cat/aws-event-msk

#11079 docs: Document the HTTP API URL output
  docs/providers/aws/events/http-api.md
Labels: documentation

#11090 docs: Mention `patterns` instead of `exclude` in layers.md
  docs/providers/aws/guide/layers.md
Labels: documentation

#11094 Console: Improve user error message
  lib/classes/console.js
Labels: refactor, cat/console

#11105 refactor(Telemetry): Recognize `isUsingCompose`
  lib/utils/telemetry/generate-payload.js
  test/unit/lib/utils/telemetry/generate-payload.test.js
Labels: refactor

#11100 fix(AWS Deploy): Ensure to only remove specific stage deploy artifacts
  lib/plugins/aws/deploy/lib/check-for-changes.js
  test/unit/lib/plugins/aws/deploy/lib/check-for-changes.test.js
Labels: bug

#11106 Console: Upgrade `@serverless/aws-lambda-otel-extension`
  lib/classes/console.js
  lib/plugins/aws/lib/upload-zip-file.js
Labels: refactor, cat/console
