Repository serverless/serverless, pull requests merged in 2022-08, with the labels that each got.

#11261 docs: Improve `RELEASE_PROCESS.md`
  RELEASE_PROCESS.md
Labels: documentation

#11312 Refactor test/utils with Async
  test/utils/api-gateway.js
  test/utils/cloudformation.js
  test/utils/cognito.js
  test/utils/dynamodb.js
  test/utils/event-bridge.js
  test/utils/iot.js
  test/utils/kinesis.js
  test/utils/misc.js
  test/utils/s3.js
  test/utils/sns.js
  test/utils/sqs.js
  test/utils/websocket.js
Labels: refactor, tests

#11324 docs: Fix typo in documentation
  docs/guides/monitoring/README.md
Labels: documentation

#11338 docs: Default to nodejs14.x in AWS docs
  docs/providers/aws/cli-reference/print.md
  docs/providers/aws/events/apigateway.md
  docs/providers/aws/events/websocket.md
  docs/providers/aws/guide/credentials.md
  docs/providers/aws/guide/functions.md
  docs/providers/aws/guide/services.md
  docs/providers/aws/guide/variables.md
  docs/providers/azure/guide/serverless.yml.md
Labels: documentation

#11345 feat(AWS Lambda): Add support for consumer group ID to kafka event
  docs/providers/aws/events/kafka.md
  docs/providers/aws/events/msk.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/compile/events/kafka.js
  lib/plugins/aws/package/compile/events/msk/index.js
  test/unit/lib/plugins/aws/package/compile/events/kafka.test.js
  test/unit/lib/plugins/aws/package/compile/events/msk/index.test.js
Labels: enhancement
