Repository serverless/serverless, pull requests merged in 2022-07, with the labels that each got.

#11203 feat(AWS Local Invocation): Support Node handlers with `.cjs` extension
  lib/plugins/aws/invoke-local/index.js
  test/fixtures/programmatic/invocation/async-cjs.cjs
  test/fixtures/programmatic/invocation/serverless.yml
  test/unit/lib/plugins/aws/invoke-local/index.test.js
Labels: enhancement, cat/local-dev

#11209 docs: Minor changes to `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: documentation

#11212 feat(AWS Local Invocation): Support Node handlers that are ECMAScript modules
  lib/plugins/aws/invoke-local/index.js
  package.json
  test/fixtures/programmatic/invocation/esm/async-esm.js
  test/fixtures/programmatic/invocation/esm/package.json
  test/fixtures/programmatic/invocation/serverless.yml
  test/unit/lib/plugins/aws/invoke-local/index.test.js
Labels: enhancement, cat/local-dev

#11220 Console: Report command which originated login operation
  commands/login.js
  lib/cli/interactive-setup/console-login.js
  lib/commands/login/console.js
Labels: refactor, cat/console

#11217 fix(AWS Deploy): Improve vague S3-related access errors
  lib/plugins/aws/deploy-list.js
  lib/plugins/aws/deploy/lib/check-for-changes.js
  lib/plugins/aws/deploy/lib/cleanup-s3-bucket.js
  lib/plugins/aws/lib/check-if-bucket-exists.js
  lib/plugins/aws/remove/lib/bucket.js
  lib/plugins/aws/rollback.js
  test/unit/lib/plugins/aws/deploy/index.test.js
  test/unit/lib/plugins/aws/deploy/lib/check-for-changes.test.js
  test/unit/lib/plugins/aws/remove/index.test.js
  test/unit/lib/plugins/aws/rollback.test.js
Labels: cat/deployment

#11228 minor typo in example
  docs/deprecations.md
Labels: documentation

#11235 Console: Keep currently attached layers with `function deploy`
  lib/plugins/aws/deploy-function.js
  test/unit/lib/classes/console.test.js
Labels: bug, cat/layers, cat/console

#11236 Console: Rely on Console ready layers pre-published to AWS
  lib/classes/console.js
  lib/plugins/aws/deploy-function.js
  lib/plugins/aws/deploy/index.js
  lib/plugins/aws/deploy/lib/upload-artifacts.js
  lib/plugins/aws/info/get-stack-info.js
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/package/compile/functions.js
  lib/plugins/aws/package/compile/layers.js
  lib/plugins/aws/package/lib/save-service-state.js
  lib/plugins/aws/package/lib/validate-template.js
  lib/plugins/aws/rollback.js
  lib/plugins/package/lib/package-service.js
  lib/utils/telemetry/generate-payload.js
  test/unit/lib/classes/console.test.js
Labels: enhancement, cat/console

#11223 feat(AWS HTTP API): Use the default API Gateway timeout of 30s
  docs/providers/aws/events/http-api.md
  lib/plugins/aws/package/compile/events/http-api.js
  test/unit/lib/plugins/aws/package/compile/events/http-api.test.js
Labels: cat/aws-event-http-api

#11270 docs: Add a "Getting Started" section to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#11282 docs: Remove link to the serverless survey
  docs/menu-builder.html
Labels: documentation

#11277 refactor(AWS CloudFormation) Add AWS SDK logging for custom resources
  lib/plugins/aws/custom-resources/resources/utils.js
Labels: enhancement

#11201 feat(AWS Cognito): Add Support for Custom Sender Triggers
  docs/providers/aws/events/cognito-user-pool.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/custom-resources/resources/cognito-user-pool/lib/user-pool.js
  lib/plugins/aws/package/compile/events/cognito-user-pool.js
  test/fixtures/programmatic/cognito-user-pool/core.js
  test/fixtures/programmatic/cognito-user-pool/serverless.yml
  test/integration/aws/cognito-user-pool.test.js
  test/unit/lib/plugins/aws/package/compile/events/cognito-user-pool.test.js
Labels: bug, cat/aws-event-cognito

#11272 refactor: Replace `_.flatMap` with `Array.prototype.flatMap`
  lib/cli/commands-schema/resolve-final.js
  lib/plugins/aws/invoke-local/index.js
  lib/plugins/aws/package/compile/events/api-gateway/lib/hack/disassociate-usage-plan.js
Labels: refactor

#11271 refactor: Replace `_.flatten` with `Array.prototype.flat`
  lib/plugins/aws/deploy/lib/check-for-changes.js
  lib/plugins/aws/metrics.js
  lib/plugins/aws/package/compile/events/api-gateway/lib/api-keys.js
  lib/plugins/aws/package/compile/events/websockets/lib/deployment.js
  lib/plugins/aws/utils/get-s3-objects-from-stacks.js
Labels: refactor

#11279 Removing selfReferences
  lib/plugins/aws/deploy/lib/extended-validate.js
  lib/plugins/aws/package/lib/save-service-state.js
  lib/plugins/aws/utils/find-references.js
  test/unit/lib/plugins/aws/package/lib/save-service-state.test.js
  test/unit/lib/plugins/aws/utils/find-references.test.js
Labels: refactor

#11294 docs: Minor `CONTRIBUTING.md` adjustments
  CONTRIBUTING.md
Labels: documentation

#11299 Variables: Fix handling of parallel resolution of same variable
  lib/configuration/variables/resolve.js
  test/unit/lib/configuration/variables/resolve.test.js
Labels: bug, cat/variable

#11292 docs: Small adjustments to `test/README.md`
  test/README.md
Labels: documentation

#11293 test: Remove obsolete template tests
  Dockerfile
  docker-compose.yml
  test/README.md
  test/templates/integration-test-template
  test/templates/test-all-templates
Labels: tests
