Repository serverless/serverless, pull requests merged in 2022-10, with the labels that each got.

#11421 Update Docs for Allowed CloudFront Lambda@Edge Runtimes
  docs/providers/aws/events/cloudfront.md
Labels: documentation

#11429 docs: Fix note about -v flag
  docs/guides/upgrading-v3.md
Labels: documentation

#11453 fix: Set API gateway timeout to 30 seconds by default
  lib/plugins/aws/package/compile/events/http-api.js
  test/unit/lib/plugins/aws/package/compile/events/http-api.test.js
Labels: bug, cat/aws-event-http-api

#11470 Update credentials.md
  docs/providers/aws/guide/credentials.md
Labels: documentation

#11461 feat: Extend AWS provider schema to support Fn::ToJsonString in environment variable
  lib/plugins/aws/provider.js
Labels: enhancement

#11490 Console: Ensure to always deploy CF stack to `us-east-1` region
  lib/cli/interactive-setup/utils.js
Labels: bug
