Repository serverless/serverless, pull requests merged in 2022-04, with the labels that each got.

#10814 feat(AWS RabbitMQ): Support `virtualHost`
  docs/providers/aws/events/rabbitmq.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/compile/events/rabbitmq.js
  test/unit/lib/plugins/aws/package/compile/events/rabbitmq.test.js
Labels: enhancement

#10922 feat(CLI Onboarding): Support all runtimes for dashboard
  lib/cli/interactive-setup/dashboard-set-org.js
  package.json
Labels: enhancement, cat/cli-onboarding

#10933 refactor(CLI): Fix typos in `create` CLI messages
  lib/plugins/create/create.js
Labels: refactor

#10936 feat(AWS Lambda): Add support for function URLs
  docs/providers/aws/guide/functions.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/info/display.js
  lib/plugins/aws/info/get-stack-info.js
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/package/compile/functions.js
  lib/plugins/aws/provider.js
  lib/utils/telemetry/generate-payload.js
  package.json
  test/integration/aws/function-url.test.js
  test/unit/lib/plugins/aws/info/display.test.js
  test/unit/lib/plugins/aws/lib/naming.test.js
  test/unit/lib/plugins/aws/package/compile/functions.test.js
  test/unit/lib/utils/telemetry/generate-payload.test.js
Labels: enhancement, cat/lambda

#10940 fix(AWS API Gateway): Correctly construct resource name for schema
  lib/plugins/aws/lib/naming.js
  test/unit/lib/plugins/aws/lib/naming.test.js
Labels: bug, cat/aws-event-api-gateway

#10942 fix(CLI): Do not attempt to resolve full config for `login`
  scripts/serverless.js
Labels: bug, cat/cli

#10949 Variables: Ensure support for promise properties at `file` source
  lib/configuration/variables/sources/file.js
  test/unit/lib/configuration/variables/sources/file.test.js
  test/unit/lib/configuration/variables/sources/fixture/file-property-promise.js
Labels: bug, cat/variable

#10961 docs: Add Lambda Function URLs resource reference
  docs/providers/aws/guide/resources.md
Labels: documentation

#10966 refactor(Telemetry): Ensure to pass unique id with events
  lib/utils/telemetry/index.js
  test/unit/lib/utils/telemetry/index.test.js
Labels: refactor, cat/telemetry

#10962 fix(AWS Local Invocation): Ensure env vars resolve for docker
  lib/plugins/aws/invoke-local/index.js
Labels: bug, cat/local-dev

#10973 test: `runServerless`-based tests for "Version hash resolution"
  test/unit/lib/plugins/aws/package/compile/functions.test.js
Labels: refactor

#10956 feat(AWS Websocket): Add ability to configure log format and types
  docs/providers/aws/events/websocket.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/compile/events/websockets/lib/stage.js
  lib/plugins/aws/provider.js
  test/unit/lib/plugins/aws/package/compile/events/websockets/lib/stage.test.js
Labels: enhancement, cat/aws-event-websocket

#10984 Handle `@serverless/compose` install in non-interactive
  lib/cli/run-compose.js
Labels: enhancement

#11002 AWS Local Invocation: Improve debugabilty of Python invocations
  lib/plugins/aws/invoke-local/index.js
Labels: refactor, cat/local-dev, runtime/python

#11004 docs: Use `!Ref LambdaLayer` instead of { Ref: LambdaLayer }
  docs/providers/aws/guide/layers.md
Labels: documentation

#11018 fix: Allow S3 event rule prefix and suffix to use CF functions
  lib/plugins/aws/package/compile/events/s3/index.js
  test/unit/lib/plugins/aws/package/compile/events/s3/index.test.js
Labels: bug, cat/config-schema

#11017 feat(CLI): Do not run `compose` for non-service commands
  lib/cli/triage.js
  test/unit/lib/cli/triage/index.test.js
Labels: enhancement, cat/cli
