Repository serverless/serverless, pull requests merged in 2022-03, with the labels that each got.

#10776 feat(Variables): Add support for `csj` in `file` source
  lib/configuration/variables/sources/file.js
  test/unit/lib/configuration/variables/sources/file.test.js
  test/unit/lib/configuration/variables/sources/fixture/file.cjs
Labels: enhancement, cat/variable

#10777 refactor(Console): Support login with Console
  lib/cli/commands-schema/no-service.js
  lib/cli/interactive-setup/dashboard-login.js
  lib/cli/interactive-setup/utils.js
  package.json
Labels: cat/console

#10779 feat(CLI Onboarding): Support `--console` flag
  lib/cli/commands-schema/no-service.js
  lib/cli/interactive-setup/dashboard-login.js
  lib/cli/interactive-setup/dashboard-set-org.js
  lib/cli/interactive-setup/utils.js
  test/fixtures/programmatic/aws-loggedin-console-service/.serverlessrc
  test/fixtures/programmatic/aws-loggedin-console-service/serverless.yml
  test/unit/lib/cli/interactive-setup/dashboard-set-org.test.js
Labels: enhancement, cat/console

#10784 fix(CLI Onboarding): Ensure variables resolution for templates
  lib/cli/interactive-setup/deploy.js
Labels: bug, cat/cli-onboarding

#10786 refactor(Telemetry): Rely on direct evaluation of `isTtyTerminal`
  lib/utils/telemetry/generate-payload.js
  package.json
Labels: cat/telemetry

#10796 fix: Properly move directories across filesystems
  lib/utils/fs/safe-move-file.js
Labels: bug

#10803 docs: Fix `schemas` documentation following v3 release
  docs/providers/aws/guide/serverless.yml.md
Labels: documentation

#10798 refactor(AWS Lambda): Support `provisionedConcurrency` set to `0`
  lib/plugins/aws/provider.js
Labels: enhancement, cat/lambda

#10810 fix(Telemetry): Ensure excluding `shouldSendTelemetry` from payload
  scripts/serverless.js
Labels: bug, cat/telemetry

#10802 docs: Rename menu to "Provider References"
  docs/README.md
  docs/providers/README.md
Labels: documentation

#10835 Console: Communicate new token implications with verbose mode
  lib/classes/console.js
Labels: refactor, cat/console

#10832 fix(AWS Local Invocation): Remove log4j dependency from java wrapper
  lib/plugins/aws/invoke-local/runtime-wrappers/java/pom.xml
Labels: bug, cat/local-dev

#10830 docs: Fix incorrect `apiKeys` example
  docs/providers/aws/guide/serverless.yml.md
Labels: documentation

#10837 fix(AWS Kafka): Allow usage of Server Root CA without client TLS auth
  lib/plugins/aws/package/compile/events/kafka.js
  test/unit/lib/plugins/aws/package/compile/events/kafka.test.js
Labels: bug, cat/aws-event-kafka

#10846 fix(CLI): Ensure proper resolution of options for service commands
  lib/cli/commands-schema/aws-service.js
  lib/cli/commands-schema/no-service.js
  lib/cli/commands-schema/service.js
  lib/cli/resolve-input.js
  test/unit/scripts/serverless.test.js
Labels: bug, cat/cli

#10851 docs: Fix markdown issue in `functions.md`
  docs/providers/aws/guide/functions.md
Labels: documentation

#10853 Standalone: Ensure error in China upload don't break GitHub upload
  scripts/pkg/upload/index.js
Labels: bug, cat/standalone

#10860 Console: Upgrade otel extension & fix packaging
  lib/classes/console.js
Labels: bug, refactor, cat/console

#10869 Console: Deployment bucket resolution fixes
  lib/classes/console.js
  test/unit/lib/classes/console.test.js
Labels: bug, cat/console

#10877 feat(AWS Lambda): Recognize `Fn::If` for properties of `vpc`
  lib/plugins/aws/provider.js
  test/unit/lib/plugins/aws/package/compile/functions.test.js
Labels: enhancement, cat/config-schema

#10878 feat(AWS Lambda): Support `logRetentionInDays` per function
  docs/providers/aws/guide/functions.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/lib/merge-iam-templates.js
  lib/plugins/aws/provider.js
  test/unit/lib/plugins/aws/package/lib/merge-iam-templates.test.js
Labels: enhancement, cat/lambda

#10845 feat(AWS Lambda): Support `Ref` for `destinations` properties
  docs/providers/aws/guide/functions.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/compile/functions.js
  lib/plugins/aws/provider.js
  test/unit/lib/plugins/aws/package/compile/functions.test.js
Labels: enhancement, cat/lambda

#10896 docs: Fix typo in `docs/guides/providers.md`
  docs/guides/providers.md
Labels: documentation

#10901 feat(AWS Lambda): Support `ephemeralStorageSize`
  docs/providers/aws/guide/functions.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/compile/functions.js
  lib/plugins/aws/provider.js
  test/unit/lib/plugins/aws/package/compile/functions.test.js
Labels: enhancement, cat/lambda

#10892 docs: Default of `configValidationMode` option
  docs/configuration-validation.md
Labels: documentation

#10908 AWS Deploy: Ensure no internal dependency on `console`
  lib/plugins/aws/info/get-stack-info.js
Labels: refactor, cat/deployment

#10903 fix(AWS Deploy): Apply stack policy after executing change sets
  lib/plugins/aws/lib/update-stack.js
  test/unit/lib/plugins/aws/deploy/index.test.js
Labels: bug, cat/deployment

#10888 fix(AWS Local Invocation): Ensure package before resolving runtime
  lib/plugins/aws/invoke-local/index.js
Labels: needs feedback
