Repository serverless/serverless, pull requests merged in 2022-11, with the labels that each got.

#11501 Console: Ensure errorneus resolution of url does not break deployments
  lib/plugins/aws/info/display.js
Labels: bug, cat/console

#11504 Fixed docs as `yarn-*.log` is the default exclude file for `package.patterns`
  docs/providers/aws/guide/packaging.md
Labels: documentation

#11506 Avoid null error of package
  lib/plugins/package/package.js
Labels: bug

#11535 fix(sec): upgrade com.fasterxml.jackson.core:jackson-databind to 2.14.0-rc1
  lib/plugins/aws/invoke-local/runtime-wrappers/java/pom.xml
Labels: enhancement, cat/local-dev, cat/security
