Repository serverless/serverless, pull requests merged in 2022-12, with the labels that each got.

#11593 Support relative paths in `import-esm` util
  lib/utils/import-esm.js
Labels: refactor

#11600 Test: Cover custom variable sources
  test/fixtures/programmatic/plugin/custom-variable-source.js
  test/unit/scripts/serverless.test.js
Labels: tests, cat/variable

#11608 Refactor: Remove no longer applicable setting
  scripts/serverless.js
  test/unit/lib/configuration/variables/sources/instance-dependent/get-aws.test.js
  test/unit/lib/configuration/variables/sources/instance-dependent/get-sls.test.js
Labels: refactor

#11576 feat: allow configuration of SnapStart in properties of AWS Lambda Fu…
  docs/providers/aws/guide/functions.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/deploy-function.js
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/package/compile/functions.js
  lib/plugins/aws/provider.js
  test/unit/lib/plugins/aws/package/compile/functions.test.js
Labels: enhancement, cat/lambda

#11558 11034 extend configuration
  docs/guides/plugins/custom-configuration.md
  docs/guides/plugins/extending-configuration.md
  docs/menu.json
  lib/serverless.js
  scripts/serverless.js
  test/fixtures/programmatic/plugin/extend-config-plugin/index.js
  test/unit/lib/serverless.test.js
Labels: enhancement, cat/variable
