Repository serverless/serverless, pull requests merged in 2022-01, with the labels that each got.

#10428 Various wording improvements
  docs/deprecations.md
  docs/getting-started.md
  lib/cli/interactive-setup/aws-credentials.js
  lib/cli/interactive-setup/utils.js
  scripts/serverless.js
  test/unit/lib/cli/interactive-setup/aws-credentials.test.js
Labels: documentation

#10431 docs: Stage parameters
  docs/guides/cicd/README.md
  docs/guides/dashboard.md
  docs/guides/parameters.md
  docs/guides/plugins/README.md
  docs/providers/aws/guide/variables.md
Labels: documentation

#10453 docs: Add stage parameters to the serverless.yml reference
  docs/providers/aws/guide/serverless.yml.md
Labels: documentation

#10452 fix(Config Schema): Address invalid schema definitions
  lib/plugins/aws/package/compile/events/cloudFront.js
  lib/plugins/aws/package/compile/events/eventBridge/index.js
  lib/plugins/aws/provider.js
Labels: bug, cat/config-schema

#10435 Add forceDeploy property in Cognito User Pools
  docs/providers/aws/events/cognito-user-pool.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/compile/events/cognitoUserPool.js
  test/unit/lib/plugins/aws/package/compile/events/cognitoUserPool.test.js
Labels: enhancement, cat/aws-event-cognito

#10416 docs: Fix long lines in code examples
  docs/providers/aws/cli-reference/config-credentials.md
  docs/providers/aws/cli-reference/config.md
  docs/providers/aws/cli-reference/create.md
  docs/providers/aws/cli-reference/deploy-function.md
  docs/providers/aws/cli-reference/invoke-local.md
  docs/providers/aws/cli-reference/invoke.md
  docs/providers/aws/cli-reference/login.md
  docs/providers/aws/cli-reference/logs.md
  docs/providers/aws/cli-reference/metrics.md
  docs/providers/aws/cli-reference/rollback-function.md
  docs/providers/aws/events/apigateway.md
  docs/providers/aws/examples/hello-world/csharp/README.md
  docs/providers/aws/examples/hello-world/fsharp/README.md
  docs/providers/aws/examples/hello-world/go/README.md
  docs/providers/aws/examples/hello-world/node/README.md
  docs/providers/aws/examples/hello-world/python/README.md
  docs/providers/aws/examples/hello-world/ruby/README.md
  docs/providers/aws/guide/credentials.md
  docs/providers/aws/guide/services.md
  docs/providers/aws/guide/workflow.md
Labels: documentation

#10259 Exclude local plugins from bundle
  lib/classes/PluginManager.js
  lib/plugins/package/lib/packageService.js
  test/fixtures/programmatic/packaging/custom-plugins/plugin-2/index.js
  test/fixtures/programmatic/packaging/custom-plugins/plugin-3/package.json
  test/fixtures/programmatic/packaging/custom-plugins/plugin-3/src/main.js
  test/fixtures/programmatic/packaging/custom-plugins/plugin-4/index.js
  test/unit/lib/classes/PluginManager.test.js
  test/unit/lib/plugins/package/lib/packageService.test.js
Labels: bug, cat/packaging, cat/plugin

#10447 refactor(CLI Onboarding): Download templates from v2 examples branch
  lib/cli/interactive-setup/service.js
  test/unit/lib/cli/interactive-setup/service.test.js
Labels: refactor

#10430 fix(Templates): Upgrade `log4j` to `2.17.1`
  lib/plugins/create/templates/aws-java-maven/pom.xml
  lib/plugins/create/templates/aws-kotlin-jvm-gradle-kts/build.gradle.kts
  lib/plugins/create/templates/aws-kotlin-jvm-gradle/build.gradle
  lib/plugins/create/templates/aws-kotlin-jvm-maven/pom.xml
  lib/plugins/create/templates/aws-scala-sbt/build.sbt
Labels: cat/template

#10478 Variables: Resign from `projectDir` concept
  docs/providers/aws/guide/serverless.yml.md
  docs/providers/aws/guide/variables.md
  lib/configuration/variables/sources/file.js
  test/fixtures/programmatic/multiService/serviceA/serverless.yml
  test/unit/lib/configuration/variables/sources/file.test.js
Labels: enhancement, cat/variable

#10479 Packaging: Revert exclusion of local plugins from a bundle
  lib/plugins/package/lib/packageService.js
  test/unit/lib/plugins/package/lib/packageService.test.js
Labels: bug, cat/packaging

#10482 refactor(CLI Onboarding): Download templates from v3 examples branch
  lib/cli/interactive-setup/service.js
  test/unit/lib/cli/interactive-setup/service.test.js
Labels: refactor, cat/cli-onboarding

#10472 docs: Add `ts-node` dependency warning to README
  docs/providers/aws/guide/intro.md
Labels: documentation

#10484 fix(Templates): Ensure `esbuild` dependency in `aws-nodejs-typescript`
  lib/plugins/create/templates/aws-nodejs-typescript/package.json
Labels: cat/template

#10490 refactor(Config Schema): Do not rely on `ajv-keywords`
  lib/classes/ConfigSchemaHandler/regexpKeyword.js
  lib/classes/ConfigSchemaHandler/resolveAjvValidate.js
  package.json
Labels: cat/config-schema

#10495 docs: Document the migration for `serverless-dotenv-plugin`
  docs/guides/upgrading-v3.md
Labels: documentation

#10498 docs: Fix links
  docs/guides/dashboard.md
Labels: documentation

#10499 CLI: Respect old Node.js versions in version detection
  .github/workflows/integrate.yml
  .github/workflows/validate.yml
  bin/serverless.js
Labels: bug, cat/cli

#10509 CLI: Improve user message
  lib/cli/interactive-setup/dashboard-set-org.js
Labels: enhancement, cat/ci

#10502 refactor: Ensure support for `warn` mode for modern deprecations
  lib/utils/logDeprecation.js
Labels: bug, cat/cli

#10513 Remove not used dependencies
  package.json
Labels: refactor

#10510 feat(CLI Onboarding): Auto login if `--org` flag provided
  lib/cli/interactive-setup/dashboard-login.js
  test/unit/lib/cli/interactive-setup/dashboard-login.test.js
Labels: enhancement, cat/cli-onboarding

#10516 docs: Fix `initialize` hook reference in comment
  lib/plugins/aws/provider.js
Labels: documentation

#10522 docs: Various updates for the v3 release
  docs/deprecations.md
  docs/environment-variables.md
  docs/providers/aws/events/event-bridge.md
  docs/providers/aws/guide/variables.md
Labels: documentation

#10534 refactor: Refactor direct use of `@serverless/utils/log`
  lib/aws/request.js
  lib/configuration/variables/eventually-report-resolution-errors.js
  lib/plugins/aws/package/compile/functions.js
  lib/utils/npmPackage/isWritable.js
Labels: refactor

#10535 v3: Configuration reference cleanup
  docs/providers/aws/guide/serverless.yml.md
Labels: documentation

#10543 v3: Adapt to renames in `@serverless/dashboard-plugin`
  lib/cli/interactive-setup/aws-credentials.js
  lib/cli/interactive-setup/dashboard-set-org.js
  lib/cli/interactive-setup/deploy.js
  lib/cli/interactive-setup/utils.js
  test/unit/lib/cli/interactive-setup/aws-credentials.test.js
  test/unit/lib/cli/interactive-setup/dashboard-set-org.test.js
  test/unit/lib/cli/interactive-setup/deploy.test.js
  test/unit/lib/cli/interactive-setup/utils.test.js
Labels: refactor

#10554 fix: nesting-tracking in resolver aborting too eagerly
  lib/configuration/variables/resolve.js
  test/unit/lib/configuration/variables/sources/file.test.js
  test/unit/lib/configuration/variables/sources/fixture/file-function-many-variables.js
  test/unit/lib/configuration/variables/sources/fixture/file-function-many-variables.yaml
Labels: bug, cat/variable

#10551 test: Ensure we tests against unached version
  package.json
  test/unit/lib/plugins/aws/customResources/generateZip.test.js
Labels: tests

#10558 Test: Remove obsolete files
  test/unit/lib/plugins/aws/invokeLocal/fixture/.gitignore
  test/unit/lib/plugins/aws/invokeLocal/fixture/__init__.py
  test/unit/lib/plugins/aws/invokeLocal/fixture/asyncHandlerWithError.js
  test/unit/lib/plugins/aws/invokeLocal/fixture/asyncHandlerWithSuccess.js
  test/unit/lib/plugins/aws/invokeLocal/fixture/handler.py
  test/unit/lib/plugins/aws/invokeLocal/fixture/handler.rb
  test/unit/lib/plugins/aws/invokeLocal/fixture/handlerWithError.js
  test/unit/lib/plugins/aws/invokeLocal/fixture/handlerWithInitializationError.js
  test/unit/lib/plugins/aws/invokeLocal/fixture/handlerWithLoadingError.js
  test/unit/lib/plugins/aws/invokeLocal/fixture/handlerWithSuccess.js
Labels: tests

#10468 docs: Split the YAML reference in multiple sections
  docs/providers/aws/guide/serverless.yml.md
Labels: documentation

#10561 Docs: Remove outdated `anatomy` doc
  docs/anatomy.md
Labels: documentation

#10575 refactor(CLI Onboarding): Minor wording adjustments
  lib/cli/interactive-setup/dashboard-set-org.js
  lib/cli/interactive-setup/deploy.js
  test/unit/lib/cli/interactive-setup/index.test.js
Labels: refactor, cat/cli-onboarding

#10574 fix: Report more meaningful strict schema mode error
  lib/classes/config-schema-handler/resolve-ajv-validate.js
Labels: bug, cat/config-schema

#10577 docs: Add information about setting `frameworkVersion`
  docs/guides/upgrading-v3.md
Labels: documentation

#10582 fix(Templates): Update dependencies of `aws-nodejs-typescript` to v3
  lib/plugins/create/templates/aws-nodejs-typescript/package.json
Labels: cat/template

#10580 feat(AWS MSK): Support `maximumBatchingWindow`
  docs/providers/aws/events/msk.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/compile/events/msk/index.js
  test/integration/aws/infra-dependent/msk.test.js
  test/unit/lib/plugins/aws/package/compile/events/msk/index.test.js
Labels: enhancement, cat/aws-event-msk

#10591 feat(AWS Kafka): Support `maximumBatchingWindow`
  docs/providers/aws/events/kafka.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/compile/events/kafka.js
  test/unit/lib/plugins/aws/package/compile/events/kafka.test.js
Labels: enhancement, cat/aws-event-kafka

#10593 feat(AWS ActiveMQ): Support `maximumBatchingWindow`
  docs/providers/aws/events/activemq.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/compile/events/activemq.js
  test/unit/lib/plugins/aws/package/compile/events/activemq.test.js
Labels: enhancement

#10598 feat(AWS RabbitMQ): Support `maximumBatchingWindow`
  docs/providers/aws/events/rabbitmq.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/compile/events/rabbitmq.js
  test/unit/lib/plugins/aws/package/compile/events/rabbitmq.test.js
Labels: enhancement

#10603 chore: Rename `master` branch to `main`
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/integrate.yml
  .github/workflows/publish.yml
  .github/workflows/validate.yml
  package.json
  test/README.md
Labels: refactor

#10607 CLI: Fix support for `-c` (`--config`) shortcut
  scripts/serverless.js
  test/fixtures/programmatic/custom-config-filename/serverless.custom.yml
  test/unit/scripts/serverless.test.js
Labels: bug, cat/cli

#10608 CLI: Get `serverless-tencent` version from all supported locations
  lib/cli/render-version.js
Labels: bug, cat/cli
