Repository serverless/serverless, pull requests merged in 2022-06, with the labels that each got.

#11115 Console: Support new user settings format
  lib/classes/console.js
  lib/config-schema.js
  test/unit/lib/classes/console.test.js
Labels: enhancement, cat/console

#11084 Improve error message for CLI param validation
  lib/cli/parse-args.js
Labels: enhancement

#11152 docs: SC-202 Sync the README with the Getting started guide
  README.md
  docs/getting-started.md
Labels: documentation

#11155 docs: Fix Console link in README
  README.md
Labels: documentation

#11168 feat: Add `X-Amzn-Trace-Id` to default CORS headers
  docs/providers/aws/events/apigateway.md
  docs/providers/aws/events/http-api.md
  lib/plugins/aws/package/compile/events/api-gateway/lib/validate.js
  lib/plugins/aws/package/compile/events/http-api.js
  lib/plugins/aws/package/compile/functions.js
  test/fixtures/programmatic/api-gateway-extended/serverless.yml
  test/integration/aws/api-gateway.test.js
  test/unit/lib/plugins/aws/package/compile/events/api-gateway/lib/validate.test.js
  test/unit/lib/plugins/aws/package/compile/functions.test.js
Labels: enhancement, cat/aws-event-api-gateway

#11194 Issue template: Improve latest version requirement
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: documentation
