Repository serverless/serverless, pull requests merged in 2022-02, with the labels that each got.

#10610 docs: Clarify that upgrading isn't required when getting started
  docs/getting-started.md
Labels: documentation

#10617 fix(AWS Deploy): Properly apply `stackPolicy` with changesets
  lib/plugins/aws/lib/get-create-change-set-params.js
  lib/plugins/aws/lib/update-stack.js
  test/unit/lib/plugins/aws/deploy/index.test.js
Labels: bug, cat/deployment

#10620 fix(AWS Deploy): Ensure to clear `notificationArns` if needed
  lib/plugins/aws/lib/get-create-change-set-params.js
  test/unit/lib/plugins/aws/deploy/index.test.js
Labels: bug, cat/deployment

#10623 feat(CLI Onboarding): Improve deploy messaging
  lib/cli/interactive-setup/deploy.js
  test/unit/lib/cli/interactive-setup/deploy.test.js
Labels: enhancement, cat/cli-onboarding

#10636 docs: Reference changeset-related iam permissions
  CHANGELOG.md
  docs/guides/upgrading-v3.md
Labels: documentation

#10231 docs: Describe `configValidationMode` options
  docs/configuration-validation.md
Labels: documentation

#10654 docs: Mention need for `cloudformation:DescribeChangeSet`
  docs/guides/upgrading-v3.md
Labels: documentation

#10655 fix: Improve validation of min supported Node version
  CHANGELOG.md
  bin/serverless.js
  docs/guides/upgrading-v3.md
Labels: bug

#10653 docs: Fix typo in deprecations
  docs/deprecations.md
Labels: documentation

#10663 fix(Config Schema): Recognize `provider.websocketsDescription`
  docs/providers/aws/events/websocket.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/provider.js
Labels: bug, cat/config-schema

#10662 fix: Improve detection of `tty`
  lib/utils/telemetry/generate-payload.js
  package.json
  scripts/serverless.js
  test/unit/lib/utils/telemetry/generate-payload.test.js
Labels: bug, cat/cli

#10668 fix(AWS Deploy): Add descriptive error if S3 bucket cant be cleaned
  lib/plugins/aws/remove/lib/bucket.js
  test/unit/lib/plugins/aws/remove/index.test.js
Labels: bug, cat/deployment

#10690 docs: Update `mono-repo.md`
  docs/guides/cicd/mono-repo.md
Labels: documentation

#10686 refactor: Upgrade to `@serverless/test` in `v10`
  package.json
  test/integration-basic.test.js
  test/integration/aws/api-gateway-external.test.js
  test/integration/aws/api-gateway.test.js
  test/integration/aws/custom-deployment-bucket.test.js
  test/integration/aws/function.test.js
  test/integration/aws/http-api.test.js
  test/integration/aws/infra-dependent/active-mq.test.js
  test/integration/aws/infra-dependent/file-system-config.test.js
  test/integration/aws/infra-dependent/msk.test.js
  test/integration/aws/infra-dependent/rabbit-mq.test.js
  test/integration/aws/iot-fleet-provisioning.test.js
  test/integration/aws/websocket.test.js
  test/utils/api-gateway.js
  test/utils/cloudformation.js
  test/utils/cognito.js
  test/utils/dynamodb.js
  test/utils/event-bridge.js
  test/utils/iot.js
  test/utils/kinesis.js
  test/utils/misc.js
  test/utils/s3.js
  test/utils/sns.js
  test/utils/sqs.js
  test/utils/websocket.js
Labels: refactor

#10698 CLI: Ensure to pass through `serverless-tencent` exit code
  lib/cli/run-serverless-tencent.js
Labels: bug, cat/cli

#10704 docs: Improve `invoke local` documentation
  docs/providers/aws/cli-reference/invoke-local.md
Labels: documentation

#10708 CLI: Remove obsolete `v` postfix when listing global version
  lib/cli/render-version.js
Labels: refactor, cat/cli

#10710 docs: Remove reference to `-v` as shortcut for `--verbose`
  docs/providers/aws/cli-reference/deploy.md
  docs/providers/aws/cli-reference/info.md
  docs/providers/aws/cli-reference/remove.md
  docs/providers/aws/cli-reference/rollback.md
  docs/providers/aws/guide/services.md
  docs/providers/azure/cli-reference/deploy.md
  docs/providers/azure/cli-reference/rollback.md
  docs/providers/azure/guide/function-apps.md
  docs/providers/cloudflare/cli-reference/deploy.md
  docs/providers/fn/cli-reference/deploy.md
  docs/providers/kubeless/cli-reference/deploy.md
  docs/providers/kubeless/cli-reference/info.md
  docs/providers/kubeless/cli-reference/remove.md
  docs/providers/kubeless/guide/services.md
  docs/providers/openwhisk/cli-reference/deploy.md
  docs/providers/openwhisk/cli-reference/info.md
  docs/providers/openwhisk/guide/services.md
  docs/providers/spotinst/cli-reference/deploy.md
  docs/providers/spotinst/cli-reference/info.md
  docs/providers/spotinst/cli-reference/remove.md
  docs/providers/tencent/cli-reference/rollback.md
Labels: documentation

#10705 fix(AWS Local Invocation): Improve `ruby` context
  lib/plugins/aws/invoke-local/index.js
  lib/plugins/aws/invoke-local/runtime-wrappers/invoke.rb
Labels: enhancement, cat/local-dev, runtime/ruby

#10713 feat(Variables): Support for `--param` CLI options
  docs/guides/parameters.md
  lib/cli/commands-schema/common-options/service.js
  test/unit/lib/cli/filter-supported-options.test.js
Labels: enhancement, cat/variable, cat/cli

#10739 ci: Ensure id for cache step when publishing
  .github/workflows/publish.yml
Labels: cat/ci

#10746 fix(AWS API Gateway): Properly apply `description` to REST API
  lib/plugins/aws/package/compile/events/api-gateway/lib/rest-api.js
  test/unit/lib/plugins/aws/package/compile/events/api-gateway/lib/rest-api.test.js
Labels: bug, cat/aws-event-api-gateway

#10757 feat(AWS Lambda): Add support for `dotnet6` runtime
  lib/plugins/aws/provider.js
Labels: enhancement, cat/lambda, runtime/dotnet

#10762 Console: Add extra needed headers for ingestion requests
  lib/classes/console.js
Labels: enhancement, cat/console
