Repository serverless/serverless, pull requests merged in 2023-03, with the labels that each got.

#11768 docs: replace incorrect white space on SQS Event maxium concurrency
  docs/providers/aws/events/sqs.md
Labels: documentation

#11769 Suppress AWS SDK v2 deprecation message
  lib/aws/has-local-credentials.js
  lib/aws/request.js
  lib/aws/sdk-v2.js
  lib/cli/interactive-setup/aws-credentials.js
  lib/cli/interactive-setup/deploy.js
  lib/plugins/aws/package/compile/functions.js
  lib/plugins/aws/provider.js
  lib/utils/telemetry/generate-payload.js
  test/unit/lib/aws/request.test.js
Labels: refactor

#11772 Fix for #11675
  lib/plugins/aws/package/compile/events/api-gateway/lib/deployment.js
  test/unit/lib/cli/triage/fixtures/@serverless/compose/ts/project/serverless-compose.ts
  test/unit/lib/plugins/aws/package/compile/events/api-gateway/lib/stage/index.test.js
Labels: bug, cat/aws-event-api-gateway

#11778 fix: Changed Map for runtimeManagementMap
  lib/plugins/aws/package/compile/functions.js
  test/unit/lib/plugins/aws/package/compile/functions.test.js
Labels: bug, cat/lambda

#11785 remove invalid variable references from the documentation
  docs/providers/aws/guide/variables.md
Labels: documentation

#11793 refactor _.entries() to Object.entries()
  lib/plugins/aws/package/compile/events/api-gateway/lib/request-validator.js
  test/unit/lib/plugins/aws/package/compile/functions.test.js
Labels: refactor

#11794 replace lodash _.fromPairs() with Object.fromEntries()
  lib/utils/deep-sort-object-by-key.js
Labels: refactor

#11790 refactor async functions `/test/.../aws/.../events/apiGateway`
  test/unit/lib/plugins/aws/package/compile/events/api-gateway/index.test.js
  test/unit/lib/plugins/aws/package/compile/events/api-gateway/lib/authorizers.test.js
  test/unit/lib/plugins/aws/package/compile/events/api-gateway/lib/hack/disassociate-usage-plan.test.js
  test/unit/lib/plugins/aws/package/compile/events/api-gateway/lib/hack/update-stage.test.js
  test/unit/lib/plugins/aws/package/compile/events/api-gateway/lib/method/request-parameters.test.js
  test/unit/lib/plugins/aws/package/compile/events/api-gateway/lib/stage/index.test.js
  test/unit/lib/plugins/aws/package/compile/events/api-gateway/lib/validate.test.js
Labels: tests

#11789 Sanitize null Properties for AWS resources
  lib/plugins/aws/package/lib/strip-null-props-from-template-resources.js
  test/unit/lib/plugins/aws/package/lib/strip-null-props-from-template-resources.test.js
Labels: bug

#11797 refactor to remove BbPromise.each()
  lib/plugins/aws/package/compile/functions.js
Labels: refactor

#11798 mark async for functions under events s3, alb & lib
  test/unit/lib/plugins/aws/package/compile/events/alb/lib/health-check.test.js
  test/unit/lib/plugins/aws/package/compile/events/lib/ensure-api-gateway-cloud-watch-role.test.js
  test/unit/lib/plugins/aws/package/compile/events/s3/index.test.js
Labels: refactor, tests

#11799 refactor async functions under `test/.../aws/.../events`
  test/unit/lib/plugins/aws/package/compile/events/cognito-user-pool.test.js
  test/unit/lib/plugins/aws/package/compile/events/http-api.test.js
Labels: refactor, tests

#11801 refactor async functions under `test/unit/lib/plugins/aws/package/compile`
  test/unit/lib/plugins/aws/package/compile/functions.test.js
Labels: refactor, tests

#11803 refactor async functions under `test/unit/lib/plugins/aws/info`
  test/unit/lib/plugins/aws/info/get-api-key-values.test.js
  test/unit/lib/plugins/aws/info/get-resource-count.test.js
  test/unit/lib/plugins/aws/info/get-stack-info.test.js
  test/unit/lib/plugins/aws/info/index.test.js
Labels: refactor, tests

#11809 refactor async functions under `test/unit/lib/plugins/aws/remove`
  test/unit/lib/plugins/aws/remove/lib/stack.test.js
Labels: refactor, tests

#11788 Lambda alias events
  lib/plugins/aws/package/compile/events/activemq.js
  lib/plugins/aws/package/compile/events/alb/lib/target-groups.js
  lib/plugins/aws/package/compile/events/alexa-skill.js
  lib/plugins/aws/package/compile/events/alexa-smart-home.js
  lib/plugins/aws/package/compile/events/api-gateway/lib/authorizers.js
  lib/plugins/aws/package/compile/events/api-gateway/lib/method/authorization.js
  lib/plugins/aws/package/compile/events/api-gateway/lib/method/index.js
  lib/plugins/aws/package/compile/events/cloud-watch-event.js
  lib/plugins/aws/package/compile/events/cloud-watch-log.js
  lib/plugins/aws/package/compile/events/cognito-user-pool.js
  lib/plugins/aws/package/compile/events/event-bridge/index.js
  lib/plugins/aws/package/compile/events/http-api.js
  lib/plugins/aws/package/compile/events/iot-fleet-provisioning.js
  lib/plugins/aws/package/compile/events/iot.js
  lib/plugins/aws/package/compile/events/kafka.js
  lib/plugins/aws/package/compile/events/msk/index.js
  lib/plugins/aws/package/compile/events/rabbitmq.js
  lib/plugins/aws/package/compile/events/s3/index.js
  lib/plugins/aws/package/compile/events/schedule.js
  lib/plugins/aws/package/compile/events/sns.js
  lib/plugins/aws/package/compile/events/websockets/lib/authorizers.js
  lib/plugins/aws/package/compile/events/websockets/lib/integrations.js
  lib/plugins/aws/package/compile/events/websockets/lib/permissions.js
  lib/plugins/aws/package/compile/events/websockets/lib/validate.js
  test/unit/lib/plugins/aws/package/compile/events/activemq.test.js
  test/unit/lib/plugins/aws/package/compile/events/alias.test.js
  test/unit/lib/plugins/aws/package/compile/events/http-api.test.js
  test/unit/lib/plugins/aws/package/compile/events/iot-fleet-provisioning/index.test.js
  test/unit/lib/plugins/aws/package/compile/events/kafka.test.js
  test/unit/lib/plugins/aws/package/compile/events/msk/index.test.js
  test/unit/lib/plugins/aws/package/compile/events/rabbitmq.test.js
  test/unit/lib/plugins/aws/package/compile/events/websockets/lib/authorizers.test.js
  test/unit/lib/plugins/aws/package/compile/events/websockets/lib/integrations.test.js
  test/unit/lib/plugins/aws/package/compile/events/websockets/lib/permissions.test.js
  test/unit/lib/plugins/aws/package/compile/events/websockets/lib/validate.test.js
Labels: bug, cat/lambda

#11815 chore: bump dotenv-expand
  package.json
Labels: refactor

#11782 Serverless Console Dev Mode
  lib/cli/commands-schema/no-service.js
  lib/cli/interactive-setup/console-dev-mode-feed.js
  lib/cli/interactive-setup/console-enable-dev-mode.js
  lib/cli/interactive-setup/dashboard-login.js
  lib/cli/interactive-setup/dashboard-set-org.js
  lib/cli/interactive-setup/deploy.js
  lib/cli/interactive-setup/index.js
  package.json
  scripts/serverless.js
Labels: enhancement, cat/cli-onboarding, cat/console

#11818 Refactor async tests under `test/unit/lib/plugins/aws/invokeLocal`
  test/unit/lib/plugins/aws/lib/monitor-stack.test.js
  test/unit/lib/plugins/aws/lib/set-bucket-name.test.js
Labels: refactor, tests

#11819 Refactor async tests under `test/unit/lib/plugins/aws`
  test/unit/lib/plugins/aws/config-credentials.test.js
  test/unit/lib/plugins/aws/provider.test.js
  test/unit/lib/plugins/aws/rollback-function.test.js
  test/unit/lib/plugins/aws/rollback.test.js
Labels: refactor, tests

#11821 Add support for Description property to EventBridge rules
  docs/providers/aws/events/event-bridge.md
  docs/providers/aws/guide/serverless.yml.md
  lib/plugins/aws/package/compile/events/event-bridge/index.js
  test/unit/lib/plugins/aws/package/compile/events/event-bridge/index.test.js
Labels: enhancement, cat/aws-event-event-bridge

#11822 Refactor async tests under `test/unit/lib/classes`
  test/unit/lib/classes/config-schema-handler/index.test.js
  test/unit/lib/classes/plugin-manager.test.js
  test/unit/lib/classes/service.test.js
  test/unit/lib/classes/utils.test.js
Labels: refactor, tests

#11823 Refactor async tests under `test/unit/lib/plugins/package`
  test/unit/lib/plugins/package/lib/zip-service.test.js
  test/unit/lib/plugins/package/package.test.js
Labels: refactor, tests

#11832 Refactor async tests under `test/unit/lib/utils/`
  test/unit/lib/utils/download-template-from-repo.test.js
  test/unit/lib/utils/fs/create-zip-file.test.js
  test/unit/lib/utils/fs/read-file.test.js
  test/unit/lib/utils/fs/write-file-sync.test.js
  test/unit/lib/utils/fs/write-file.test.js
  test/unit/lib/utils/yaml-ast-parser.test.js
Labels: refactor, tests

#11833 refactor async tests under `test/unit/lib/plugins/plugin`
  test/unit/lib/plugins/plugin/lib/utils.test.js
  test/unit/lib/plugins/plugin/list.test.js
  test/unit/lib/plugins/plugin/search.test.js
Labels: refactor, tests

#11834 refactor async tests under `test/unit/lib`
  test/unit/lib/config-schema.test.js
  test/unit/lib/serverless.test.js
Labels: refactor, tests

#11838 refactor async tests under `test/integration`
  test/integration/aws/api-gateway-external.test.js
  test/integration/aws/api-gateway.test.js
  test/integration/aws/cognito-user-pool.test.js
  test/integration/aws/iot-fleet-provisioning.test.js
  test/integration/aws/s3.test.js
  test/integration/aws/schedule.test.js
  test/integration/aws/sns.test.js
  test/integration/aws/sqs.test.js
  test/integration/aws/stream.test.js
  test/integration/aws/websocket.test.js
Labels: refactor, tests

#11844 chore: Include dev mode verbose flag
  lib/cli/interactive-setup/console-dev-mode-feed.js
Labels: cat/cli, cat/console

#11845 chore: Updated dev mode step unit tests
  lib/cli/interactive-setup/console-enable-dev-mode.js
  test/unit/lib/cli/interactive-setup/console-enable-dev-mode.test.js
Labels: tests

#11848 chore: Updated unit tests for dev mode feed
  lib/cli/interactive-setup/console-dev-mode-feed.js
  test/unit/lib/cli/interactive-setup/console-dev-mode-feed.test.js
Labels: cat/cli, cat/console

#11851 Refactor async function under `lib/classes`
  lib/classes/utils.js
  lib/classes/yaml-parser.js
Labels: refactor

#11847 remove temp var `twoWayPassed`
  test/integration/aws/websocket.test.js
Labels: tests

#11849 Retain console properties on function deploy
  lib/plugins/aws/deploy-function.js
  package.json
  test/unit/lib/plugins/aws/deploy-function.test.js
Labels: enhancement, cat/cli, cat/console

#11854 Temporarily revert `dev` command
  lib/cli/commands-schema/no-service.js
  lib/cli/interactive-setup/console-dev-mode-feed.js
  lib/cli/interactive-setup/console-enable-dev-mode.js
  lib/cli/interactive-setup/console-setup-iam-role.js
  lib/cli/interactive-setup/dashboard-login.js
  lib/cli/interactive-setup/dashboard-set-org.js
  lib/cli/interactive-setup/deploy.js
  lib/cli/interactive-setup/index.js
  package.json
  scripts/serverless.js
  test/unit/lib/cli/interactive-setup/console-dev-mode-feed.test.js
  test/unit/lib/cli/interactive-setup/console-enable-dev-mode.test.js
  test/unit/lib/cli/interactive-setup/dashboard-login.test.js
  test/unit/lib/cli/interactive-setup/dashboard-set-org.test.js
Labels: enhancement, cat/console

#11855 Allow OriginAccessControlId field for CloudFront origins
  lib/plugins/aws/package/compile/events/cloud-front.js
Labels: enhancement, cat/aws-event-cloudfront

#11853 Refactor to get rid of Promise resolve/reject
  test/unit/lib/classes/plugin-manager.test.js
  test/unit/lib/plugins/aws/utils/credentials.test.js
  test/unit/lib/plugins/aws/utils/resolve-cf-import-value.test.js
  test/unit/lib/plugins/aws/utils/resolve-cf-ref-value.test.js
  test/unit/lib/plugins/plugin/lib/utils.test.js
  test/unit/lib/plugins/plugin/list.test.js
  test/unit/lib/plugins/plugin/search.test.js
  test/unit/lib/utils/download-template-from-repo.test.js
  test/utils/kinesis.js
Labels: refactor, tests

#11863 fix(AWS Deploy): Handle error for abnormal CloudFormation stack state during AWS deployment
  lib/plugins/aws/deploy/lib/create-stack.js
  test/unit/lib/plugins/aws/deploy/index.test.js
  test/unit/lib/plugins/aws/deploy/lib/check-for-changes.test.js
  test/unit/lib/plugins/aws/deploy/lib/upload-artifacts.test.js
  test/unit/lib/plugins/aws/package/compile/events/api-gateway/lib/hack/update-stage.test.js
  test/unit/lib/plugins/package/lib/package-service.test.js
Labels: refactor, cat/deployment

#11875 Refactor to remove Promise.bind()
  lib/plugins/aws/package/compile/events/activemq.js
  lib/plugins/aws/package/compile/events/alexa-skill.js
  lib/plugins/aws/package/compile/events/alexa-smart-home.js
  lib/plugins/aws/package/compile/events/cloud-front.js
  lib/plugins/aws/package/compile/events/cloud-watch-event.js
  lib/plugins/aws/package/compile/events/cloud-watch-log.js
  lib/plugins/aws/package/compile/events/cognito-user-pool.js
  lib/plugins/aws/package/compile/events/event-bridge/index.js
  lib/plugins/aws/package/compile/events/iot-fleet-provisioning.js
  lib/plugins/aws/package/compile/events/iot.js
  lib/plugins/aws/package/compile/events/kafka.js
  lib/plugins/aws/package/compile/events/msk/index.js
  lib/plugins/aws/package/compile/events/rabbitmq.js
  lib/plugins/aws/package/compile/events/schedule.js
  lib/plugins/aws/package/compile/events/sns.js
  lib/plugins/aws/package/compile/events/sqs.js
  lib/plugins/aws/package/compile/events/stream.js
  lib/plugins/aws/package/compile/layers.js
  lib/plugins/aws/remove/lib/stack.js
  lib/plugins/create/create.js
  lib/plugins/install.js
  lib/plugins/invoke.js
  lib/plugins/package/package.js
  lib/plugins/plugin/list.js
  lib/plugins/plugin/search.js
  test/fixtures/programmatic/package-artifact-in-serverless-dir/package-artifact-plugin.js
  test/unit/lib/classes/plugin-manager.test.js
Labels: refactor
