Repository serverless/serverless, pull requests merged in 2023-05, with the labels that each got.

#11893 Avoid lambda permission for log subscriptions from depending on itself
  lib/plugins/aws/package/compile/events/cloud-watch-log.js
  test/unit/lib/plugins/aws/package/compile/events/cloud-watch-log.test.js
Labels: bug, cat/aws-event-cloudwatch

#11938 feat: Support for Java17 as runtime for AWS Lambda functions
  docs/providers/aws/guide/functions.md
  lib/plugins/aws/invoke-local/index.js
  lib/plugins/aws/provider.js
Labels: enhancement, cat/lambda

#11941 Added missing .NET runtimes
  lib/plugins/aws/provider.js
Labels: enhancement, cat/lambda

#11922 feat(AWS Lambda): Supports Python3.10
  lib/plugins/aws/invoke-local/index.js
  lib/plugins/aws/provider.js
Labels: enhancement, cat/lambda

#11905 Replace BbPromise usages
  test/integration/aws/cognito-user-pool.test.js
  test/integration/aws/s3.test.js
  test/unit/lib/plugins/aws/custom-resources/index.test.js
  test/unit/lib/plugins/aws/package/compile/events/lib/ensure-api-gateway-cloud-watch-role.test.js
  test/unit/lib/plugins/deploy.test.js
Labels: refactor, bug/dependency

#11940 fix: Remove references to deprecated AWS Lambda runtimes
  docs/providers/aws/guide/functions.md
  docs/providers/kubeless/cli-reference/create.md
  docs/providers/kubeless/cli-reference/info.md
  docs/providers/kubeless/events/http.md
  docs/providers/kubeless/events/pubsub.md
  docs/providers/kubeless/guide/debugging.md
  docs/providers/kubeless/guide/deploying.md
  docs/providers/kubeless/guide/functions.md
  docs/providers/kubeless/guide/services.md
  docs/providers/spotinst/examples/python/README.md
  docs/providers/tencent/cli-reference/create.md
  lib/plugins/aws/invoke-local/index.js
  lib/plugins/aws/provider.js
  test/unit/lib/cli/interactive-setup/dashboard-login.test.js
  test/unit/lib/cli/interactive-setup/dashboard-set-org.test.js
  test/unit/lib/plugins/aws/invoke-local/index.test.js
Labels: refactor, cat/lambda

#11967 fix: Adding support for '$or' property in EventBridge pattern schema
  lib/plugins/aws/package/compile/events/event-bridge/index.js
  test/unit/lib/plugins/aws/package/compile/events/event-bridge/index.test.js
Labels: enhancement, cat/aws-event-event-bridge

#11972 Fix `provider.layers` support in `deploy function` command
  lib/plugins/aws/deploy-function.js
  test/unit/lib/plugins/aws/deploy-function.test.js
Labels: bug, cat/deployment

#11935 Add ability to create AWS::Scheduler::Schedule triggers and specify timezone
  docs/providers/aws/events/schedule.md
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/package/compile/events/schedule.js
  test/unit/lib/plugins/aws/lib/naming.test.js
  test/unit/lib/plugins/aws/package/compile/events/schedule.test.js
Labels: enhancement, cat/aws-event-schedule

#9706 Unique stream consumer name per service and stage
  docs/deprecations.md
  lib/plugins/aws/lib/naming.js
  lib/plugins/aws/package/compile/events/stream.js
  lib/plugins/aws/provider.js
  test/unit/lib/plugins/aws/package/compile/events/stream.test.js
Labels: enhancement, cat/aws-event-stream

#11976 refactor: Updated dev mode warning copy
  lib/cli/interactive-setup/console-dev-mode-feed.js
  lib/cli/interactive-setup/console-enable-dev-mode.js
Labels: refactor, cat/cli

#11974 11879 warning for func package patterns
  lib/plugins/package/lib/package-service.js
Labels: enhancement, cat/packaging

#11980 feat: add support for writing minified JSON
  lib/cli/commands-schema/aws-service.js
  lib/plugins/aws/package/lib/save-compiled-template.js
  test/unit/lib/plugins/aws/package/lib/save-compiled-template.test.js
Labels: enhancement, cat/deployment

#11907 AWS Lambda response streaming for Lambda URLs
  docs/providers/aws/guide/functions.md
  lib/plugins/aws/package/compile/functions.js
  lib/plugins/aws/provider.js
  package.json
  test/fixtures/programmatic/function/stream.js
  test/integration/aws/function-url.test.js
  test/unit/lib/plugins/aws/package/compile/functions.test.js
Labels: enhancement, cat/lambda

#11985 added custom resource lambda in vpc if vpc is configured
  lib/plugins/aws/custom-resources/index.js
  test/unit/lib/plugins/aws/custom-resources/index.test.js
Labels: bug, cat/deployment

#11888 fix: allow multiple alb http-header conditions
  lib/plugins/aws/package/compile/events/alb/index.js
  lib/plugins/aws/package/compile/events/alb/lib/listener-rules.js
  lib/plugins/aws/package/compile/events/alb/lib/validate.js
  test/unit/lib/plugins/aws/package/compile/events/alb/index.test.js
Labels: enhancement, cat/aws-event-alb
