Repository serverless/serverless, pull requests merged in 2023-04, with the labels that each got.

#11885 Remove promise resolve() & reject() function calls
  test/fixtures/programmatic/invocation/doubled-resolution-promise-first.js
  test/unit/commands/logout.test.js
  test/unit/lib/aws/request.test.js
  test/unit/lib/plugins/aws/rollback.test.js
Labels: refactor

#11896 Dev command
  docs/guides/dev.md
  lib/cli/commands-schema/no-service.js
  lib/cli/interactive-setup/console-dev-mode-feed.js
  lib/cli/interactive-setup/console-enable-dev-mode.js
  lib/cli/interactive-setup/console-login.js
  lib/cli/interactive-setup/console-resolve-org.js
  lib/cli/interactive-setup/console-setup-iam-role.js
  lib/cli/interactive-setup/dashboard-login.js
  lib/cli/interactive-setup/dashboard-set-org.js
  lib/cli/interactive-setup/deploy.js
  lib/cli/interactive-setup/index.js
  lib/cli/interactive-setup/utils.js
  package.json
  scripts/serverless.js
  test/unit/lib/cli/interactive-setup/console-dev-mode-feed.test.js
  test/unit/lib/cli/interactive-setup/console-enable-dev-mode.test.js
  test/unit/lib/cli/interactive-setup/dashboard-login.test.js
  test/unit/lib/cli/interactive-setup/dashboard-set-org.test.js
  test/unit/lib/cli/interactive-setup/deploy.test.js
Labels: enhancement, cat/cli, cat/console

#11898 chore: Added explorerTraceTime
  lib/cli/interactive-setup/console-dev-mode-feed.js
Labels: enhancement, cat/cli, cat/console

#11899 chore: Release v3.30.0
  CHANGELOG.md
  package.json
Labels: cat/cli, cat/console

#11900 Ensure to not login back accidentaly on logout operation
  package.json
  scripts/serverless.js
Labels: bug, cat/console
